import {item,PALETTE} from './life-state.js';
import {T,C,v} from './kit.js';
import {PEOPLE,PATTERNS,SIDEQUESTS,MATERIALS,count,give,spend,describeCost,availableFood,takeFood,craftOutfit,outfitOK,grantPattern,worldUnlocked,worldLock,tickWorld,gather,bridgeReady,waterReady,flowerReady} from './adventure-state.js';
import {enrichAdventure} from './adventure-world.js';
import {grow} from './craft-state.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(label,a,val='',extra='')=>`<button data-world="${a}" data-value="${val}" ${extra}>${label}</button>`;
export function createAdventure({life,W,camera,scene,bridge,travel,openLife}){
 const s=life.state,w=s.world;let ctx=null,model=null,opened=false,page='journal',selected=null,talkAt=0,cooperator=null,coopTime=0,hold=null,care=null,petCourse=null,depth=0,flight=null,returnPoint=null,dtSave=0,uiClock=0,walked=0,lastWalk=null,toastTimer=null,transition=0,selectedBridge=0,bridgeRot=0,hoverPanel=false;
 const ui=document.createElement('section');ui.id='adventure-panel';ui.hidden=true;ui.setAttribute('aria-label','星光海屿旅行手册');ui.innerHTML=`<header><div><small>星光嘉年华筹备手册</small><h2 id="adventure-title">星光海屿群岛</h2></div>${btn('收起','close','','aria-label="收起旅行手册"')}</header><nav>${[['journal','世界地图'],['bag','背包'],['people','伙伴故事'],['patterns','图纸制作'],['pets','动物伙伴']].map(([a,n])=>btn(n,'page',a)).join('')}</nav><div id="adventure-body"></div><footer id="adventure-status" role="status"></footer>`;document.body.append(ui);
 const hud=document.createElement('div');hud.id='adventure-hud';hud.innerHTML=`${btn('星光海屿 · 地图与主线','open')}<span id="adventure-goal"></span>${btn('背包','page','bag')}`;document.body.append(hud);const $=q=>ui.querySelector(q);const body=$('#adventure-body');
 function note(t){$('#adventure-status').textContent=t;ctx?.note(t);if(!ctx)bridge.toast?.(t);}
 function persist(){life.persist();}
 function primary(){if(!w.flags.prologue)return '序章 · 为朋友准备旅行礼物';if(!w.flags.valley)return '第一章 · 恢复风铃山谷的水车与温室';if(!w.flags.islands)return '第二章 · 点亮航标，布置群岛庆典';if(!w.flags.ocean)return '第三章 · 重启海底花园的乐章';return w.festival.complete?'嘉年华进行中 · 继续拜访朋友与探索':'终章 · 邀请伙伴，完成嘉年华布置';}
 function open(next='journal',p=null){opened=true;page=next;selected=p;ui.hidden=false;document.body.classList.add('adventure-open');ctx?.keys.clear();render();}
 function close(){opened=false;ui.hidden=true;document.body.classList.remove('adventure-open');hold=null;}
 function location(){return !ctx?'粉晶主岛':ctx.mode==='bus'?(depth?'山谷 · 根系洞窟':'风铃山谷'):ctx.mode==='yacht'?(flight?'群岛上空':'蔚蓝外海群岛'):'深海琉璃海沟';}
 function journal(){const r=[['home','粉晶主岛','豪宅 · 农场 · 衣帽宫 · 沙滩'],['bus','风铃山谷','山路 · 森林小镇 · 温室 · 根系洞窟'],['yacht','蔚蓝外海群岛','游艇 · 潮汐海岛 · 灯塔 · 天空城堡'],['submarine','深海琉璃海沟','潜艇 · 珊瑚拱 · 沉船 · 海底花园']];return `<p class="adv-eyebrow">当前：${location()} · 游戏第 ${1+Math.floor(w.time/1440)} 天</p><h3>${primary()}</h3><div class="adv-map">${r.map(([id,n,desc])=>`<article class="adv-region ${id}"><b>${n}</b><p>${desc}</p><small>${id==='home'||worldUnlocked(w,id)?'航路已开放':worldLock(w,id)}</small>${btn(id==='home'?'返回主岛':worldUnlocked(w,id)?'前往地区':'尚未解锁','region',id,id==='home'||worldUnlocked(w,id)?'':'disabled')}</article>`).join('')}</div><h3>嘉年华筹备</h3><p>邀请伙伴 ${w.invited.length}/3 · 餐点 ${w.festival.food}/4 · 花艺 ${w.festival.flowers}/4 · 布料 ${w.festival.cloth}/4</p>${!w.flags.prologue?`<div class="adv-card"><b>芭比的旅行来信</b><p>带一份亲手制作、评分至少 55 的饮品或蛋糕，以及两份草莓。初始农场有成熟草莓，制作好的餐点会进入共同背包。</p>${btn('读芭比的来信','letter')}${btn('交付旅行礼物','prologue')}${btn('去农场','work','farm')}${btn('调一杯饮品','work','mix')}</div>`:''}<div class="adv-checks"><p>${w.flags.bridge?'✓':'○'} 修复溪桥　${w.flags.water?'✓':'○'} 恢复分流　${w.flags.greenhouse?'✓':'○'} 唤醒温室</p><p>${w.flags.valley?'✓':'○'} 邀请米拉　${w.flags.islands?'✓':'○'} 开通潜航　${w.flags.ocean?'✓':'○'} 恢复海洋乐章</p></div>${w.flags.ocean?`${btn('交付一份宴会餐点','festival','food')}${btn('交付花材 ×4','festival','flowers')}${btn('交付布料 ×4','festival','cloth')}${btn('举办星光嘉年华','celebrate','','class="primary"')}`:''}<h3>主岛的生活</h3><div class="adv-buttons">${[['fashion','衣帽工坊'],['farm','农场'],['pet','照料动物'],['mix','调饮'],['cupcake','蛋糕裱花'],['sand','沙堡'],['blocks','积木'],['service','多订单厨房'],['home','自由布置房间']].map(([id,n])=>btn(n,'work',id)).join('')}</div><h3>旅程设置</h3>${btn(w.sound?'关闭地区音乐':'开启地区音乐','music')}${['day','dusk','night'].map((k,i)=>btn(['晴日','黄昏','星夜'][i],'weather',k,`aria-pressed="${w.weather===k}"`)).join('')}<p><small>手册与对话期间暂停经营计时。离线期间动物状态和食品保质时间暂停。旧衣橱、金币和作品沿用当前浏览器存档。</small></p>`;}
 function bag(){return `<h3>材料仓库 · ${s.coins} 梦想币</h3><div class="adv-inventory">${Object.entries(MATERIALS).map(([k,n])=>`<div><span>${n}</span><b>${count(s,k)}</b></div>`).join('')}</div><h3>随身餐点</h3>${w.food.length?w.food.map(f=>`<article class="adv-card"><b>${esc(f.name)} · ${f.score} 分</b><small>${f.expires>w.time?'保鲜剩余 '+Math.ceil((f.expires-w.time)/60)+' 分钟':'已过保鲜期，可堆肥'} · ${f.tags.map(t=>({berry:'莓果',milk:'奶香',flower:'花香',mint:'清爽'}[t]||t)).join(' / ')}</small>${f.expires<=w.time?btn('堆肥 · 返回花材','compost',f.id):''}</article>`).join(''):'<p>到厨房或饮品吧亲手制作，成品会装入背包。</p>'}<p>基础采集点每 4 分钟游玩时间恢复；星光碎片和珍藏图纸只领取一次。</p>${btn('查看图纸','page','patterns')}`;}
 function patterns(){return `<h3>图纸与手工制作</h3><p>装备制作完成后仍需到衣帽工坊穿上。山路检查服装与鞋履，深海检查潜航服。</p>${Object.entries(PATTERNS).map(([id,p])=>`<article class="adv-card"><b>${p.name}</b><p>${describeCost(p.cost)}</p><small>${s.owned.includes(id)?'已制作，永久保留':w.patterns.includes(id)?'已拥有图纸':'图纸来源：'+p.source}</small>${btn(s.owned.includes(id)?'去试穿':'手工制作','craft',id,s.owned.includes(id)||w.patterns.includes(id)?'':'disabled')}</article>`).join('')}${btn('局部染色与试穿','work','fashion')}`;}
 function people(){return `<h3>伙伴与生活故事</h3>${Object.entries(PEOPLE).filter(([id])=>id!=='barbie').map(([id,p])=>`<article class="adv-card"><b>${p.name} · ${p.role}</b><small>好感 ${w.affection[id]}/100 · ${w.invited.includes(id)?'已接受嘉年华邀请':'等待一起经历的故事'}</small>${SIDEQUESTS.filter(q=>q.npc===id).map(q=>`<p><b>${w.completed.includes(q.id)?'✓ ':''}${q.title}</b><br>${q.desc}<br><small>${q.reward}</small>${btn(w.completed.includes(q.id)?'故事已完成':w.accepted.includes(q.id)?'已记入手册':'记下这条委托','accept',q.id,w.completed.includes(q.id)||w.accepted.includes(q.id)?'disabled':'')}</p>`).join('')}</article>`).join('')}<small>记下委托后，前往居民身边交付。居民会根据完成的故事继续对话。</small>`;}
 function pets(){return `<h3>动物伙伴</h3>${Object.entries(w.pets).map(([id,p])=>`<article class="adv-card"><b>${p.name} · ${id==='bell'?'山谷小鹿':id==='coco'?'花店猫咪':'海豚'}</b><p>饱腹 ${Math.round(p.food)}　清洁 ${Math.round(p.clean)}<br>心情 ${Math.round(p.joy)}　体力 ${Math.round(p.energy)}<br>好感 ${Math.round(p.bond)}　能力 ${p.trained}/3</p><small>${p.job?(p.job==='class'?'正在上课':p.job==='garden'?'在花园帮忙':'在店里招待')+' · 剩余 '+Math.ceil(90-p.jobTime)+' 秒':'可在地图中找到它，照料、上课或带着出门'}</small></article>`).join('')}`;}
 function npcPanel(p){const n=PEOPLE[p.npc],lines=n.lines;return `<p class="adv-eyebrow">${n.role} · 好感 ${w.affection[p.npc]}/100</p><blockquote>${lines[Math.min(talkAt,lines.length-1)]}</blockquote>${talkAt<lines.length-1?btn('继续听','talkNext','','class="primary"'):`${btn('邀请同行协助','companion',p.npc)}${btn('送一份合口味的餐点','gift',p.npc)}`}<h3>带来的委托</h3>${SIDEQUESTS.filter(q=>q.npc===p.npc).map(q=>`<article class="adv-card"><b>${q.title}</b><p>${q.desc}</p>${btn(w.completed.includes(q.id)?'已经完成':w.accepted.includes(q.id)?'交付并继续故事':'接下委托',w.accepted.includes(q.id)?'deliverQuest':'accept',q.id,w.completed.includes(q.id)?'disabled':'')}</article>`).join('')}${p.npc==='mira'&&w.flags.greenhouse?btn('邀请米拉参加嘉年华','invite','mira','class="primary"'):''}${p.npc==='joey'&&w.flags.islands?btn('邀请乔伊参加嘉年华','invite','joey'):''}${p.npc==='neri'&&w.flags.ocean?btn('邀请澜汐参加嘉年华','invite','neri'):''}`;}
 function petPanel(p){const a=w.pets[p.pet];return `<p>饱腹 ${Math.round(a.food)} · 清洁 ${Math.round(a.clean)} · 心情 ${Math.round(a.joy)}<br>体力 ${Math.round(a.energy)} · 好感 ${Math.round(a.bond)} · 能力 ${a.trained}/3</p><div class="adv-buttons">${btn('喂食 · 草莓 ×1','care','feed')}${btn('清洗与梳理','care','groom')}${btn('陪它玩一会儿','care','play')}${btn('练习气味 / 声纹路线','course')}${btn('带着一起出门','follow',p.pet)}${btn('安排课堂 · 90 秒','job','class')}${btn('花园帮忙 · 90 秒','job','garden')}${btn('店里招待 · 90 秒','job','shop')}</div><p>课堂与工作需要饱腹、清洁和体力均至少 45；学习期间会留在这里。完成寻物练习可引导你寻找隐藏宝箱。</p>${btn('结束安排，接它回来','job','stop')}`;}
 function puzzlePanel(p){
  if(p.type==='bridge')return `<p>四块构件要连续支撑河面。旧桥图案：<b>横梁—顺桥板—横梁—顺桥板</b>。横梁旋转 90°，桥板顺着溪桥摆放。</p><div class="adv-buttons">${[0,1,2,3].map(i=>btn('选第 '+(i+1)+' 段','bridgeSelect',i,`aria-pressed="${selectedBridge===i}"`)).join('')}${btn('旋转构件 90°','bridgeRotate')}${btn('放入选中位置','bridgePlace')}</div><p>待放构件：${bridgeRot?'横向':'顺向'} · 已放 ${w.puzzles.bridge.length}/4</p>${btn('让乔伊固定绞盘','helper','joey')}${btn('承重测试 · 木材 ×2 / 树脂 ×1','bridgeTest','','class="primary"')}<small>完成后桥会保留，可继续调节水车。支撑错误只需要调整对应构件。</small>`;
  if(p.type==='water')return `<p>沿水渠检查旧刻度：<b>水车三格、温室两格</b>。需要乔伊持续固定闸门，你来控制分流。</p>${[0,1].map(i=>`<label>${i?'温室支渠':'水车支渠'} <input type="range" min="0" max="5" step="1" data-world-range="valve" data-index="${i}" value="${w.puzzles.valves[i]}"><output>${w.puzzles.valves[i]} 格</output></label>`).join('')}${btn('请乔伊固定闸门','helper','joey')}${btn('保持分流并测试水流','waterTest','','class="primary"')}<p>${w.flags.bridge?'溪桥可通行':'需要先修好旁边的溪桥'} · ${w.flags.water?'供水已经恢复':'让正确水流保持 4 秒'}</p>`;
  if(p.type==='flowers')return `<p>温室笔记：晨光落在<b>东镜 2、西镜 5</b>的星标上。米拉引导藤蔓接水，你把光带到三朵花上。</p>${[0,1].map(i=>`<label>${i?'西镜':'东镜'} <input type="range" min="0" max="7" step="1" data-world-range="mirror" data-index="${i}" value="${w.puzzles.mirrors[i]}"><output>${w.puzzles.mirrors[i]}</output></label>`).join('')}${btn('请米拉引导藤蔓','helper','mira')}<div class="adv-buttons">${[0,1,2].map(i=>btn((w.puzzles.flowers[i]?'✓ ':'')+'引光到第 '+(i+1)+' 朵花','flower',i)).join('')}</div>${btn('保持光与水，唤醒花圃','flowerTest','','class="primary"')}<p>山路穿搭：${outfitOK(s,'trail')?'已满足':'需要徒步装或水手装，并穿防滑短靴 / 深色靴'}</p>${btn('去衣帽工坊换装','work','fashion')}`;
  if(p.type==='tide')return `<p>让三座浮台形成连续阶梯，再请乔伊固定绞盘。沙滩石刻的高度从岸边向外为 <b>1、2、1</b>。先在附近沙滩保存一座带城墙与拱门的沙堡，为浮台阻挡侧向水流。</p>${[0,1,2].map(i=>`<label>浮台 ${i+1}<input type="range" min="0" max="3" step="1" data-world-range="tide" data-index="${i}" value="${w.puzzles.tide[i]}"></label>`).join('')}${btn('调整沙堡与导流墙','work','sand')}${btn('请乔伊固定浮台','helper','joey')}${btn('测试连续通路','tideTest','','class="primary"')}`;
  if(p.type==='sound')return `<p>在珊瑚、沉船、海沟回收的观测匣分别记录了声阶 <b>1、3、2</b>。依照来源顺序调准共鸣柱；请澜汐保持水流安静。</p>${[0,1,2].map(i=>`<label>共鸣柱 ${i+1}<input type="range" min="0" max="4" step="1" data-world-range="sound" data-index="${i}" value="${w.puzzles.sound[i]}"></label>`).join('')}${btn('请澜汐安抚海洋伙伴','helper','neri')}${btn('持续共鸣，唤醒海底花园','soundTest','','class="primary"')}`;
  return '';
 }
 function render(){if(!opened)return;$('#adventure-title').textContent=selected?.name||({journal:'星光海屿群岛',bag:'共同背包',people:'伙伴与支线',patterns:'手工衣帽工坊',pets:'动物伙伴'}[page]||'星光海屿');body.innerHTML=page==='journal'?journal():page==='bag'?bag():page==='people'?people():page==='patterns'?patterns():page==='pets'?pets():page==='npc'?npcPanel(selected):page==='pet'?petPanel(selected):page==='puzzle'?puzzlePanel(selected):page==='letter'?`<blockquote>${PEOPLE.barbie.lines[Math.min(talkAt,2)]}</blockquote>${btn(talkAt<2?'继续读信':'收好来信',talkAt<2?'talkNext':'close')}`:'';for(const b of ui.querySelectorAll('[data-world="page"]'))b.setAttribute('aria-pressed',String(b.dataset.value===page));}
 function payQuest(id){const q=SIDEQUESTS.find(q=>q.id===id);if(!q||w.completed.includes(id)||selected?.npc!==q.npc)return;let ok=false;
  if(id==='ribbon'&&w.chests.includes('ribbon'))ok=spend(s,{lace:1});
  if(id==='dress'&&w.flags.greenhouse&&['petalcouture','picnicdress','trail','valleycouture'].includes(s.look.dress))ok=!!takeFood(s,null,'flower',60);
  if(id==='plane'&&w.flags.islands&&count(s,'cloth')>=2&&availableFood(s,'drink','berry',55).length){spend(s,{cloth:2});takeFood(s,'drink','berry',55);ok=true;}
  if(id==='cake'){const cake=availableFood(s,'cake','milk',75)[0],drink=availableFood(s,'drink',null,60)[0];if(cake&&drink){w.food=w.food.filter(f=>f.id!==cake.id&&f.id!==drink.id);ok=true;}}
  if(id==='letter'&&w.flags.letter&&w.flags.ocean)ok=!!takeFood(s,'drink','mint',55);
  if(id==='picnic'&&ctx?.state.arrivals===3)ok=spend(s,{wheat:2,berry:2});
  if(id==='flowers'&&w.weather==='night')ok=spend(s,{flower:3});
  if(id==='stage'&&s.craft.builds.blocks.some(p=>p.y>=1))ok=!!takeFood(s,'cake',null,70);
  if(id==='dolphin'&&w.pets.pearl.trained>0&&w.flags.ocean)ok=true;
  if(!ok){note('还缺少委托里的条件：'+q.desc);return;}w.completed.push(id);w.affection[q.npc]=Math.min(100,w.affection[q.npc]+18);s.coins+=35;for(const [quest,pattern]of [['dress','valleycouture'],['plane','rosepilot'],['cake','chefcouture'],['letter','oceanweave']])if(id===quest)grantPattern(w,pattern);if(id==='ribbon'){give(s,'lace',2);w.flags.ribbon=true;}if(id==='cake')w.flags.cooler=true;if(id==='plane')w.flags.plane=true;if(id==='picnic')give(s,'cloth',3);if(id==='flowers')give(s,'lace',1);if(id==='stage'){give(s,'cloth',2);w.service.level=Math.min(2,w.service.level+1);}if(id==='dolphin')give(s,'pearl',3);note('故事完成：'+q.title+'。'+q.reward);persist();render();}
 function action(a,val=''){
  if(a==='open'){open();return;}if(a==='close'){close();return;}if(a==='page'){open(val);return;}if(a==='letter'){talkAt=0;w.started=true;open('letter');persist();return;}
  if(a==='region'){if(val==='home'){close();travel()?.close();return;}if(!worldUnlocked(w,val)){note(worldLock(w,val));return;}close();travel()?.open(val);return;}
  if(a==='work'){close();const origin=ctx?.mode;openLife(val,origin);return;}
  if(a==='prologue'){if(w.flags.prologue)return;if(count(s,'berry')<2||!availableFood(s,null,null,55).length){note('需要草莓 ×2 和一份评分至少 55 的饮品 / 蛋糕。');return;}give(s,'berry',-2);takeFood(s,null,null,55);w.flags.prologue=true;w.started=true;w.affection.barbie=10;give(s,'cloth',2);note('旅行礼物已装好！大巴航路开放，米拉在风铃山谷等你。');}
  if(a==='craft'){if(s.owned.includes(val)){close();openLife('fashion',ctx?.mode);return;}note(craftOutfit(s,val)?'已制作，永久加入衣橱。去工坊穿上即可使用。':'还需要对应图纸和材料。');}
  if(a==='accept'){if(!w.accepted.includes(val)&&SIDEQUESTS.some(q=>q.id===val)){w.accepted.push(val);note('委托已记入手册。可以随时去做别的事情，再回来继续。');}}
  if(a==='deliverQuest'){payQuest(val);return;}if(a==='talkNext'){talkAt++;if(selected?.npc)w.dialogue[selected.npc]=Math.max(w.dialogue[selected.npc]||0,talkAt);}
  if(a==='companion'){if(talkAt<2)return;setHelper(val);note(PEOPLE[val].name+'愿意一起探索。到机关旁可以请伙伴就位。');}
  if(a==='gift'){if(selected?.npc!==val)return;const f=takeFood(s,null,PEOPLE[val].taste,55);if(!f){note('这位伙伴喜欢'+({flower:'花香',berry:'莓果',milk:'奶香',mint:'清爽'}[PEOPLE[val].taste])+'，背包里还没有合适的成品。');return;}w.affection[val]=Math.min(100,w.affection[val]+Math.round(f.score/10));w.gifted[val]=(w.gifted[val]||0)+1;note(PEOPLE[val].name+'接过了「'+f.name+'」，好感增加。');}
  if(a==='invite'){const ready=val==='mira'?w.flags.greenhouse:val==='joey'?w.flags.islands:w.flags.ocean;if(!ready||selected?.npc!==val)return;if(!w.invited.includes(val))w.invited.push(val);if(val==='mira'){w.flags.valley=true;}note(PEOPLE[val].name+'接受了邀请，嘉年华会为她留出展位。');}
  if(a==='compost'){const f=w.food.find(f=>f.id===+val&&f.expires<=w.time);if(f){w.food=w.food.filter(x=>x!==f);give(s,'flower',1);}}
  if(a==='helper'){if(!selected||!ctx)return;setHelper(val);coopTime=0;note(PEOPLE[val].name+'正在走向机关，站稳后就能配合操作。');}
  if(a==='bridgeSelect')selectedBridge=+val;if(a==='bridgeRotate')bridgeRot=1-bridgeRot;if(a==='bridgePlace'){while(w.puzzles.bridge.length<=selectedBridge)w.puzzles.bridge.push(0);w.puzzles.bridge[selectedBridge]=bridgeRot;model.bridge[selectedBridge].visible=true;model.bridge[selectedBridge].rotation.y=bridgeRot*Math.PI/2;}
  if(a==='bridgeTest'){if(w.flags.bridge){note('溪桥已经修好。');return;}if(!bridgeReady(w)||cooperator!=='joey'||coopTime<2){note('检查横梁 / 桥板方向，并等乔伊站到绞盘旁。');return;}if(!spend(s,{wood:2,resin:1})){note('需要木材 ×2、树脂 ×1，附近落枝和树脂可以采集。');return;}hold={kind:'bridge',time:0,duration:3};note('正在承重测试，桥梁会逐渐落稳。');}
  if(a==='waterTest'){if(!waterReady(w)||cooperator!=='joey'||coopTime<2){note('先修溪桥，再把两条支渠分别调成 3、2，并请乔伊固定闸门。');return;}hold={kind:'water',time:0,duration:4};}
  if(a==='flower'){if(!waterReady(w)||w.puzzles.mirrors[0]!==2||w.puzzles.mirrors[1]!==5){note('先恢复供水，并按温室笔记调整两个镜面。');return;}w.puzzles.flowers[+val]=true;}
  if(a==='flowerTest'){if(!outfitOK(s,'trail')){note('先穿好徒步服装与防滑短靴。');return;}if(!flowerReady(w)||cooperator!=='mira'||coopTime<2){note('镜面需要 2、5，三朵花都需要引光，再请米拉引导藤蔓。');return;}hold={kind:'greenhouse',time:0,duration:5};}
  if(a==='tideTest'){const build=s.craft.builds.sand;if(!build.some(p=>p.id==='wall')||!build.some(p=>p.id==='gate')||!w.puzzles.tide.every((n,i)=>n===[1,2,1][i])||cooperator!=='joey'||coopTime<2){note('需要城墙与拱门沙堡、1/2/1 高度和乔伊的绞盘配合。');return;}hold={kind:'tide',time:0,duration:5};}
  if(a==='soundTest'){if(!ctx?.state.base||!w.puzzles.sound.every((n,i)=>n===[1,3,2][i])||cooperator!=='neri'||coopTime<2){note('恢复基地后，把声阶调成 1、3、2，并请澜汐协助。');return;}hold={kind:'ocean',time:0,duration:5};}
  if(a==='care'){if(!selected?.pet||care)return;const p=w.pets[selected.pet];if(p.job){note('先结束课堂或工作，再照料它。');return;}if(val==='feed'&&!spend(s,{berry:1})){note('需要一份草莓，可以在农场种植。');return;}care={id:selected.pet,type:val,time:0};note('正在照料'+p.name+'。');}
  if(a==='follow'){const p=w.pets[val];if(p.job||p.food<35||p.energy<30){note('先让伙伴吃饱、休息，并结束工作。');return;}w.following=w.following===val?null:val;note(w.following?p.name+'跟上来了。':'伙伴留在这里休息。');}
  if(a==='job'){if(!selected?.pet)return;const p=w.pets[selected.pet];if(val==='stop'){p.job=null;p.jobTime=0;}else if(Math.min(p.food,p.clean,p.energy)<45){note('需要饱腹、清洁、体力都达到 45。');return;}else{p.job=val;p.jobTime=0;if(w.following===selected.pet)w.following=null;note(p.name+'开始'+(val==='class'?'上课':'帮忙')+'，你可以继续探索。');}}
  if(a==='course'){if(!selected?.pet)return;const p=w.pets[selected.pet];if(p.job||p.food<35||p.energy<30){note('伙伴需要先吃东西、休息或结束工作。');return;}const pet=model.pets.find(a=>a.id===selected.pet);petCourse={id:selected.pet,pet,at:0,points:[pet.home.clone().add(v(3,0,3)),pet.home.clone().add(v(-3,0,5)),pet.home.clone().add(v(0,0,0))]};note('观察地上的三枚气味星标，走近它们，伙伴会跟你一起辨认。');close();for(const pos of petCourse.points){const star=ctx.K.star(ctx.root,pos.x,pos.y+.35,pos.z,.23,ctx.K.glow);star.layers.set(3);model.starTrail.push(star);} }
  if(a==='music'){w.sound=!w.sound;if(w.sound)startMusic();else stopMusic();}
  if(a==='weather'){w.weather=val;applyWeather();}
  if(a==='festival'){if(!w.flags.ocean)return;if(val==='food'&&w.festival.food<4){if(!takeFood(s,null,null,60)){note('需要一份 60 分以上的新鲜餐点。');return;}w.festival.food++;}if(val==='flowers'&&w.festival.flowers<4&&spend(s,{flower:4}))w.festival.flowers=4;if(val==='cloth'&&w.festival.cloth<4&&spend(s,{cloth:4}))w.festival.cloth=4;note('筹备物资已送到主岛，展台会逐步丰富。');}
  if(a==='celebrate'){if(w.invited.length<3||Math.min(w.festival.food,w.festival.flowers,w.festival.cloth)<4){note('还需要邀请三位地区伙伴，并完成餐点、花艺与布料筹备。');return;}w.festival.complete=true;close();travel()?.close();bridge.celebration?.();bridge.go?.('festival');bridge.toast?.('星光嘉年华开幕！伙伴、花艺和你的作品一起登场。');}
  if(a==='fly'){launchFlight();return;}if(a==='flightGuide'&&flight){flight.auto='sky';note('飞机正在沿航线爬升，飞向云上城堡。方向键可随时接管。');return;}if(a==='flightHome'&&flight){flight.auto='marina';flight.landed=false;ctx.avatar.visible=false;note('已设定返航珍珠母港。');return;}if(a==='land'){landFlight();return;}
  persist();render();
 }
 function setHelper(id){cooperator=id;coopTime=0;if(!ctx||!model)return;if(model.helper)model.helper.removeFromParent();const anchor=selected?.g.position||ctx.avatar.position;model.helper=ctx.map.A.doll(ctx.root,anchor.x+5,anchor.y,anchor.z+3,{style:PEOPLE[id].style,color:PEOPLE[id].color,scale:.95,name:PEOPLE[id].name+' · 同行伙伴'});model.helper.userData.live=true;ctx.K.optimize(model.helper);ctx.setLayers();}
 function interact(p,c){if(p.kind!=='world')return false;ctx=c;if(!c.onFoot){note('先停靠并下车或登岛，再靠近这个地点。');return true;}if(c.avatar.position.distanceTo(p.g.position)>5){note('点地点标签走过去，靠近后就能互动。');return true;}
  if(p.type==='event'){p.g.visible=false;give(s,'wood',1);give(s,'cloth',1);note('收好了散落的野餐用品：木材 ×1、布料 ×1。篮底还有一张花会邀请函。');persist();return true;}if(p.type==='npc'){talkAt=0;open('npc',p);return true;}if(p.type==='pet'){open('pet',p);return true;}if(p.type==='work'){openLife(p.activity,c.mode);return true;}
  if(p.type==='gather'){if(gather(s,p.id,p.material,p.rare)){p.g.visible=false;note('获得 '+MATERIALS[p.material]+' ×'+(p.rare?1:2)+'，已放进共同背包。');persist();}else note(p.rare?'这份珍藏已经收好。':'这里还在生长，可以去别处探索后再来。');return true;}
  if(['bridge','water','flowers','tide','sound'].includes(p.type)){if(p.type==='flowers'&&!outfitOK(s,'trail')){note('湿滑山路需要徒步装或水手装，并穿防滑短靴 / 深色靴。');open('patterns');return true;}open('puzzle',p);return true;}
  if(p.type==='sand'){openLife('sand',c.mode);return true;}
  if(p.type==='cave'){const b=s.craft.builds.sand;if(!w.flags.water||!b.some(a=>a.id==='gate')||!b.some(a=>a.id==='wall')){note('先恢复水流，在镜湖沙滩搭建有城墙与拱门的沙堡，水流会清出入口。');return true;}depth=-12;w.flags.cave=true;c.map.land.visible=false;model.cave.visible=true;c.avatar.position.set(120,-11.8,1);note('进入根系洞窟。发光苔藓与星标指向出口。');persist();return true;}
  if(p.type==='caveExit'){depth=0;c.map.land.visible=true;c.avatar.position.set(127,.3,-3);note('回到山谷，洞窟探索记录已经保存。');return true;}
  if(p.type==='chest'){if(w.chests.includes(p.chest))return true;if(p.requirement==='pet'&&(!w.following||w.pets[w.following].trained<1)){note('宝箱留下气味的线索。带一位学过寻物的动物伙伴来。');return true;}if(p.requirement&&!['pet','flight'].includes(p.requirement)&&!w.flags[p.requirement]){note('附近的机关还没有解开。观察水流、光线或伙伴留下的提示。');return true;}if(p.illusion&&!w.flags.mirageSeen){w.flags.mirageSeen=true;p.g.visible=false;setTimeout(()=>{if(p.g.parent)p.g.visible=true;},2500);note('光影消失了，动物伙伴盯着地上的倒影。再次沿倒影走近，才能找到实物。');return true;}w.chests.push(p.chest);give(s,'cloth',2);give(s,'lace',1);give(s,'star',1);p.g.visible=false;note('打开童话宝箱：棉布 ×2、蕾丝 ×1、星光碎片 ×1。');persist();return true;}
  if(p.type==='letter'){w.flags.letter=true;note('找到贝壳信！带回给澜汐，继续她的故事。');p.g.visible=false;persist();return true;}
  if(p.type==='plane'){if(!w.flags.plane){note('先帮助乔伊完成「一架总想开花的飞机」：修复航路后，带来布料和莓果饮品。');return true;}selected=p;open('plane',p);body.innerHTML='<p>亲自驾驶水上飞机前往天空城堡。方向键控制航向和速度，Q/E 升降；触屏使用方向盘和升降按钮。到金色停机圈上方缓慢降落。</p>'+btn('登机起飞','fly','','class="primary"');return true;}
  if(p.type==='skyport'){if(!flight){note('乘水上飞机抵达这里，就能登上城堡花园。');}return true;}return true;
 }
 function build(K,root,map,mode,travelState){depth=0;model=enrichAdventure(K,root,map,mode,w);model.cave&&(model.cave.visible=false);cooperator=null;coopTime=0;flight=null;lastWalk=null;return model;}
 function entered(c){ctx=c;applyWeather();if(w.sound)startMusic();}
 function leaveMap(){document.querySelector('#adventure-flight')?.remove();close();ctx=null;model=null;care=petCourse=hold=flight=null;cooperator=null;depth=0;stopMusic();}
 function applyWeather(){if(!ctx){bridge.weather?.(w.weather);return;}const palette=ctx.mode==='submarine'?['#7598bd','#777da7','#344e78']:w.weather==='night'?['#273652','#7082a3','#354159']:w.weather==='dusk'?['#d4afc4','#f0c5af','#a990b2']:['#c5ddee','#fff1d5','#adc6ce'];scene.background=new T.Color(palette[0]);scene.fog=new T.FogExp2(palette[0],ctx.mode==='submarine'?.006:.0018);ctx.map.light.color.set(palette[1]);ctx.map.light.intensity=w.weather==='night'?1.2:2.7;}
 let audio=null,musicTimer=null,musicStep=0;
 function startMusic(){stopMusic();if(!w.sound||typeof window==='undefined')return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio??=new AC();audio.resume().catch(()=>{});const patterns={bus:[60,64,67,72,71,67,64,62],yacht:[62,69,74,76,74,69,66,62],submarine:[57,64,69,71,69,64,60,57],home:[60,67,72,76,74,72,67,64]},melody=patterns[ctx?.mode||'home'];musicTimer=setInterval(()=>{if(document.hidden||!w.sound)return;const osc=audio.createOscillator(),gain=audio.createGain(),t=audio.currentTime;osc.type=ctx?.mode==='submarine'?'sine':'triangle';osc.frequency.value=440*2**((melody[musicStep++%melody.length]-69)/12);gain.gain.setValueAtTime(0,t);gain.gain.linearRampToValueAtTime(.027,t+.06);gain.gain.exponentialRampToValueAtTime(.001,t+.9);osc.connect(gain);gain.connect(audio.destination);osc.start(t);osc.stop(t+1);osc.onended=()=>{osc.disconnect();gain.disconnect();};},ctx?.mode==='submarine'?850:610);}
 function stopMusic(){clearInterval(musicTimer);musicTimer=null;}
 function launchFlight(){if(!ctx||!model.planeModel||!w.flags.plane)return;close();returnPoint=ctx.avatar.position.clone();const p=model.planeModel;p.updateMatrixWorld(true);const pos=p.getWorldPosition(v());ctx.root.attach(p);p.position.copy(pos);flight={g:p,speed:0,yaw:Math.PI,landed:false};ctx.avatar.visible=false;ctx.rig.vehicle.visible=false;note('飞机就绪。按前进加速，Q 上升、E 下降，飞向中央云上城堡的金色圆环。');}
 function landFlight(){if(!flight||!ctx)return;const p=flight.g.position,home=model.plane.g.position;if(Math.hypot(p.x-home.x,p.z-home.z)<8&&p.y<9&&Math.abs(flight.speed)<7){model.plane.g.attach(flight.g);flight.g.position.set(0,0,0);flight.g.rotation.set(0,0,0);ctx.avatar.position.copy(returnPoint);ctx.avatar.visible=true;ctx.rig.vehicle.visible=true;flight=null;document.querySelector('#adventure-flight')?.remove();note('已返回珍珠母港。');return;}if(Math.hypot(p.x,p.z+8)<7&&p.y>70&&p.y<78&&Math.abs(flight.speed)<7){flight.landed=true;flight.speed=0;flight.g.position.set(0,72,-8);ctx.avatar.position.set(4,71,-8);ctx.avatar.visible=true;w.flags.flight=true;note('已停在云上花园。可以步行打开宝箱，再回到飞机旁返航。');persist();}else note('飞到中央城堡金色停机圈上方，降到 71–77 米并减速到 7 以下再降落。');}
 function update(dt,c){ctx=c;coopTime+=dt;if(model?.helper){const anchor=selected?.g.position||c.avatar.position;const target=anchor.clone().add(v(2,0,1));model.helper.position.lerp(target,Math.min(1,dt*1.6));model.helper.rotation.y=Math.atan2(anchor.x-model.helper.position.x,anchor.z-model.helper.position.z);model.helper.position.y=anchor.y+Math.abs(Math.sin(c.clock*7))*.025;}
  if(hold){hold.time+=dt;if(hold.kind==='water')model.water.scale.z=Math.min(1,hold.time/hold.duration);if(hold.kind==='bridge')model.bridge.forEach((p,i)=>p.position.y=.52+Math.sin(hold.time*6+i)*.025*(1-hold.time/hold.duration));if(hold.time>=hold.duration){w.flags[hold.kind]=true;if(hold.kind==='greenhouse'){give(s,'flower',6);give(s,'cloth',2);}if(hold.kind==='ocean'){grantPattern(w,'oceanweave');give(s,'pearl',3);}note(({bridge:'溪桥修好了，可以调节水车。',water:'水流分配稳定，温室开始得到供水。',greenhouse:'温室盛开了！回工坊邀请米拉，外海航路就能开放。',tide:'浮台稳定，潮汐宝箱的通路已经开放。',ocean:'海底花园苏醒，澜汐终于听见了完整的乐章。'})[hold.kind]);hold=null;persist();render();}}
  if(model?.wheel&&w.flags.water)model.wheel.rotation.z+=dt*.4;model?.valves.forEach((p,i)=>p.rotation.z=w.puzzles.valves[i]*Math.PI/3);model?.mirrors.forEach((p,i)=>p.rotation.y=w.puzzles.mirrors[i]*Math.PI/4);model?.blooms.forEach((p,i)=>{const bloom=c.mode==='bus'?w.flags.greenhouse:w.flags.ocean;p.scale.setScalar(bloom?1:.24+(w.puzzles.flowers[i] ? .20 : 0));});model?.tide.forEach((p,i)=>p.position.y=w.puzzles.tide[i]*.65+(w.flags.tide?0:Math.sin(c.clock+i)*.18));
  for(const p of model?.collectibles||[]){const last=w.gathered[p.id];p.g.visible=last===undefined||(!p.rare&&w.time-last>=240);if(p.material==='star')p.g.rotation.y+=dt*.7;}
  if(care){care.time+=dt;const p=model.pets.find(p=>p.id===care.id);if(p){p.g.rotation.z=Math.sin(care.time*5)*.10;p.g.position.y=care.type==='play'?Math.abs(Math.sin(care.time*6))*.3:0;}if(care.time>=3){const a=w.pets[care.id];if(care.type==='feed')a.food=Math.min(100,a.food+35);else if(care.type==='groom')a.clean=100;else a.joy=Math.min(100,a.joy+25);a.bond=Math.min(100,a.bond+4);a.energy=Math.min(100,a.energy+5);if(p){p.g.rotation.z=0;p.g.position.y=0;}care=null;persist();render();}}
  for(const p of model?.pets||[]){const a=w.pets[p.id];if(petCourse?.id===p.id){const target=petCourse.points[petCourse.at];if(c.avatar.position.distanceTo(target)<4){p.p.g.position.lerp(target,Math.min(1,dt*2));if(p.p.g.position.distanceTo(target)<.3){model.starTrail[petCourse.at].visible=false;petCourse.at++;if(petCourse.at===3){a.trained=Math.min(3,a.trained+1);a.bond=Math.min(100,a.bond+10);a.energy=Math.max(0,a.energy-10);w.following=p.id;petCourse=null;note(a.name+'学会寻找线索了！带它去有气味的隐藏宝箱。');persist();}}}}else if(w.following===p.id&&c.onFoot&&!opened&&!flight){const target=c.avatar.position.clone().add(v(-1.7,0,-1.2)),delta=target.clone().sub(p.p.g.position);if(delta.length()>1.5){p.p.g.position.addScaledVector(delta.normalize(),dt*4.5);p.p.g.rotation.y=Math.atan2(delta.x,delta.z);}p.g.position.y=Math.abs(Math.sin(c.clock*10))*.05;}else if(a.job){p.g.rotation.y=Math.sin(c.clock)*.5;p.g.position.y=Math.abs(Math.sin(c.clock*4))*.05;}}
  if(c.mode==='yacht'&&c.state.flowers===3&&c.state.lens.every((n,i)=>n===[2,5,7][i])&&!w.flags.islands){w.flags.islands=true;grantPattern(w,'divesuit');give(s,'pearl',2);give(s,'cloth',3);note('灯塔与庆典都准备好了！获得潜航服图纸与材料。穿好后可进入海沟。');persist();}
  if(flight){const f=flight;if(!f.landed){let target=c.keys.has('up')?20:c.keys.has('down')?-4:0;if(c.keys.size)f.auto=null;if(f.auto){const dest=f.auto==='sky'?v(0,74,-8):model.plane.g.position.clone().setY(4),delta=dest.clone().sub(f.g.position),horizontal=Math.hypot(delta.x,delta.z);f.yaw=Math.atan2(delta.x,delta.z);target=Math.min(22,horizontal*1.5);const targetY=f.auto==='marina'&&horizontal>25?74:dest.y;f.g.position.y+=Math.max(-dt*10,Math.min(dt*10,targetY-f.g.position.y));if(horizontal<.8&&Math.abs(delta.y)<.6){f.auto=null;target=0;f.speed=0;note('飞机已悬停在停机圈上方，可以降落。');}}f.speed+=(target-f.speed)*Math.min(1,dt*1.4);f.yaw+=((c.keys.has('left')?1:0)-(c.keys.has('right')?1:0))*dt;f.g.rotation.y=f.yaw;f.g.position.add(v(Math.sin(f.yaw)*f.speed*dt,0,Math.cos(f.yaw)*f.speed*dt));f.g.position.y=Math.max(3,Math.min(100,f.g.position.y+((c.keys.has('rise')?1:0)-(c.keys.has('sink')?1:0))*dt*10));f.g.position.x=Math.max(-185,Math.min(185,f.g.position.x));f.g.position.z=Math.max(-185,Math.min(185,f.g.position.z));model.planeProp.rotation.z+=dt*30;}let el=document.querySelector('#adventure-flight');if(!el){el=document.createElement('div');el.id='adventure-flight';hud.append(el);}if(!el.last||c.clock-el.last>.4){el.last=c.clock;el.innerHTML=`<span>飞行高度 ${Math.round(f.g.position.y)} m · 速度 ${Math.round(f.speed)}</span>${btn('上升 Q','flightRise')}${btn('下降 E','flightSink')}${btn('引导至城堡','flightGuide')}${btn('返航母港','flightHome')}${btn(f.landed?'登机返航':'降落','flightLand')}`;}if(f.landed&&c.keys.has('rise')){f.landed=false;c.avatar.visible=false;}}
  if(c.onFoot&&!opened&&!flight){if(lastWalk)walked+=c.avatar.position.distanceTo(lastWalk);lastWalk=c.avatar.position.clone();if(walked>140&&w.time>w.eventAt){walked=0;w.eventAt=w.time+180;if(model.event){model.event.g.position.copy(c.avatar.position).add(v(3,0,2));model.event.g.visible=true;}note('风吹散了路旁的野餐篮。可以走过去整理，再把找到的物资带给居民。');persist();}}
 }
 function globalUpdate(dt){if(document.hidden)return;dt=Math.min(dt,.1);if(!opened){tickWorld(s,dt);if(!life.busy())grow(s,dt);}dtSave+=dt;uiClock+=dt;if(dtSave>4){persist();dtSave=0;}if(uiClock>1){uiClock=0;document.querySelector('#adventure-goal').textContent=primary();hud.hidden=life.busy();if(opened&&page==='pets')render();}}
 function input(a,index,value){if(!selected)return;const n=Math.round(Math.max(0,Math.min(7,+value)));if(a==='valve')w.puzzles.valves[index]=Math.min(5,n);if(a==='mirror')w.puzzles.mirrors[index]=n;if(a==='tide')w.puzzles.tide[index]=Math.min(3,n);if(a==='sound'){w.puzzles.sound[index]=Math.min(4,n);bridge.note?.(220*2**(n/12),.2);}hold=null;persist();}
 function handle(e){const b=e.target.closest('[data-world]');if(!b||b.disabled)return;const a=b.dataset.world,val=b.dataset.value;if(a==='flightLand'){if(flight?.landed){flight.landed=false;ctx.avatar.visible=false;note('重新登机。飞回珍珠母港，或收起旅行地图返回主岛。');}else landFlight();return;}if(a==='flightRise'||a==='flightSink'){if(flight){flight.g.position.y+=a==='flightRise'?4:-4;flight.g.position.y=Math.max(3,Math.min(100,flight.g.position.y));}return;}action(a,val);}
 ui.addEventListener('click',handle);hud.addEventListener('click',handle);ui.addEventListener('input',e=>{if(e.target.dataset.worldRange)input(e.target.dataset.worldRange,+e.target.dataset.index,e.target.value);});addEventListener('keydown',e=>{if(e.code==='Escape'&&opened){close();e.preventDefault();}});
 return {open,close,action,globalUpdate,build,entered,leaveMap,interact,update,input,allowed:mode=>worldUnlocked(w,mode)&&(mode!=='submarine'||outfitOK(s,'dive')),lockReason:mode=>mode==='submarine'&&w.flags.islands&&!outfitOK(s,'dive')?'先制作并穿上珍珠潜航服，再前往海沟。':worldLock(w,mode),inform:note,busy:()=>opened||!!care,flightActive:()=>!!flight,cameraHeading:()=>flight?.yaw,driving:()=>!!flight&&!flight.landed,floorY:()=>flight?.landed?71:depth? -11.8:null,cameraActor:()=>flight&&!flight.landed?flight.g:selected&&opened?selected.g:null,walkable:(p,c)=>flight?.landed?Math.hypot(p.x,p.z+18)<17:depth?Math.abs(p.x-120)<12&&Math.abs(p.z+7)<10:!c.map.solid.some(a=>Math.hypot(p.x-a.x,p.z-a.z)<a.r+.45),appearance:()=>({style:item(s.look.dress).value,color:PALETTE.find(p=>p[0]===s.look.color)[2],hairStyle:item(s.look.hair).value}),get state(){return w;},get debug(){return {ctx,model,selected,hold,cooperator,flight,depth,open,interact};}};
}
