import {createGame} from './game.js';
import {createCraftDisplay} from './craft-display.js';
import {T,C,v} from './kit.js';
import {OrbitControls} from './vendor/OrbitControls.js';
import {buildWorld,LOCATIONS} from './world.js';
import {waterMaterial,installSeaOptics,animateGlassCoast} from './glass-sea.js';
import {animatePalms} from './landscape.js';
import {installForestLight,animateForest} from './fantasy-forest.js';
import {LIGHTING,createAtmosphere,setAtmosphere} from './lighting.js';
import {installWeather,animateExpansion,expansionRide} from './expansion-motion.js';
import {updateWorldInteractions,toggleWorldInteraction,submergedWorld,visibleInScene,applyRealmVisibility} from './world-interactions.js';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
let game=null;
let winter=false,weather,ballet=true,lighting='day',atmosphere;
let renderer,scene,camera,controls,W,ocean,sun,hemi,fill,skyLight,night=false,party=false,fly=false,tour=false,ride=null,flightKeys=new Set(),world='home',current=LOCATIONS[0],layer='full',transition=null,t=0,ambient=null,audioEnabled=false,toastTimer,refs=[];
const state={dressTarget:'home',dressColor:C.pink,dressStyle:'ruffle',nailColor:C.pink,nailFinish:'gloss',shellOpen:true,liftUp:false,swing:false};
const actionNames={worldFestival:'查看嘉年华筹备',farm:'播种、浇水与收获',animals:'照料动物与抛球',teaCafe:'经营花园茶会',cupcake:'制作纸杯蛋糕与裱花',sandcastle:'亲手堆沙堡',blocks:'自由拼积木',tour:'开始漫游',lift:'乘观光电梯',slide:'从滑梯入水',dress:'搭配服装',nails:'亲手涂画美甲',cake:'亲手烘焙蛋糕',piano:'弹奏钢琴',drink:'亲手调饮与摇杯',party:'和朋友跳派对舞',swing:'荡起秋千',night:'点亮晚宴',picnic:'布置下午茶',dive:'潜入海底',mermaid:'跟随美人鱼',pearl:'打开／合上贝壳',balloon:'乘热气球',drive:'跑车兜风',references:'逐图对照',snow:'切换雪季',ballet:'上台挑战节拍',portal:'穿过神秘之门',bus:'大巴环山旅行',yacht:'乘游艇出航',submarine:'乘潜艇巡游',pegasus:'跟随白色飞马',sleigh:'跟随麋鹿雪橇',carousel:'坐上旋转木马',deepLift:'乘海底电梯',dusk:'欣赏海岛黄昏',deepEnter:'进入海底衣帽宫',deepUpper:'登上二层衣廊',deepDress:'进入搭配工作室',carriageDoor:'打开马车门',royalDoor:'打开舞会马车门',treeHalo:'暂停星光环',wings:'舒展飞马翅膀',townDoors:'打开小镇店门',linerCruise:'乘邮轮看船队',linerHorn:'鸣响邮轮汽笛',linerLights:'关闭邮轮灯光',linerDeck:'走进邮轮舞厅'};
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function fail(e){console.error(e);$('#loading').classList.add('error');$('#loading').classList.remove('done');$('#loading strong').textContent='画面暂时没有打开';$('#load-status').textContent=e?.message||'请重试';$('.load-track').style.display='none';if(!$('.retry')){let b=document.createElement('button');b.className='retry';b.textContent='重新打开';b.onclick=()=>location.reload();$('#loading').append(b);}}
const environmentMaps=new Map();
function environment(preset=LIGHTING.day){if(environmentMaps.has(preset))return environmentMaps.get(preset);const width=512,height=256,data=new Uint8Array(width*height*4);let top=new T.Color(preset.sky),bottom=new T.Color(preset.horizon);for(let y=0;y<height;y++)for(let x=0;x<width;x++){let c=top.clone().lerp(bottom,Math.min(1,y/(height*.62)));let lobe=Math.exp(-(((x-170)/19)**2)-((y-81)/18)**2)*1.0;c.lerp(new T.Color('white'),Math.min(1,lobe));let i=(y*width+x)*4;data[i]=c.r*255;data[i+1]=c.g*255;data[i+2]=c.b*255;data[i+3]=255;}let texture=new T.DataTexture(data,width,height,T.RGBAFormat);texture.needsUpdate=true;texture.mapping=T.EquirectangularReflectionMapping;texture.colorSpace=T.LinearSRGBColorSpace;environmentMaps.set(preset,texture);return texture;}
function setupSparkles(){for(const m of W.K.mats.values()){if(!m.userData.sparkle||m.userData.sparkleApplied)continue;m.userData.sparkleApplied=true;m.customProgramCacheKey=()=>m.userData.prism?'prism-sparkle-v6':'sparkle-v6';m.onBeforeCompile=s=>{s.uniforms.sparkleTime={value:0};m.userData.shader=s;s.vertexShader='varying vec3 sparklePosition;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nsparklePosition=position;');s.fragmentShader='varying vec3 sparklePosition;uniform float sparkleTime;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <opaque_fragment>',`vec3 cell=floor(sparklePosition*95.);float hash=fract(sin(dot(cell,vec3(12.9898,78.233,37.719)))*43758.5453);float blink=pow(max(0.,sin(sparkleTime*1.4+hash*20.)),18.);outgoingLight+=vec3(1.,.92,.8)*step(.982,hash)*blink*.85;${m.userData.prism?'vec3 prismLight=.5+.5*cos(vec3(0.,2.1,4.2)+sparklePosition.y*3.6+sparklePosition.x*1.9+sparkleTime*.55);outgoingLight=mix(outgoingLight,outgoingLight*(.72+prismLight*.65)+prismLight*.065,.42);':''}\n#include <opaque_fragment>`);};m.needsUpdate=true;}}
function makeText(text,x,y,z,width,parent=W.root){let c=document.createElement('canvas');c.width=1024;c.height=256;let ctx=c.getContext('2d');ctx.clearRect(0,0,1024,256);ctx.font='italic bold 140px Georgia';ctx.fillStyle='#ffedf7';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,512,128,990);let tx=new T.CanvasTexture(c);tx.colorSpace=T.SRGBColorSpace;let m=new T.MeshBasicMaterial({map:tx,transparent:true,depthWrite:false,side:T.DoubleSide});let q=new T.Mesh(new T.PlaneGeometry(width,width/4),m);q.position.set(x,y,z);parent.add(q);return q;}
function setLayer(value){layer=value;let m=W.mansion,p=W.palace;for(let r of [m.roofs,p.roofs])r.visible=value==='full';for(let r of [m.upper,p.upper])r.visible=value!=='ground';for(let r of [m.ground,p.ground])r.visible=value!=='upper';m.shell.visible=p.shell.visible=value==='full'||value==='open';p.live.visible=true;p.live.children.forEach(o=>{if(o.userData.level===undefined)o.userData.level=o.position.y>=8?'upper':'ground';o.visible=value==='ground'?o.userData.level!=='upper':value==='upper'?o.userData.level==='upper':true;});$$('[data-layer]').forEach(b=>{b.classList.toggle('selected',b.dataset.layer===value);b.setAttribute('aria-pressed',String(b.dataset.layer===value));});}
function setWorld(value){world=value;const sub=applyRealmVisibility(W,value,winter);ocean.visible=!sub;
 const preset=LIGHTING[lighting];scene.background.set(value==='wardrobe'?'#809bc1':sub?'#91b9e8':preset.horizon);scene.fog.color.copy(scene.background);if(atmosphere){atmosphere.visible=!sub;setAtmosphere(atmosphere,preset,winter);}scene.fog.density=value==='wardrobe'?.0015:sub?(current.id==='deepaccess'?.0035:.014):winter?.003:.0018;
 sun.intensity=sub?1.1:preset.sunPower;hemi.intensity=sub?2.1:preset.ambient;skyLight.visible=sub;fill.intensity=sub?1.25:preset.fill;sun.color.set(preset.sun);fill.color.set(preset.hemi);scene.environment=environment(preset);scene.environmentIntensity=lighting==='night'?.28:lighting==='dusk'?.48:.65;sun.position.set(...preset.position);const lightOrigin=value==='sky'?v(...(['forest','treehouse','crown','stream'].includes(current.id)?[-154,42,-94]:[-85,42,-80])):v(0,0,0);sun.position.add(lightOrigin);sun.target.position.copy(lightOrigin).add(v(0,0,-10));sun.target.updateMatrixWorld();hemi.color.set(preset.hemi);hemi.groundColor.set(preset.ground);renderer.toneMappingExposure=preset.exposure;for(let l of wardrobeLights)l.visible=value==='wardrobe';
 if(!sub){setLayer(layer);if(value==='sky'||value==='beach'){W.mansion.ground.visible=W.mansion.upper.visible=W.palace.ground.visible=W.palace.upper.visible=W.palace.live.visible=false;}}
 $$('[data-world]').forEach(b=>{b.classList.toggle('active',b.dataset.world===value);b.setAttribute('aria-pressed',String(b.dataset.world===value));});$('.view-controls').style.display=sub||value==='sky'?'none':'';renderPlaces();}
const switchKeys={carriageDoor:'carriageOpen',royalDoor:'royalOpen',treeHalo:'treeSpin',wings:'wings',townDoors:'townOpen',linerLights:'linerLit'};
const switchLabels={carriageDoor:['打开马车门','合上马车门'],royalDoor:['打开舞会马车门','合上舞会马车门'],treeHalo:['旋转星光环','暂停星光环'],wings:['让飞马振翅','舒展飞马翅膀'],townDoors:['打开小镇店门','合上小镇店门'],linerLights:['点亮邮轮','关闭邮轮灯光']};
function renderActions(){ $('#place-actions').replaceChildren(...current.actions.map((a,i)=>{let b=document.createElement('button');b.className='pill-action'+(i?' alt':'');b.dataset.action=a;let key=switchKeys[a],on=key&&W.interactions.state[key];b.textContent=key?switchLabels[a][on?1:0]:actionNames[a];if(key)b.setAttribute('aria-pressed',String(on));b.onclick=()=>act(a);return b;}));}

function renderPlaces(){const items=LOCATIONS.filter(a=>a.world===world);$('#places').replaceChildren(...items.map(l=>{let b=document.createElement('button');b.className='place'+(l.id===current.id?' active':'');b.innerHTML=`<span class="symbol">${l.symbol}</span><span class="text"><strong>${l.name}</strong><small>${l.en}</small></span>`;b.onclick=()=>go(l.id);b.setAttribute('aria-label','前往'+l.name);return b;}));}
function go(id,{immediate=false,keepTour=false}={}){game?.cancel();const l=LOCATIONS.find(a=>a.id===id);if(!l)return;if(!keepTour)stopTour();stopRide(false);if(l.id==='sleigh'&&!winter)toggleSnow(true);if(fly)toggleFly(false);current=l;setWorld(l.world);if(l.world==='home')setLayer(l.layer);let end=v(...l.pos);if(innerWidth<720&&l.world!=='wardrobe'){let target=v(...l.target);end=target.clone().add(end.sub(target).multiplyScalar(1.22));}transition={from:camera.position.clone(),to:end,fromTarget:controls.target.clone(),toTarget:v(...l.target),elapsed:0,duration:immediate||reduced?0:1.6};$('#place-category').textContent=l.en;$('#place-name').textContent=l.name;$('#place-description').textContent=l.description;renderActions();if(innerWidth<720){$('.destinations').classList.add('folded');$('#fold-menu').textContent='+';}renderPlaces();game?.onLocation(l);}
function setLighting(value){lighting=value;night=value==='night';const preset=LIGHTING[value];$('#day-button').innerHTML=preset.symbol+' <span>'+preset.label+'</span>';$('#day-button').setAttribute('aria-label','当前'+preset.label+'，点击选择晴日、黄昏或星夜');$$('[data-time]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.time===value));b.classList.toggle('selected',b.dataset.time===value);});setWorld(world);
 for(let p of poolLights)p.intensity=night?14:value==='dusk'?6:0;for(let m of W.K.mats.values())if(m.emissive?.getHex()>0)m.emissiveIntensity=night?1.8:value==='dusk'?1.15:.7;
 for(let water of [ocean,...W.mansion.movers.poolWater]){let u=water.material.uniforms;u.night.value=night?1:0;u.waterColor.value.set(u.isPool.value>.5?preset.pool:preset.water);u.skyColor.value.set(preset.reflection);u.sunColor.value.set(preset.sun);u.sunDirection.value.set(...preset.position).normalize();}
 const u=W.glassCoast.bed.material.uniforms;u.night.value=night?1:0;u.warmth.value=value==='dusk'?1:0;}
function toggleNight(value=!night){setLighting(value?'night':'day');}
function toggleSnow(value=!winter){winter=value;$('#snow-button').setAttribute('aria-pressed',String(winter));$('#snow-button').innerHTML='❄ <span>'+(winter?'雪季':'雪景')+'</span>';setWorld(world);toast(winter?'雪季开启，圣诞树、暖窗与麋鹿雪橇等你来探索':'回到晴朗的海岛季节');}
const poolLights=[],wardrobeLights=[];
function stopRide(show=true){if(!ride)return;if(ride.type==='liner')W.liner.fleet.position.copy(W.liner.base);if(ride.type==='yacht'){W.coast.movers.yacht.position.set(45,.25,84);W.coast.movers.yacht.rotation.y=0;}if(ride.type==='submarine'){W.deep.movers.submarine.position.set(45,-24,146);W.deep.movers.submarine.rotation.y=0;}if(ride.type==='mermaid'){const m=W.underwater.movers.mermaids[0];m.g.position.copy(m.base);m.g.rotation.y=0;}ride=null;controls.enabled=true;$('#control-hint').textContent='拖动旋转 · 滚轮靠近 · 右键平移';if(show)toast('已结束体验，可以继续自由探索');}
function startRide(type){stopTour();transition=null;if(type==='lift')setLayer('open');controls.enabled=false;ride={type,start:t,duration:{slide:9,drive:32,mermaid:24,balloon:22,lift:6,bus:32,yacht:36,submarine:32,pegasus:25,sleigh:25,carousel:22,deepLift:10,liner:45}[type]||12};if(type==='deepLift'){ride.fromY=W.deep.movers.lift.position.y;ride.toY=ride.fromY<-36?-30:-43.7;}if(type==='drive'){let best=Infinity;ride.offset=0;for(let i=0;i<200;i++){const distance=W.island.movers.roadCurve.getPoint(i/200).distanceToSquared(W.island.movers.car.position);if(distance<best){best=distance;ride.offset=i/200;}}}$('#control-hint').textContent='体验中 · 点击画面或按Esc结束';toast('体验开始，按 Esc 或点击画面结束');}
function stopTour(){tour=false;$('#tour-button').textContent='▷ 自动漫游';}
let tourIndex=0,tourNext=0;const route=['overview','foyer','wardrobe','gallery','barbie','kelly','salon','kitchen','party','pool','drive','beach','reef','pearl','deepcloset','couture','whale','carousel','christmas','town','liner','yacht','skycity','theater','swanlake','library','astronaut'];
function startTour(){tour=true;tourIndex=0;go(route[0],{keepTour:true});tourNext=t+7;$('#tour-button').textContent='Ⅱ 暂停漫游';toast('正在带你逛整座梦想世界');}
function toggleFly(force=!fly){fly=force;stopRide(false);stopTour();transition=null;controls.enablePan=!fly;controls.minDistance=fly?.15:1;$('#fly-button').textContent=fly?'✧ 结束飞行':'✧ 自由飞行';$('#touch-flight').hidden=!fly;$('#control-hint').textContent=fly?'WASD移动 · Q/E升降 · Shift加速':'拖动旋转 · 滚轮靠近 · 右键平移';if(fly)controls.target.copy(camera.position).add(camera.getWorldDirection(v(0,0,0)).multiplyScalar(5));}
let actExtra=[];
function clearExtra(key){actExtra=actExtra.filter(a=>{if(a.key!==key)return true;a.g.removeFromParent();return false;});}
function act(a,sceneOnly=false){if(!sceneOnly&&game?.interact(a))return;const origin=current.id;const result=performAction(a);const success=a==='party'?party:a==='pearl'?state.shellOpen:a==='royalDoor'?W.interactions.state.royalOpen:a==='treeHalo'?W.interactions.state.treeSpin:a==='portal';game?.onAction(a,origin,!!success);return result;}
function performAction(a){
 if(a==='dusk'){setLighting('dusk');return toast('黄昏开启，粉金色天光与海面反光一起变化');}
 const toggled=toggleWorldInteraction(W,a);if(toggled!==null){renderActions();const phrases={carriageDoor:toggled?'马车门已打开，可以靠近看座舱':'马车门已合上',royalDoor:toggled?'舞会马车门已打开':'舞会马车门已合上',treeHalo:toggled?'圣诞星光环开始旋转':'星光环停留在这一刻',wings:toggled?'飞马开始振翅':'飞马舒展翅膀，方便看羽毛细节',townDoors:toggled?'小镇八间店铺的门已打开':'小镇店门已合上',linerLights:toggled?'邮轮暖灯已点亮':'邮轮灯光已关闭'};return toast(phrases[a]);}
 if(a==='deepEnter')return go('deepcloset');if(a==='deepUpper')return go('deepUpper');if(a==='linerDeck')return go('linerDeck');if(a==='linerCruise'){go('liner');return startRide('liner');}if(a==='linerHorn')return linerHorn();if(a==='deepDress')return dressDialog(true);
 if(a==='snow')return toggleSnow();if(a==='portal')return go(current.id==='forest'?'skycity':'forest');if(a==='ballet'){ballet=!ballet;return toast(ballet?'公主们开始轻轻起舞':'舞台动作已暂停');}if(['bus','yacht','submarine','pegasus','sleigh','carousel','deepLift'].includes(a)){if(a==='sleigh'&&!winter)toggleSnow(true);if(a==='deepLift')W.deep.movers.lift.position.y=world==='wardrobe'?-43.7:-30;return startRide(a);}if(a==='tour')return startTour();if(['slide','drive','mermaid','balloon','lift'].includes(a)){if(a==='slide'&&world!=='home')go('pool');if(a==='mermaid'&&world!=='underwater')go('reef');if(a==='balloon'&&world!=='sky')go('balloon');return startRide(a);}if(a==='dive')return go('reef');if(a==='night'){toggleNight(true);return toast('花拱露台的星灯亮起来了');}if(a==='dress')return dressDialog();if(a==='nails')return nailDialog();if(a==='references')return referenceDialog();if(a==='party'){party=!party;toggleNight(party);partyLight.visible=party;toast(party?'派对开始！镜面球与彩色灯光已打开':'派对灯光已关闭');return;}if(a==='swing'){if(current.id!=='swing')go('swing');state.swing=!state.swing;toast(state.swing?'花环秋千开始轻轻摇摆':'秋千停下了');return;}if(a==='pearl'){state.shellOpen=!state.shellOpen;toast(state.shellOpen?'珍珠重新闪耀起来':'贝壳合上，替你保管小秘密');return;}if(a==='piano')return pianoDialog();if(a==='cake')return cakeDialog();if(a==='drink')return drinkDialog();if(a==='picnic'){clearExtra('picnic');let g=W.K.group(W.island.land,'新布置的野餐点心',-3,1,50);W.K.cake(g,-.7,.08,0,1);for(let i=0;i<3;i++)W.K.cup(g,.5,.10,-.6+i*.6);W.K.bouquet(g,0,.1,-.8,.8);W.K.optimize(g);actExtra.push({key:'picnic',g});toast('野餐毯上添好了蛋糕、茶与鲜花');}}
function showActivity(eyebrow,title,body){$('#activity-content').innerHTML=`<span class="eyebrow">${eyebrow}</span><h2>${title}</h2>${body}`;$('#activity-dialog').showModal();}
const colors=[['芭比粉',C.pink],['樱花粉',C.blush],['紫水晶',C.violet],['海水蓝',C.aqua],['香槟金',C.gold],['红丝绒','#b71543']];
function swatches(selected,onChange){return colors.map(([name,c])=>{let b=document.createElement('button');b.className='swatch'+(selected===c?' selected':'');b.style.background=c;b.title=name;b.setAttribute('aria-label',name);b.setAttribute('aria-pressed',String(selected===c));b.onclick=()=>{b.parentElement.querySelectorAll('button').forEach(q=>{q.classList.remove('selected');q.setAttribute('aria-pressed','false');});b.classList.add('selected');b.setAttribute('aria-pressed','true');onChange(c);};return b;});}
function updateOutfit(){let home=state.dressTarget==='deep'?W.deep:W.palace,d=home.movers.runway;d.userData.outfit.removeFromParent();let next=home.A.outfit(d,state.dressStyle,state.dressColor);next.userData.live=true;d.userData.outfit=next;W.K.optimize(next);setupSparkles();}
function dressDialog(deep=false){state.dressTarget=deep?'deep':'home';go(deep?'deepcloset':'wardrobe');showActivity('THE DREAM WARDROBE','今天穿哪一套？','<p>'+ (deep?'给海底衣帽宫中央的人偶更换整套服装，搭配珍珠、闪粉与不同裙形。':'给圆塔里的试衣人偶更换整套服装。层叠裙、马甲格裙和红金礼服保留为独立款式。')+'</p><div class="activity-tabs" id="dress-styles"></div><div class="choice-row" id="dress-colors"></div><div class="activity-actions"><button class="primary" id="dress-view">回到场景看搭配</button></div>');$('#dress-colors').replaceChildren(...swatches(state.dressColor,c=>{state.dressColor=c;updateOutfit();}));for(let [id,name]of [['ruffle','粉紫层叠裙'],['uniform','马甲与格裙'],['gown','红金晚礼服'],['pajamas','睡衣派对'],['floral','花园礼服'],['ballet','粉红舞鞋'],['swan','天鹅湖'],['sugar','糖果公主'],['pilot','飞行员'],['astronaut','宇航员']]){let b=document.createElement('button');b.textContent=name;b.className=id===state.dressStyle?'selected':'';b.onclick=()=>{state.dressStyle=id;$('#dress-styles').querySelectorAll('button').forEach(q=>q.classList.toggle('selected',q===b));updateOutfit();};$('#dress-styles').append(b);}$('#dress-view').onclick=()=>{$('#activity-dialog').close();transition={from:camera.position.clone(),to:deep?v(86.6,-40.6,129.5):v(-18.7,4.3,-1.5),fromTarget:controls.target.clone(),toTarget:deep?v(85,-42.3,124.2):v(-22,3.7,-5),elapsed:0,duration:1.1};};}
function updateNails(){const finish=state.nailFinish;for(let n of W.palace.movers.nails){n.material=W.K.mat(state.nailColor,{roughness:finish==='gloss'?.12:.22,metalness:finish==='glitter'?.75:.18});if(finish==='glitter')n.material.userData.sparkle=true;}clearExtra('nailfinish');let g=W.K.group(W.palace.live,'甲片装饰',-28,3.14,3.1);for(let i=0;i<5;i++){if(finish==='pearl')W.K.ell(g,-.64+i*.32,.13,.13,.035,.035,.035,C.cream,12);if(finish==='french')W.K.ell(g,-.64+i*.32,.108,-.18,.11,.025,.07,C.white,16);}actExtra.push({key:'nailfinish',g});setupSparkles();$$('.nail').forEach(n=>{n.style.background=state.nailColor;n.className='nail '+finish;});}
function nailDialog(){go('salon');showActivity('GLOSS & GLITTER','你的专属闪亮美甲','<p>选颜色，再选亮面、闪粉、法式或珍珠。桌上的五片展示甲会同步改变。</p><div class="nail-display">'+Array(5).fill('<i class="nail"></i>').join('')+'</div><div class="choice-row" id="nail-colors"></div><div class="activity-tabs" id="nail-finishes"></div><div class="activity-actions"><button class="primary" id="nail-view">看看我的作品</button></div>');$('#nail-colors').replaceChildren(...swatches(state.nailColor,c=>{state.nailColor=c;updateNails();}));for(let [id,name] of [['gloss','镜面亮泽'],['glitter','璀璨闪粉'],['french','奶油法式'],['pearl','珍珠点缀']]){let b=document.createElement('button');b.textContent=name;b.className=state.nailFinish===id?'selected':'';b.onclick=()=>{state.nailFinish=id;$('#nail-finishes').querySelectorAll('button').forEach(q=>q.classList.toggle('selected',q===b));updateNails();};$('#nail-finishes').append(b);}updateNails();$('#nail-view').onclick=()=>{$('#activity-dialog').close();transition={from:camera.position.clone(),to:v(-27.5,4.4,4.1),fromTarget:controls.target.clone(),toTarget:v(-28,3.25,3.1),elapsed:0,duration:1.2};};}
function getAudio(){if(!ambient){let AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('此浏览器暂不支持声音');ambient=new AC();}if(ambient.state==='suspended')ambient.resume();return ambient;}
function note(freq,duration=.65,delay=0){try{let ctx=getAudio(),osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='triangle';osc.frequency.value=freq;osc.connect(gain);gain.connect(ctx.destination);let at=ctx.currentTime+delay;gain.gain.setValueAtTime(0,at);gain.gain.linearRampToValueAtTime(.07,at+.015);gain.gain.exponentialRampToValueAtTime(.001,at+duration);osc.start(at);osc.stop(at+duration+.1);}catch(e){toast(e.message);}}
function linerHorn(){try{for(let f of [87.31,130.81,174.61])note(f,2.6);toast('梦幻邮轮鸣笛，准备启航');}catch(e){toast(e.message);}}
function pianoDialog(){showActivity('MUSIC SALON','弹一段小小的旋律','<p>点琴键即可发声，也可以听一段为这座豪宅写的小旋律。</p><div class="piano-keys" id="piano-keys"></div><div class="activity-actions"><button class="primary" id="melody">♫ 播放小旋律</button></div>');let notes=[261.63,293.66,329.63,349.23,392,440,493.88,523.25];notes.forEach((n,i)=>{let b=document.createElement('button');b.textContent=['Do','Re','Mi','Fa','Sol','La','Si','Do'][i];b.onpointerdown=()=>note(n);$('#piano-keys').append(b);});$('#melody').onclick=()=>[0,2,4,7,6,4,3,2,1,3,5,7,4,2,1,0].forEach((n,i)=>note(notes[n],.6,i*.3));}
function cakeDialog(){showActivity('SWEET LITTLE THINGS','装饰一只庆祝蛋糕','<p>在厨房岛台上做一只新的三层蛋糕，选择糖霜颜色与顶部装饰。</p><div class="choice-row" id="cake-colors"></div><div class="activity-tabs" id="cake-top"><button data-top="bow" class="selected">蝴蝶结</button><button data-top="star">金色星星</button><button data-top="flowers">花束</button></div><div class="activity-actions"><button class="primary" id="cake-make">把蛋糕放上岛台</button></div>');let color=C.pink,top='bow';$('#cake-colors').replaceChildren(...swatches(color,c=>color=c));$$('[data-top]').forEach(b=>b.onclick=()=>{top=b.dataset.top;$$('[data-top]').forEach(q=>q.classList.toggle('selected',q===b));});$('#cake-make').onclick=()=>{go('kitchen');clearExtra('cake');let g=W.K.group(W.mansion.ground,'定制蛋糕',-8.15,3.325,-21.9);W.K.cake(g,0,0,0,.85);for(let i=0;i<3;i++)W.K.cyl(g,0,.19+i*.19,0,.36-i*.09,.36-i*.09,.15,color,32);if(top==='bow')W.palace.A.bow(g,0,.88,0,.55,W.K.gold);else if(top==='star')W.K.star(g,0,.97,0,.25,W.K.gold);else W.K.bouquet(g,0,.62,0,.4);W.K.optimize(g);actExtra.push({key:'cake',g});$('#activity-dialog').close();toast('蛋糕做好了，已经放上厨房岛台');};}
function drinkDialog(){showActivity('SIP SOMETHING PINK','调一杯海岛气泡饮','<p>选择口味，让饮品出现在吧台上。</p><div class="activity-tabs" id="flavors"></div>');for(let [name,c] of [['蜜桃玫瑰',C.rose],['蓝色海盐',C.aqua],['紫莓气泡',C.violet]]){let b=document.createElement('button');b.textContent=name;b.onclick=()=>{clearExtra('drink');let g=W.K.group(W.mansion.ground,name,...(current.id==='cafe'?[-11.2,3.56,-10.8]:[25,3.67,-12.7]));W.K.cyl(g,0,.25,0,.18,.12,.5,W.K.glass);W.K.cyl(g,0,.21,0,.16,.11,.38,c);W.K.rod(g,[.08,.1,0],[.17,.7,0],.016,C.cream);W.K.ell(g,-.13,.5,0,.14,.14,.025,C.peach);W.K.optimize(g);actExtra.push({key:'drink',g});$('#activity-dialog').close();toast(name+'已经放在吧台上');};$('#flavors').append(b);}}
async function referenceDialog(){if(!refs.length){try{refs=await(await fetch('./assets/references.json')).json();}catch(e){return toast('参考索引暂时未能加载，请稍后再试');}}showActivity('EVERY REFERENCE MATTERS','逐图找到你的参考','<p>131张场景、人物和服装参考逐张对应到模型区域，另有5张空间清单。相同图片的不同上传记录共同对应相同细节；天空、海岸与海底的连接为补充设计。</p><div class="reference-list" id="reference-list"></div>');for(const r of refs){let card=document.createElement('button');card.className='reference-card';card.innerHTML=`<div class="reference-symbol">${LOCATIONS.find(l=>l.id===r.place)?.symbol||"♡"}</div><span><b>${r.id} · ${r.title}</b><small>${r.use}</small></span>`;card.onclick=()=>{$('#activity-dialog').close();go(r.place);};$('#reference-list').append(card);}}

function gameBridge(){const displayCraft=createCraftDisplay(W,clearExtra);return {
 displayCraft,weather:setLighting,
 go,enterActivity(id){go(id,{immediate:true});if(transition){camera.position.copy(transition.to);controls.target.copy(transition.toTarget);camera.lookAt(controls.target);transition=null;}},toast,note:(...args)=>{if(audioEnabled)note(...args);},
 prepare(){stopRide(false);stopTour();transition=null;if(fly)toggleFly(false);},
 snow(value){if(winter!==value)toggleSnow(value);},
 dance(value){ballet=value;},
 ensureAction(action,place){
  if(action==='photo')return photo();
  if(action==='royalDoor')W.interactions.state.royalOpen=false;
  if(action==='treeHalo'){if(!winter)toggleSnow(true);W.interactions.state.treeSpin=false;}
  if(action==='party')party=false;
  if(action==='pearl')state.shellOpen=false;
  act(action,true);
 },
 cake(berries=[]){clearExtra('cake');const K=W.K,g=K.group(W.mansion.ground,'亲手完成的草莓庆祝蛋糕',-8.15,3.335,-21.9);g.scale.setScalar(.31);K.disk(g,0,.21,0,1.06,.10,K.gold);K.cyl(g,0,.57,0,.85,.88,.60,'#d79a57',48);K.disk(g,0,.94,0,.88,.12,C.cream);for(let i=0;i<20;i++){const a=i/20*Math.PI*2;K.ell(g,Math.sin(a)*.80,.97,Math.cos(a)*.80,.10,.075,.10,C.cream,12);}for(const p of berries){K.ell(g,p.x,1.15,p.z,.17,.23,.17,C.hot,20);K.star(g,p.x,1.38,p.z,.15,C.leaf);}K.optimize(g);actExtra.push({key:'cake',g});},
 outfit(style,color,accessory='none'){
  state.dressTarget='deep';state.dressStyle=style;state.dressColor=color;updateOutfit();
  const d=W.deep.movers.runway;d.userData.gameAccessory?.removeFromParent();const acc=W.K.group(d,'游戏奖励配饰');acc.userData.live=true;
  if(accessory==='crown')W.deep.A.crown(acc,0,2.54,0,1);
  if(accessory==='wings')W.deep.A.wings(acc,1,color);
  if(accessory==='bow')W.deep.A.bow(acc,.19,2.48,.02,.36,color);
  W.K.optimize(acc);d.userData.gameAccessory=acc;setupSparkles();
 },
 nails(color,finish,crystals=false){state.nailColor=color;state.nailFinish=finish;updateNails();clearExtra('quest-nail-gems');if(crystals){const g=W.K.group(W.palace.live,'亲手完成的水晶美甲',-28,3.14,3.1);for(let i=0;i<5;i++)W.palace.A.gem(g,-.64+i*.32,.13,-.13,.034,C.cream);W.K.optimize(g);actExtra.push({key:'quest-nail-gems',g});}},
 celebration(){setLighting('dusk');ballet=true;party=true;partyLight.visible=true;W.interactions.state.linerLit=true;}
};}

let partyLight;
async function init(){renderer=new T.WebGLRenderer({canvas:$('#scene'),antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,innerWidth<720?1.5:1.75));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.96;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
 scene=new T.Scene();scene.background=new T.Color('#b6e6f2');scene.fog=new T.FogExp2(scene.background,.0018);scene.environment=environment();scene.environmentIntensity=.65;camera=new T.PerspectiveCamera(44,innerWidth/innerHeight,.05,1200);camera.position.set(84,63,102);controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,6,-12);controls.enableDamping=true;controls.dampingFactor=.075;controls.minDistance=1;controls.maxDistance=550;controls.maxPolarAngle=Math.PI*.88;controls.zoomSpeed=.9;
 hemi=new T.HemisphereLight('#e5f6ff','#bd9cab',1.65);scene.add(hemi);sun=new T.DirectionalLight('#fff3df',2.5);sun.position.set(-46,89,34);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-80,right:80,top:85,bottom:-85,near:1,far:260});sun.shadow.normalBias=.07;sun.shadow.bias=-.00005;sun.target.position.set(0,0,-10);scene.add(sun,sun.target);fill=new T.DirectionalLight('#dfeaff',.95);fill.position.set(40,32,-40);scene.add(fill);skyLight=new T.DirectionalLight('#75e2ff',2.4);skyLight.position.set(10,5,135);skyLight.target.position.set(0,-30,110);scene.add(skyLight,skyLight.target);
 $('#load-status').textContent='正在布置房间、人物与珊瑚花园…';await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));
 const textures={};W=buildWorld(textures);scene.add(W.root);weather=installWeather(W,scene);installSeaOptics(W);atmosphere=createAtmosphere();scene.add(atmosphere);for(let p of [[85,-34,105],[85,-35,125]]){let l=new T.PointLight('#ffe0ed',45,40,1.5);l.position.set(...p);scene.add(l);wardrobeLights.push(l);}setupSparkles();installForestLight(W.skyCity.forest);
 ocean=new T.Mesh(new T.PlaneGeometry(1700,1700,140,140),waterMaterial());ocean.rotation.x=-Math.PI/2;ocean.position.y=-.16;ocean.name='海洋';scene.add(ocean);for(let w of W.mansion.movers.poolWater){const geo=w.geometry.clone();geo.rotateX(Math.PI/2);w.geometry=geo;w.rotation.x=-Math.PI/2;w.material=waterMaterial(true);}
 for(let [x,y,z,c]of [[-4,3,12,'#7fa9ff'],[7,3,17,'#b1caff'],[-23,6,-8,'#ffc6e9'],[0,10,-43,'#ffdfb3'],[-29,11,0,'#ffe8c7']]){let l=new T.PointLight(c,0,25,2);l.position.set(x,y,z);scene.add(l);poolLights.push(l);}partyLight=new T.PointLight('#de67fa',25,18,2);partyLight.position.set(4,12,-17);partyLight.visible=false;scene.add(partyLight);makeText('Barbie',0,13.0,-26.65,7);makeText('Dreamhouse',0,11.5,-26.6,7);makeText('Glitter Club',-28,6.8,17.79,4.5);makeText('Royal Ballet',-114,51.5,-70.1,12);makeText('Dream Academy',-57,47,-102.25,4);makeText('Couture under the Sea',85,-31,129.8,12);makeText('Christmas Wishes',87,8,-43,10);for(let l of [...W.town.labels,...W.liner.labels])makeText(l.text,...l.pos,l.width,l.parent);
 const sf=W.K.group(W.underwater.sea,'穿过海水的光束');for(let i=0;i<7;i++){let q=W.K.cyl(sf,-25+i*8,15,-8-i%3*7,.12,2.0,24,W.K.mat('#b5f6ff',{transparent:true,opacity:.055,depthWrite:false,side:T.DoubleSide}),12);q.rotation.z=-.2;q.castShadow=false;}
 $('#day-button').onclick=()=>$('#weather-dialog').showModal();$$('[data-time]').forEach(b=>b.onclick=()=>{setLighting(b.dataset.time);$('#weather-dialog').close();});$('#snow-button').onclick=()=>toggleSnow();$('#help-button').onclick=()=>$('#help-dialog').showModal();$('#photo-button').onclick=photo;$('#sound-button').onclick=()=>{audioEnabled=!audioEnabled;$('#sound-button').setAttribute('aria-pressed',String(audioEnabled));$('#sound-button').innerHTML='♫ <span>'+(audioEnabled?'有声':'声音')+'</span>';if(audioEnabled){getAudio();note(523.25);toast('轻柔环境旋律已开启');}else toast('声音已关闭');};$('#fold-menu').onclick=()=>{let f=$('.destinations').classList.toggle('folded');$('#fold-menu').textContent=f?'+':'−';};$('#tour-button').onclick=()=>tour?stopTour():startTour();$('#fly-button').onclick=()=>toggleFly();$('#zoom-in').onclick=()=>zoom(.8);$('#zoom-out').onclick=()=>zoom(1.25);$('#reset-camera').onclick=()=>go(world==='wardrobe'?'deepcloset':world==='underwater'?'reef':world==='sky'?'skycity':world==='beach'?'beach':'overview');$$('[data-world]').forEach(b=>b.onclick=()=>go({home:'overview',beach:'beach',underwater:'reef',sky:'skycity',wardrobe:'deepcloset'}[b.dataset.world]));$$('[data-layer]').forEach(b=>b.onclick=()=>setLayer(b.dataset.layer));$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
 const rb=document.createElement('button');rb.className='primary reference-open';rb.textContent='查看全部参考与对应区域';rb.onclick=()=>{$('#help-dialog').close();referenceDialog();};$('#help-dialog details').before(rb);
 controls.addEventListener('start',()=>{transition=null;stopTour();});installModelClicks();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);});addEventListener('keydown',e=>{if(e.code==='Escape'){stopRide();stopTour();if(fly)toggleFly(false);}if(fly&&!game?.busy()&&!$('dialog[open]')&&['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyE','ShiftLeft','ShiftRight'].includes(e.code)){e.preventDefault();flightKeys.add(e.code);}});addEventListener('keyup',e=>flightKeys.delete(e.code));addEventListener('blur',()=>flightKeys.clear());$$('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);flightKeys.add(b.dataset.key);};b.onpointerup=b.onpointercancel=()=>flightKeys.delete(b.dataset.key);});$('#scene').addEventListener('webglcontextlost',e=>{e.preventDefault();fail(new Error('图形环境中断，重新打开即可继续。'));});go('overview',{immediate:true});setLighting('day');game=createGame({W,scene,camera,controls,locations:LOCATIONS,bridge:gameBridge(),reduced});$('#loading').classList.add('done');animate();}
function installModelClicks(){
 const canvas=$('#scene'),raycaster=new T.Raycaster(),point=new T.Vector2(),pointers=new Set();let down=null;
 canvas.addEventListener('pointerdown',e=>{pointers.add(e.pointerId);if(pointers.size>1){down=null;return;}const cancelled=!!ride;if(ride)stopRide();down={x:e.clientX,y:e.clientY,id:e.pointerId,cancelled};});
 canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);down=null;});
 canvas.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);const start=down;down=null;if(game?.busy()||e.gameConsumed)return;if(!start||start.id!==e.pointerId||start.cancelled||fly||Math.hypot(e.clientX-start.x,e.clientY-start.y)>6||e.button>0)return;const bounds=canvas.getBoundingClientRect();point.set((e.clientX-bounds.left)/bounds.width*2-1,-(e.clientY-bounds.top)/bounds.height*2+1);W.root.updateMatrixWorld(true);camera.updateMatrixWorld(true);raycaster.setFromCamera(point,camera);const available=W.interactions.items.filter(i=>visibleInScene(i.object));const candidates=raycaster.intersectObjects(available.map(i=>i.object),true).filter(h=>visibleInScene(h.object));if(!candidates.length)return;const chosen=candidates[0];raycaster.far=chosen.distance+.015;const obstruction=raycaster.intersectObject(W.root,true).find(h=>visibleInScene(h.object)&&!(h.object.material?.transparent&&h.object.material.opacity<.6));raycaster.far=Infinity;if(obstruction&&obstruction.distance<chosen.distance-.08)return;let target;for(let o=chosen.object;o&&!target;o=o.parent)target=available.find(i=>i.object===o);if(target)act(target.action);});
}
function zoom(s){transition=null;camera.position.copy(controls.target.clone().add(camera.position.clone().sub(controls.target).multiplyScalar(s)));}
function photo(){try{renderer.render(scene,camera);const a=document.createElement('a');a.download='芭比梦想豪宅-'+current.name+'.png';a.href=renderer.domElement.toDataURL('image/png');a.click();toast('当前画面已保存');game?.onAction('photo',current.id,true);}catch(e){toast('当前浏览器未能保存照片，请使用系统截图');}}
$('.download-model').addEventListener('click',async e=>{e.preventDefault();const button=e.currentTarget;if(button.dataset.busy)return;button.dataset.busy='1';const label=button.textContent;try{button.textContent='正在准备完整模型…';const r=await fetch('./assets/model-info.json');if(!r.ok)throw Error('未能获取模型信息');const info=await r.json(),chunks=[];for(let i=0;i<info.parts.length;i++){button.textContent=`正在准备模型 ${i+1}/${info.parts.length}`;let response=await fetch('./assets/'+info.parts[i]);if(!response.ok)throw Error('模型下载中断，请重试');chunks.push(await response.arrayBuffer());}const blob=new Blob(chunks,{type:'model/gltf-binary'});if(blob.size!==info.glbBytes)throw Error('模型尚未下载完整，请重试');const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='芭比-海屿梦想豪宅.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('完整3D模型已准备好');}catch(err){toast(err.message);}finally{delete button.dataset.busy;button.textContent=label;}});
let prev=performance.now(),melodyAt=0,melodyIndex=0;
function animate(now=performance.now()){requestAnimationFrame(animate);if(document.hidden){prev=now;return;}const dt=Math.min((now-prev)/1000,.05);prev=now;t+=dt;
 if(transition){transition.elapsed+=dt;let q=transition.duration?Math.min(1,transition.elapsed/transition.duration):1;q=q*q*(3-2*q);camera.position.lerpVectors(transition.from,transition.to,q);controls.target.lerpVectors(transition.fromTarget,transition.toTarget,q);if(q>=1)transition=null;}
 if(tour&&t>tourNext){tourIndex=(tourIndex+1)%route.length;go(route[tourIndex],{keepTour:true});tourNext=t+8;$('#tour-button').textContent='Ⅱ 暂停漫游';}
 if(fly){let speed=dt*(flightKeys.has('ShiftLeft')||flightKeys.has('ShiftRight')?20:6),d=camera.getWorldDirection(v(0,0,0)),right=v().crossVectors(d,camera.up).normalize(),delta=v(0,0,0);if(flightKeys.has('KeyW'))delta.addScaledVector(d,speed);if(flightKeys.has('KeyS'))delta.addScaledVector(d,-speed);if(flightKeys.has('KeyA'))delta.addScaledVector(right,-speed);if(flightKeys.has('KeyD'))delta.addScaledVector(right,speed);if(flightKeys.has('KeyQ'))delta.y-=speed;if(flightKeys.has('KeyE'))delta.y+=speed;camera.position.add(delta);controls.target.add(delta);}
 const mm=W.mansion.movers,im=W.island.movers,um=W.underwater.movers;
 if(!reduced){mm.flamingo.position.y=1.98+Math.sin(t)*.04;mm.flamingo.rotation.y=Math.sin(t*.2)*.15;im.boat.rotation.z=Math.sin(t*.7)*.025;im.balloon.position.y=21+Math.sin(t*.28)*.6;if(state.swing)mm.swing.rotation.x=Math.sin(t*1.4)*.13;if(party){mm.disco.rotation.y=t*.7;partyLight.color.setHSL((t*.09)%1,.75,.62);}}
 for(let w of [ocean,...mm.poolWater])w.material.uniforms.time.value=reduced?0:t;for(let m of W.K.mats.values())if(m.userData.shader)m.userData.shader.uniforms.sparkleTime.value=reduced?2:t;
 if(submergedWorld(world)){for(let f of um.fish){let a=f.a+(reduced?0:t*f.speed);f.g.position.set(Math.cos(a)*f.r,f.y+Math.sin(a*4)*.3,Math.sin(a)*f.r*.65);f.g.rotation.y=-a-Math.PI/2;}for(let [i,m]of um.mermaids.entries()){m.g.position.y=m.base.y+(reduced?0:Math.sin(t*.7+i)*.25);m.tail.rotation.z=reduced?0:Math.sin(t*1.7+i)*.045;}um.jelly.forEach((j,i)=>j.g.position.y=j.y+(reduced?0:Math.sin(t*.6+i)*.3));um.turtle.position.x=-13+(reduced?0:Math.sin(t*.14)*4);um.shell.rotation.x=T.MathUtils.damp(um.shell.rotation.x,state.shellOpen?-1.12:0,4,dt);}
 animatePalms(W,t,reduced);animateForest(W,t,reduced,lighting);animateExpansion(W,t,reduced,world,winter,weather,camera,ballet);animateGlassCoast(W,t,reduced);atmosphere.position.copy(camera.position);updateWorldInteractions(W,dt,t,reduced);if(world==='home'&&!['overview','pool'].includes(current.id))weather.flakes.visible=false;
 if(ride){const r=ride,q=Math.min(1,(t-r.start)/r.duration);let custom=expansionRide(W,r.type,q,r);if(custom){camera.position.copy(custom.position);controls.target.copy(custom.target);}else if(r.type==='slide'){let p=mm.slide.getPoint(q);camera.position.copy(p).add(v(0,.70,0));controls.target.copy(mm.slide.getPoint(Math.min(1,q+.07))).add(v(0,.4,0));}else if(r.type==='drive'){let a=(q+(r.offset||0))%1,p=im.roadCurve.getPoint(a),d=im.roadCurve.getTangent(a);im.car.position.copy(p).add(v(0,.13,0));im.car.rotation.y=Math.atan2(-d.x,-d.z);camera.position.copy(p).addScaledVector(d,-7).add(v(0,3.7,0));controls.target.copy(p).addScaledVector(d,4).add(v(0,1.1,0));}else if(r.type==='mermaid'){let m=um.mermaids[0],a=q*Math.PI*2;m.g.position.set(-4+Math.sin(a)*10,5+Math.sin(a)*2,5+Math.cos(a)*7);m.g.rotation.y=a;let p=m.g.getWorldPosition(v());camera.position.copy(p).add(v(5,2,8));controls.target.copy(p).add(v(0,1,0));}else if(r.type==='balloon'){let p=im.balloon.getWorldPosition(v());camera.position.copy(p).add(v(0,3,1));controls.target.copy(v(0,8,-16));camera.position.y+=Math.sin(q*Math.PI)*12;}else if(r.type==='lift'){let yy=2.2+(state.liftUp?1-q:q)*6.3;W.palace.movers.lift.position.y=yy;camera.position.set(0,yy+1.7,-52.8);controls.target.set(0,yy+1.4,-35);}camera.lookAt(controls.target);if(q===1){if(r.type==='lift')state.liftUp=!state.liftUp;if(r.type==='mermaid'){let m=um.mermaids[0];m.g.position.copy(m.base);m.g.rotation.y=0;}stopRide();if(r.type==='deepLift')go(r.toY<-36?'deepcloset':'deepaccess');}}
 else if(!game?.hasScene())controls.update();game?.update(dt,t);if(audioEnabled&&t>melodyAt){note([261.63,329.63,392,523.25,440,349.23,293.66,392][melodyIndex++%8],1.6);melodyAt=t+2.2;}renderer.render(scene,camera);
}
init().catch(fail);
