export const CROPS=[{id:'berry',name:'草莓',color:'#d33c71',time:24,cost:1,sell:6},{id:'mint',name:'薄荷',color:'#68ab73',time:18,cost:1,sell:4},{id:'wheat',name:'小麦',color:'#e8bd61',time:30,cost:0,sell:5}];
export const FLAVORS=[{id:'soda',name:'苏打水',color:'#a6d5fc'},{id:'milk',name:'香草奶',color:'#fff2d7'},{id:'berry',name:'草莓果浆',color:'#dc487e'},{id:'citrus',name:'柠檬汁',color:'#ffda68'},{id:'mint',name:'薄荷露',color:'#85c597'}];
export const DRINKS=[{name:'落日莓果气泡',parts:{soda:3,berry:2,citrus:1},method:'stir'},{name:'草莓云朵奶昔',parts:{milk:3,berry:2},method:'shake'},{name:'海风薄荷特调',parts:{soda:3,mint:1,citrus:1},method:'stir'}];
export const PARTS={sand:[{id:'tower',name:'圆塔',w:1,d:1},{id:'wall',name:'城墙',w:2,d:1},{id:'gate',name:'拱门',w:2,d:1},{id:'roof',name:'尖顶',w:1,d:1},{id:'stairs',name:'阶梯',w:1,d:1},{id:'flag',name:'旗帜',w:1,d:1}],blocks:[{id:'brick',name:'双粒砖',w:2,d:1},{id:'square',name:'四粒砖',w:2,d:2},{id:'single',name:'单粒砖',w:1,d:1},{id:'window',name:'窗框',w:2,d:1},{id:'roof',name:'屋顶',w:2,d:2},{id:'arch',name:'拱门',w:2,d:1}]};
export const PAINTS=['#da5a94','#fff1d5','#86b9eb','#ad8dda','#76b1a2','#e8bd68'];
export function freshCraft(){return {plots:Array.from({length:6},(_,i)=>i===0?{crop:'berry',water:1,growth:24}:{crop:null,water:0,growth:0}),inventory:{berry:3,mint:3,wheat:3},harvested:0,contracts:0,drinkBook:[],cupcakes:[],builds:{sand:[],blocks:[]},shelves:{sand:[],blocks:[]}};}
const num=(v,a,b)=>Math.min(b,Math.max(a,Number.isFinite(v)?v:a));
export function validPieces(list,mode){const out=[];if(!Array.isArray(list))return out;for(const p of list.slice(0,140)){if(!p||!PARTS[mode].some(a=>a.id===p.id)||!PAINTS.includes(p.color)||![p.x,p.z,p.y,p.rot].every(Number.isInteger))continue;const q={id:p.id,x:p.x,z:p.z,y:p.y,rot:p.rot%2,color:p.color};if(canPlace(out,q,mode))out.push(q);}return out;}
export function restoreCraft(d){const s=freshCraft();if(!d||typeof d!=='object')return s;for(let i=0;i<6;i++){const p=d.plots?.[i],crop=CROPS.find(c=>c.id===p?.crop);s.plots[i]=crop?{crop:crop.id,water:num(p.water,0,1),growth:num(p.growth,0,crop.time)}:{crop:null,water:0,growth:0};}for(const c of CROPS)s.inventory[c.id]=Math.floor(num(d.inventory?.[c.id]??3,0,9999));s.harvested=Math.floor(num(d.harvested,0,99999));s.contracts=Math.floor(num(d.contracts,0,99999));s.drinkBook=Array.isArray(d.drinkBook)?[...new Set(d.drinkBook.filter(i=>Number.isInteger(i)&&i>=0&&i<DRINKS.length))]:[];s.cupcakes=(Array.isArray(d.cupcakes)?d.cupcakes:[]).slice(0,6).filter(a=>a&&Array.isArray(a.dots)).map(a=>({name:typeof a.name==='string'?a.name.slice(0,24):'奶油纸杯蛋糕',dots:a.dots.slice(0,700).filter(p=>Array.isArray(p)&&p.length===5&&p.slice(0,3).every(n=>Number.isFinite(n)&&Math.abs(n)<5)&&PAINTS.includes(p[3])&&['round','star','rose','berry','pearl','sprinkle'].includes(p[4])).map(p=>[...p])}));for(const mode of ['sand','blocks']){s.builds[mode]=validPieces(d.builds?.[mode],mode);s.shelves[mode]=(Array.isArray(d.shelves?.[mode])?d.shelves[mode]:[]).slice(0,4).filter(a=>a&&Array.isArray(a.parts)).map(a=>({name:typeof a.name==='string'?a.name.slice(0,24):'我的作品',parts:validPieces(a.parts,mode)}));}return s;}
export function plant(s,i,crop){const c=CROPS.find(c=>c.id===crop),p=s.craft.plots[i];if(!c||!p||p.crop||s.coins<c.cost)return false;s.coins-=c.cost;Object.assign(p,{crop,water:0,growth:0});return true;}
export function water(s,i,amount){const p=s.craft.plots[i];if(!p?.crop)return false;p.water=Math.min(1,p.water+Math.max(0,amount));return true;}
export function grow(s,dt){let changed=false;for(const p of s.craft.plots){const c=CROPS.find(c=>c.id===p.crop);if(c&&p.water>=1&&p.growth<c.time){p.growth=Math.min(c.time,p.growth+Math.max(0,Math.min(dt,.2)));changed=true;}}return changed;}
export function harvest(s,i){const p=s.craft.plots[i],c=CROPS.find(c=>c.id===p?.crop);if(!c||p.growth<c.time)return false;s.craft.inventory[c.id]+=3;s.craft.harvested+=3;Object.assign(p,{crop:null,water:0,growth:0});return true;}
export function sellCrop(s,id){const c=CROPS.find(c=>c.id===id);if(!c||s.craft.inventory[id]<1)return false;s.craft.inventory[id]--;s.coins+=c.sell;return true;}
export function fulfill(s){if(CROPS.some(c=>s.craft.inventory[c.id]<2))return false;for(const c of CROPS)s.craft.inventory[c.id]-=2;s.craft.contracts++;s.coins+=40;return true;}
export function drinkScore(parts,recipe,method,motion){const total=Object.values(parts).reduce((a,b)=>a+b,0),need=Object.values(recipe.parts).reduce((a,b)=>a+b,0);if(total<.5)return 0;const err=FLAVORS.reduce((n,f)=>n+Math.abs((parts[f.id]||0)/total-(recipe.parts[f.id]||0)/need),0);return Math.round(Math.max(0,70*(1-err/2))+(method===recipe.method?15:5)+Math.min(15,motion*3));}
export function footprint(p,mode){const d=PARTS[mode].find(a=>a.id===p.id);if(!d)return [];const w=p.rot?d.d:d.w,h=p.rot?d.w:d.d,out=[];for(let x=0;x<w;x++)for(let z=0;z<h;z++)out.push([p.x+x,p.z+z]);return out;}
export function canPlace(list,p,mode){if(!p||!Number.isInteger(p.y)||p.y<0||p.y>5||list.length>=140)return false;const cells=footprint(p,mode);if(!cells.length||cells.some(([x,z])=>!Number.isInteger(x)||!Number.isInteger(z)||x< -4||x>4||z< -4||z>4))return false;for(const [x,z]of cells){if(list.some(q=>q.y===p.y&&footprint(q,mode).some(c=>c[0]===x&&c[1]===z)))return false;if(p.y>0&&!list.some(q=>q.y===p.y-1&&footprint(q,mode).some(c=>c[0]===x&&c[1]===z)))return false;}return true;}
export function erasePiece(list,index,mode){const out=list.filter((_,i)=>i!==index);return out.every(p=>p.y===0||footprint(p,mode).every(([x,z])=>out.some(q=>q.y===p.y-1&&footprint(q,mode).some(c=>c[0]===x&&c[1]===z))))?out:null;}
