import {createFestivalDisplay} from './festival-display.js';
import {createTravel} from './travel.js';
import {createAdventure} from './adventure.js';
import {T,v,C} from './kit.js';
import {QUESTS,LOOKS,SOURCES,SAVE_KEY,freshSave,restoreSave,reduceGame,currentStep,isUnlocked,unlockedLooks,stars} from './game-state.js';
import {createLifestyle} from './lifestyle.js';
import {startHandsOn,HANDS_ON_KINDS} from './hands-on.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escapeText=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createGame({W,scene,camera,controls,locations,bridge,reduced=false}){
 let save=freshSave(),saveFailed=false;try{save=restoreSave(localStorage.getItem(SAVE_KEY));}catch{saveFailed=true;}
 let life=null,travel=null,adventure=null,festival=null;
 let current=locations[0],panelStop=null,handsOn=null,sceneRun=null,mode='game',lastTime=0,transitionReady=0,winTimer=0;
 const gameRoot=new T.Group();gameRoot.name='游戏任务与庆典';scene.add(gameRoot);
 const keys=new Set(),ray=new T.Raycaster(),pointer=new T.Vector2();let down=null;
 document.body.classList.add('game-mode');
 document.body.insertAdjacentHTML('beforeend',`
 <nav class="game-toolbar glass" aria-label="游戏工具"><button id="world-map" class="life-open">✧ <span>星光海屿</span></button><button id="dream-life" class="life-open">✧ <span>梦想生活</span></button><button id="quest-book">☷ <span>旧日故事</span></button><button id="game-closet">♕ <span>奖励衣橱</span></button><button id="game-mode" aria-pressed="true">⌖ <span>自由探索</span></button><span class="star-bank" id="star-bank">✦ 0</span></nav>
 <nav class="life-shortcuts" aria-label="直接开始生活玩法">${[['fashion','高级换装'],['farm','农场经营'],['pet','小动物'],['mix','调饮'],['cupcake','蛋糕裱花'],['sand','堆沙堡'],['blocks','拼积木']].map(([id,n])=>`<button data-life-shortcut="${id}">${n}</button>`).join('')}</nav>
 <aside class="quest-tracker glass" aria-label="当前游戏任务"><div class="quest-topline"><span>梦 想 冒 险</span><button id="quest-minimize" aria-label="折叠任务">−</button></div><div id="quest-detail"></div></aside>
 <section id="scene-challenge" class="glass" hidden aria-label="场景挑战"><div><b id="scene-challenge-title"></b><button id="cancel-challenge" aria-label="暂停挑战">×</button></div><p id="scene-instruction"></p><strong id="scene-score" role="status"></strong><div id="scene-targets"></div><div id="flight-pad" hidden><button data-steer="ArrowLeft" aria-label="向左">←</button><button data-steer="ArrowUp" aria-label="上升">↑</button><button data-steer="ArrowDown" aria-label="下降">↓</button><button data-steer="ArrowRight" aria-label="向右">→</button></div></section>
 <div id="quest-markers" aria-label="场景中可收集的物品"></div>
 <dialog id="quest-dialog" aria-labelledby="quest-dialog-title"><button class="close-dialog" aria-label="关闭">×</button><div id="quest-dialog-body"></div></dialog>
 <dialog id="game-challenge-dialog" aria-label="游戏挑战"><button class="close-dialog" aria-label="暂停挑战">×</button><div id="game-challenge-body"></div></dialog>
 <div id="game-win" role="status" aria-live="polite" hidden></div>`);
 const dialog=$('#quest-dialog'),body=$('#quest-dialog-body'),challengeDialog=$('#game-challenge-dialog');
 function persist(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(save));saveFailed=false;}catch{saveFailed=true;}}
 function send(event){const before=save.completed.length,old=save.progress[save.active]||0;save=reduceGame(save,event);persist();render();if(save.completed.length>before){const q=QUESTS.find(q=>q.id===save.active);celebrate(q);return true;}if((save.progress[save.active]||0)>old){bridge.toast(currentStep(save)?'完成！下一步：'+currentStep(save).text:'重玩完成！最高成绩已保留，不重复发放奖励。');return true;}return false;}
 function render(){const q=QUESTS.find(q=>q.id===save.active),step=currentStep(save),n=save.progress[q.id]||0;$('#star-bank').textContent=`✦ ${stars(save)} · ${save.completed.length}/10`;$('#quest-detail').innerHTML=`<span class="quest-chapter">${q.icon} ${q.short}</span><h2>${q.title}</h2><p class="quest-dialogue"><b>${q.npc}</b>：${save.started?(step?step.text:'谢谢你！这枚徽章属于你。'):q.intro}</p><ol class="quest-steps">${q.steps.map((s,i)=>`<li class="${i<n?'done':i===n?'now':''}"><span>${i<n?'✓':i+1}</span>${s.text}</li>`).join('')}</ol><div class="quest-reward">✦ ${q.reward} 星光 · ${q.badge}</div><button class="primary" id="quest-next">${!save.started?'接受第一个委托':!step?'选择下一段冒险':step.place!==current.id?'前往'+locations.find(l=>l.id===step.place).name:step.type==='challenge'?'开始挑战':step.text}</button><button class="text-button" id="quest-read">听听伙伴怎么说</button><small class="save-label">${saveFailed?'本机暂时无法保存，离开页面会丢失进度':'本机自动保存 · 随时可以继续'}</small>`;
 $('#quest-next').onclick=next;$('#quest-read').onclick=()=>openDialogue(q);$('.quest-tracker').style.setProperty('--quest-color',q.color);}
 function open(){if(!dialog.open)dialog.showModal();}
 function openDialogue(q){body.innerHTML=`<span class="eyebrow">${q.icon} ${q.short}</span><h2 id="quest-dialog-title">${q.npc}的委托</h2><p class="companion-line">“${q.intro}”</p><p>奖励：<b>${q.badge}</b>徽章、${q.reward} 星光，以及「${LOOKS.find(l=>l.id===q.gift).name}」。</p><button class="primary" id="accept-quest">${save.started?'好，我们出发':'接受委托'}</button>`;open();$('#accept-quest').onclick=()=>{dialog.close();send({type:'start'});next();};}
 function next(){if(sceneRun||handsOn)return;if(!save.started){send({type:'start'});openDialogue(QUESTS.find(q=>q.id===save.active));return;}const step=currentStep(save);if(!step){journal();return;}if(current.id!==step.place){bridge.go(step.place);transitionReady=performance.now()+1800;return;}if(performance.now()<transitionReady){bridge.toast('正在靠近任务地点，稍等一下就能开始。');return;}if(step.type==='action')return;startChallenge(step);}
 function journal(){body.innerHTML=`<span class="eyebrow">THE DREAM JOURNAL</span><h2 id="quest-dialog-title">十段冒险，一座梦想海屿</h2><p>任选一段故事开始。集齐九枚伙伴徽章，就能开启最终庆典。</p><label class="slow-switch"><input type="checkbox" id="slow-game" ${save.slow?'checked':''}> 舒缓挑战 <small>放慢节拍与飞行，寻物不限时</small></label><div class="quest-grid">${QUESTS.map(q=>{const done=save.completed.includes(q.id),unlocked=isUnlocked(save,q.id);return `<button class="quest-card ${done?'completed':''}" data-quest="${q.id}" ${unlocked?'':'disabled'} style="--quest-color:${q.color}"><span class="quest-emblem">${done?'✓':q.icon}</span><span><strong>${q.title}</strong><small>${done?'已获徽章 · 可重玩':unlocked?q.short+' · ✦ '+q.reward:'集齐前九枚徽章后开启'}</small></span>${save.best[q.id]?`<b>${save.best[q.id]}分</b>`:''}</button>`;}).join('')}</div><p class="quiet">${saveFailed?'浏览器暂时无法保存进度。':'游戏进度只保存在这台设备的当前浏览器中。'}本作任务为根据动画主题创作的原创玩法。</p><details><summary>电影与动画灵感</summary>${SOURCES.map(([title,url,theme])=>`<p><a href="${url}" target="_blank" rel="noreferrer">${title}</a> · ${theme}</p>`).join('')}</details><button class="text-button danger" id="reset-game">重新开始全部故事</button>`;open();$('#slow-game').onchange=e=>send({type:'slow',value:e.target.checked});$$('[data-quest]').forEach(b=>b.onclick=()=>{cancel();if(mode!=='game')setMode('game');send({type:'select',id:b.dataset.quest,replay:save.completed.includes(b.dataset.quest)});send({type:'start'});dialog.close();openDialogue(QUESTS.find(q=>q.id===save.active));});$('#reset-game').onclick=()=>{body.innerHTML='<h2 id="quest-dialog-title">重新开始全部故事？</h2><p>这会清除本机的章节、徽章与奖励服装。豪宅和场景不受影响。</p><div class="game-choices"><button class="primary" id="keep-save">保留进度</button><button class="secondary" id="confirm-reset">清除游戏进度</button></div>';$('#keep-save').onclick=journal;$('#confirm-reset').onclick=()=>{cancel();save=freshSave();persist();restoreWorldRewards();render();dialog.close();bridge.go('kitchen');};};}
 function closet(){const unlocked=unlockedLooks(save);body.innerHTML=`<span class="eyebrow">COLLECT YOUR DREAMS</span><h2 id="quest-dialog-title">我的奖励衣橱</h2><p>完成故事获得整套造型。点「穿上」后，海底衣帽宫的人偶会换上对应服装和配饰。</p><div class="looks-grid">${LOOKS.map(l=>{const ok=unlocked.some(x=>x.id===l.id),quest=QUESTS.find(q=>q.gift===l.id);return `<button data-look="${l.id}" class="look-card" ${ok?'':'disabled'} aria-pressed="${save.look===l.id}"><i style="background:${l.color}">${l.accessory==='wings'?'✧':l.accessory==='crown'?'♕':'♡'}</i><strong>${l.name}</strong><small>${ok?(save.look===l.id?'已穿上':'穿上这套'):'完成「'+quest.short+'」'}</small></button>`;}).join('')}</div>`;open();$$('[data-look]').forEach(b=>b.onclick=()=>{const l=LOOKS.find(l=>l.id===b.dataset.look);send({type:'look',id:l.id});dialog.close();bridge.go('deepcloset');bridge.outfit(l.style,l.color,l.accessory);bridge.toast('已穿上「'+l.name+'」，奖励配饰也一起佩戴好了。');});}
 function startChallenge(step){
  cancel();send({type:'start'});bridge.prepare();document.body.classList.add('challenge-active');
  if(['cleanup','pollen','flight'].includes(step.kind)){startScene(step);return;}
  if(HANDS_ON_KINDS.includes(step.kind))handsOn=startHandsOn({kind:step.kind,W,scene,camera,controls,bridge,slow:save.slow,cancel,finish:result=>{
   const session=handsOn;handsOn=null;session?.stop();document.body.classList.remove('challenge-active');
   if(!send({type:'challenge',place:step.place,kind:step.kind,result}))bridge.toast('这次操作完成了！可以从任务手册继续伙伴的委托。');
   if(step.kind==='portal')bridge.go('forest');
  }});
 }

 function interact(action){
  if(action==='worldFestival'){adventure?.open();return true;}
  if(["bus","yacht","submarine"].includes(action)){travel?.open(action);return true;}
  const activities={drink:'mix',teaCafe:'cafe',dress:'fashion',deepDress:'fashion',farm:'farm',animals:'pet',cupcake:'cupcake',sandcastle:'sand',blocks:'blocks'};if(activities[action]){life.open(activities[action]);return true;}
  const mapping={cake:'bake',nails:'nails',dress:'style',deepDress:'style',ballet:'rhythm',party:'partyDance',royalDoor:'carriage',pearl:'pearl',portal:'portal',treeHalo:'treeLights'};
  const kind=mapping[action];if(!kind)return false;if(handsOn||sceneRun)return true;
  const step=QUESTS.flatMap(q=>q.steps).find(s=>s.kind===kind);if(!step)return false;
  if(current.id!==step.place)bridge.enterActivity(step.place);
  startChallenge(step);return true;
 }

 function onAction(action,place,success){if(mode==='game')send({type:'action',action,place,success});}
 function cancel(){adventure?.close();travel?.close();life?.close();handsOn?.stop();handsOn=null;panelStop?.();panelStop=null;if(challengeDialog.open)challengeDialog.close();stopScene();document.body.classList.remove('challenge-active');keys.clear();}
 function onLocation(l){if(l.id!==current.id){cancel();transitionReady=performance.now()+1700;}current=l;render();}
 function celebrate(q){restoreWorldRewards();const l=LOOKS.find(l=>l.id===q.gift);$('#game-win').hidden=false;$('#game-win').innerHTML=`<span>✦ ${q.badge} ✦</span><strong>${q.title} · 完成</strong><p>+${q.reward} 星光 · 解锁「${l.name}」</p><button id="win-continue">${q.id==='finale'?'重温喜欢的故事':'继续下一段冒险'} →</button>`;$('#win-continue').onclick=()=>{$('#game-win').hidden=true;journal();};clearTimeout(winTimer);winTimer=setTimeout(()=>$('#game-win').hidden=true,9000);bridge.note(523,.4);bridge.note(659,.4,.15);bridge.note(784,.8,.3);if(q.id==='finale'){bridge.celebration();fireworks();}}
 // A small persistent aura marks the worlds the player has helped.
 const rewards=new T.Group();gameRoot.add(rewards);const rewardGroups={};
 for(const [id,origin]of [['ocean',[0,-30,109]],['forest',[-155,47,-89]],['swan',[-83,43,-57]]]){const g=new T.Group();g.position.set(...origin);rewards.add(g);for(let i=0;i<16;i++){const a=i/16*Math.PI*2;W.K.ell(g,Math.cos(a)*3,.5+Math.sin(a*3)*.4,Math.sin(a)*3,.075,.075,.075,W.K.glow,8);}rewardGroups[id]=g;}
 function restoreWorldRewards(){for(const [id,g]of Object.entries(rewardGroups))g.visible=save.completed.includes(id);}
 function fireworks(){let geo=new T.BufferGeometry(),ps=[],colors=[];for(let i=0;i<220;i++){ps.push(0,0,0);const c=new T.Color(['#ff75ba','#ffe5a1','#e1c6ff','#ffffff'][i%4]);colors.push(c.r,c.g,c.b);}geo.setAttribute('position',new T.Float32BufferAttribute(ps,3));geo.setAttribute('color',new T.Float32BufferAttribute(colors,3));const points=new T.Points(geo,new T.PointsMaterial({size:.55,vertexColors:true,transparent:true,depthWrite:false}));points.position.set(82,22,184);points.userData.burstAt=lastTime;gameRoot.add(points);bursts.push(points);}
 const bursts=[];
 function startScene(step){const root=new T.Group();root.name='当前游戏挑战';gameRoot.add(root);sceneRun={step,root,elapsed:0,score:0,collected:new Set(),objects:[],camera:camera.position.clone(),target:controls.target.clone(),remaining:step.kind==='pollen'?5:6};controls.enabled=false;$('#scene-challenge').hidden=false;$('#scene-challenge-title').textContent=QUESTS.find(q=>q.id===save.active).title;$('#flight-pad').hidden=step.kind!=='flight';$('#scene-targets').replaceChildren();$('#quest-markers').replaceChildren();if(step.kind==='flight'){startFlight();return;}
 const pollen=step.kind==='pollen',center=v(...(pollen?[-143,47,-85]:[0,-24,138]));camera.position.copy(center).add(v(0,3,Math.max(23,10/(Math.tan(camera.fov*Math.PI/360)*camera.aspect))));controls.target.copy(center);camera.lookAt(center);sceneRun.center=center;$('#scene-instruction').textContent=pollen?'收集粉金花粉，保留蓝色萤火虫。点光点上方的标记，或按数字 1–8。':'收走瓶子和包装，不要打扰小鱼。点物品上方的标记，或按数字 1–9。';
 const total=pollen?8:9,targetCount=pollen?5:6;for(let i=0;i<total;i++){const valid=i<targetCount,j=[0,4,8,2,6,1,3,5,7][i],g=new T.Group();g.position.copy(center).add(v((j%3-1)*7,(1-Math.floor(j/3))*3,Math.sin(i)*1.5));root.add(g);const color=valid?(pollen?'#ffb457':'#dbaad2'):'#559fdf';if(pollen){W.K.ell(g,0,0,0,valid?.27:.16,valid?.27:.16,valid?.27:.16,W.K.mat(color,{emissive:color,emissiveIntensity:.8,roughness:.2}),16);W.K.torus(g,0,0,0,.55,.025,W.K.gold);}else if(valid){if(i%2){W.K.box(g,0,0,0,.7,.55,.24,'#cfb6df',.05);g.rotation.z=.25;}else{W.K.cyl(g,0,0,0,.16,.19,.72,'#d4e7ff',16);W.K.cyl(g,0,.47,0,.10,.10,.22,C.rose,16);}}else{W.K.ell(g,0,0,0,.5,.25,.18,color,16);let tail=W.K.cyl(g,-.53,0,0,0,.26,.4,C.gold,3);tail.rotation.z=Math.PI/2;W.K.ell(g,.3,.07,.16,.04,.04,.03,C.dark,8);}
 W.K.optimize(g);const marker=document.createElement('button');marker.className='collect-marker';marker.setAttribute('aria-label',`${i+1} · ${pollen?(valid?'粉金花粉':'蓝色萤火虫'):(valid?'漂流垃圾':'小鱼')}`);marker.textContent=String(i+1);marker.onclick=()=>collect(i);$('#quest-markers').append(marker);sceneRun.objects.push({g,valid,marker,base:g.position.clone()});}
 updateSceneScore();}
 function updateSceneScore(){if(!sceneRun)return;const r=sceneRun,k=r.step.kind;if(k==='flight')$('#scene-score').textContent=`穿环 ${r.score}/6 · 航程 ${Math.min(9,r.gate||0)}/9`;else $('#scene-score').textContent=`已收集 ${r.collected.size}/${r.remaining}`+(save.slow?' · 不限时':` · 剩余 ${Math.max(0,Math.ceil(60-r.elapsed))} 秒`);}
 function collect(i){const r=sceneRun;if(!r||r.step.kind==='flight')return;const o=r.objects[i];if(!o||r.collected.has(i))return;if(!o.valid){r.elapsed+=3;bridge.toast(r.step.kind==='pollen'?'这是萤火虫，让它继续发光吧。':'这是小鱼，垃圾才需要带走哦。');updateSceneScore();return;}r.collected.add(i);o.g.visible=false;o.marker.hidden=true;bridge.note(420+r.collected.size*65,.2);updateSceneScore();if(r.collected.size===r.remaining){const {step}=r,result={count:r.remaining,score:Math.max(50,100-Math.floor(r.elapsed/3))};stopScene();document.body.classList.remove('challenge-active');send({type:'challenge',place:step.place,kind:step.kind,result});}}
 function startFlight(){const r=sceneRun,p=W.skyCity.movers.pegasus;r.horse=p;r.oldPosition=p.position.clone();r.oldRotation=p.rotation.clone();r.oldCamera=camera.position.clone();r.origin=v(-103,76,-20);r.player=v(0,0,0);r.gate=0;r.rings=[];r.savedWings=W.interactions.state.wings;W.interactions.state.wings=true;for(let i=0;i<9;i++){const x=[0,-3,3,0,-3,3,0,3,0][i],y=[0,2,0,-2,0,2,0,-2,0][i],z=15+i*15;const g=new T.Mesh(new T.TorusGeometry(2.4,.10,10,48),W.K.mat('#ffd779',{emissive:'#b76a28',emissiveIntensity:.55,metalness:.6,roughness:.2}));g.position.copy(r.origin).add(v(x,y,z));r.root.add(g);r.rings.push({g,x,y,z,checked:false});}$('#scene-instruction').textContent='方向键 / WASD 或下方按钮移动飞马。自动向前飞，穿过六道金环即可过关。Esc 随时退出。';updateSceneScore();positionFlight();}
 function positionFlight(){const r=sceneRun,worldPos=r.origin.clone().add(r.player);r.horse.position.copy(r.horse.parent.worldToLocal(worldPos.clone().add(v(0,-3.5,0))));r.horse.rotation.y=0;camera.position.copy(worldPos).add(v(0,3,-Math.max(13,6/(Math.tan(camera.fov*Math.PI/360)*camera.aspect))));controls.target.copy(worldPos).add(v(0,0,15));camera.lookAt(controls.target);}
 function stopScene(){if(!sceneRun)return;const r=sceneRun;if(r.horse){r.horse.position.copy(r.oldPosition);r.horse.rotation.copy(r.oldRotation);W.interactions.state.wings=r.savedWings;}r.root.traverse(o=>{if(o.isMesh)o.geometry.dispose();});r.root.removeFromParent();r.objects.forEach(o=>o.marker.remove());camera.position.copy(r.camera);controls.target.copy(r.target);controls.enabled=true;sceneRun=null;$('#scene-challenge').hidden=true;$('#quest-markers').replaceChildren();keys.clear();}
 function failScene(message){const q=QUESTS.find(q=>q.id===save.active);stopScene();document.body.classList.remove('challenge-active');body.innerHTML=`<span class="eyebrow">再试一次也没关系</span><h2 id="quest-dialog-title">${q.title}</h2><p>${message}</p><p>不会扣除徽章或星光。也可以在任务手册开启「舒缓挑战」。</p><button class="primary" id="scene-retry">再试一次</button>`;open();$('#scene-retry').onclick=()=>{dialog.close();startChallenge(currentStep(save));};}
 function update(dt,time){adventure?.globalUpdate(dt);festival?.update(time);travel?.update(dt);life?.update(dt);lastTime=time;handsOn?.update(dt);for(const [id,g]of Object.entries(rewardGroups)){g.visible=save.completed.includes(id)&&(id==='ocean'?current.world==='underwater':current.world==='sky');if(!reduced)g.rotation.y=time*.15;}
 for(const p of bursts.slice()){const age=time-p.userData.burstAt;if(age>7){p.geometry.dispose();p.material.dispose();p.removeFromParent();bursts.splice(bursts.indexOf(p),1);continue;}const a=p.geometry.attributes.position;for(let i=0;i<a.count;i++){const theta=i*2.399,r=(age%2.3)*5,ph=Math.acos(1-2*(i+.5)/a.count);a.setXYZ(i,Math.sin(ph)*Math.cos(theta)*r,Math.cos(ph)*r+6-Math.pow(age%2.3,2),Math.sin(ph)*Math.sin(theta)*r);}a.needsUpdate=true;p.material.opacity=Math.max(.1,1-(age%2.3)/2.3);}
 const r=sceneRun;if(!r)return;r.elapsed+=dt;
 if(r.step.kind==='flight'){const speed=save.slow?6:9,steer=7;let dx=(keys.has('ArrowLeft')||keys.has('KeyA')?1:0)-(keys.has('ArrowRight')||keys.has('KeyD')?1:0),dy=(keys.has('ArrowUp')||keys.has('KeyW')?1:0)-(keys.has('ArrowDown')||keys.has('KeyS')?1:0);r.player.x=T.MathUtils.clamp(r.player.x+dx*dt*steer,-7,7);r.player.y=T.MathUtils.clamp(r.player.y+dy*dt*steer,-5,5);r.player.z+=dt*speed;positionFlight();for(const ring of r.rings){if(!ring.checked&&r.player.z>=ring.z){ring.checked=true;r.gate++;if(Math.hypot(r.player.x-ring.x,r.player.y-ring.y)<2.4){r.score++;ring.g.visible=false;bridge.note(520+r.score*35,.25);}else{ring.g.material=W.K.mat('#bd5879');bridge.toast('错过这一环，瞄准下一道金环。');}updateSceneScore();}}if(r.gate===9){const {step,score}=r;if(score>=6){stopScene();document.body.classList.remove('challenge-active');send({type:'challenge',place:step.place,kind:'flight',result:{hits:score,total:9,score:Math.round(score/9*100)}});}else failScene(`这次穿过了 ${score}/9 道星环，需要至少六道。`);}return;}
 if(!save.slow&&r.elapsed>=60){failScene('这一轮时间到了！你找到的路线会帮助你更快完成下一次挑战。');return;}r.objects.forEach((o,i)=>{if(r.collected.has(i))return;o.g.position.y=o.base.y+(reduced?0:Math.sin(time*1.1+i)*.16);const pos=o.g.getWorldPosition(v()).add(v(0,.85,0)).project(camera);o.marker.hidden=pos.z<-1||pos.z>1||Math.abs(pos.x)>1||Math.abs(pos.y)>1;o.marker.style.transform=`translate(-50%,-50%) translate(${(pos.x*.5+.5)*innerWidth}px,${(-pos.y*.5+.5)*innerHeight}px)`;});updateSceneScore();}
 function setMode(force){cancel();mode=force||(mode==='game'?'explore':'game');document.body.classList.toggle('game-mode',mode==='game');$('#game-mode').setAttribute('aria-pressed',String(mode==='game'));$('#game-mode span').textContent=mode==='game'?'自由探索':'返回游戏';$('.quest-tracker').hidden=mode!=='game';if(mode==='game')render();}
 $('#quest-book').onclick=()=>{cancel();journal();};$('#game-closet').onclick=()=>{cancel();closet();};$('#game-mode').onclick=()=>setMode();$('#quest-minimize').onclick=()=>{const folded=$('.quest-tracker').classList.toggle('folded');$('#quest-minimize').textContent=folded?'+':'−';};$('#cancel-challenge').onclick=()=>{cancel();bridge.toast('已暂停这一局，任务进度保留。');};dialog.querySelector('.close-dialog').onclick=()=>dialog.close();challengeDialog.querySelector('.close-dialog').onclick=cancel;challengeDialog.addEventListener('close',()=>{panelStop?.();panelStop=null;document.body.classList.remove('challenge-active');});
 $$('[data-steer]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.steer);};b.onpointerup=b.onpointercancel=()=>keys.delete(b.dataset.steer);});
 addEventListener('keydown',e=>{if(handsOn||life?.busy()||travel?.busy()||adventure?.busy())return;if(e.repeat&&e.code==='KeyE')return;if(e.code==='Escape'&&sceneRun){cancel();e.preventDefault();return;}if(document.querySelector('dialog[open]'))return;if(sceneRun){if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){e.preventDefault();keys.add(e.code);}if(/^[1-9]$/.test(e.key)){e.preventDefault();collect(+e.key-1);}return;}if(mode==='game'&&e.code==='KeyE'){e.preventDefault();next();}if(e.code==='KeyJ'){e.preventDefault();journal();}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{if(document.hidden&&sceneRun){cancel();bridge.toast('游戏已暂停，回来后可重新开始这一局。');}});
 const canvas=$('#scene');canvas.addEventListener('pointerdown',e=>{if(sceneRun)down={x:e.clientX,y:e.clientY,id:e.pointerId};},true);canvas.addEventListener('pointerup',e=>{if(!sceneRun)return;e.gameConsumed=true;const start=down;down=null;if(!start||start.id!==e.pointerId||Math.hypot(e.clientX-start.x,e.clientY-start.y)>8||sceneRun.step.kind==='flight')return;pointer.set(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(sceneRun.objects.filter((o,i)=>!sceneRun.collected.has(i)).map(o=>o.g),true);if(hits.length){let g=hits[0].object;while(g&&!sceneRun.objects.some(o=>o.g===g))g=g.parent;collect(sceneRun.objects.findIndex(o=>o.g===g));}},true);
 life=createLifestyle({scene,camera,controls,bridge,beforeOpen:()=>{cancel();if(dialog.open)dialog.close();$('#game-win').hidden=true;}});$('#dream-life').onclick=()=>life.open();$$('[data-life-shortcut]').forEach(b=>b.onclick=()=>life.open(b.dataset.lifeShortcut));
 adventure=createAdventure({life,W,camera,scene,bridge,travel:()=>travel,openLife:(mode,origin)=>{life.open(mode);if(origin)life.setReturn(()=>travel.open(origin,true));}});travel=createTravel({W,scene,camera,controls,bridge,reduced,world:adventure,beforeOpen:()=>{cancel();if(dialog.open)dialog.close();$('#game-win').hidden=true;},reward:(coins,id)=>life.reward(coins,id),openLife:next=>{const origin=travel.debug.mode;life.open(next);life.setReturn(()=>travel.open(origin,true));}});festival=createFestivalDisplay(W,life.state,reduced);$('#world-map').onclick=()=>adventure.open();document.body.classList.add('open-world-mode');
 const look=LOOKS.find(l=>l.id===save.look);if(look&&save.look!=='everyday')bridge.outfit(look.style,look.color,look.accessory);restoreWorldRewards();render();
 return {update,onLocation,onAction,interact,busy:()=>adventure.busy()||travel.busy()||life.busy()||!!handsOn||!!sceneRun||challengeDialog.open,hasScene:()=>travel.busy()||life.busy()||!!handsOn||!!sceneRun,cancel,journal,travel,adventure,life,festival};
}
