import {T,C,v} from './kit.js';
import {canFurnitureFit} from './adventure-state.js';
export function createHomeEditor({K,root,save,camera,note,persist,render,layers,remove}){
 const list=save.world.furniture,names={chair:'贝壳椅',table:'圆角茶几',sofa:'丝绒沙发',shelf:'展示书架',plant:'花艺盆栽',petbed:'动物软垫'},btn=(n,a,val='')=>`<button data-life="craft-${a}" data-value="${val}">${n}</button>`;let type='chair',rot=0,selected=-1,dragging=false,objects=[],ghost=null;
 K.box(root,0,-.03,0,11.4,.2,9,'#eee0e8',.12);K.box(root,0,2,-4.5,11.4,4,.18,'#d49ab8',.1);K.box(root,-5.7,2,0,.18,4,9,'#dcc4df',.1);for(let x of [-3.8,0,3.8]){K.arch(root,x,.6,-4.38,2.6,3,C.cream,.12);K.box(root,x,2,-4.36,2.4,2.5,.04,'#acc7df');}K.rug(root,0,.09,0,3.8,2.6,'#c996bc');K.box(root,0,.09,3.8,2.5,.04,1,'#e0d0c2');
 function mesh(p,preview=false){const g=K.group(root,names[p.type],p.x,.12,p.z);g.rotation.y=p.rot*Math.PI/2;if(p.type==='chair')K.chair(g,0,0,0,C.rose,0,.48);if(p.type==='table'){K.box(g,0,.85,0,2.4,.16,1.7,C.cream,.13);for(let x of [-.9,.9])for(let z of [-.6,.6])K.rod(g,[x,0,z],[x,.8,z],.045,K.gold);K.bouquet(g,.5,.95,0,.55);}if(p.type==='sofa'){K.box(g,0,.45,0,2.8,.65,1.15,'#c885b1',.2);K.box(g,0,.95,-.5,2.8,.8,.22,'#d9a5c6',.13);for(let x of [-1.25,1.25])K.box(g,x,.75,0,.23,.5,1.15,'#d9a5c6',.12);}if(p.type==='shelf'){for(let y of [.15,1,1.9])K.box(g,0,y,0,1.6,.09,.75,C.cream,.03);for(let x of [-.75,.75])K.rod(g,[x,0,-.3],[x,2.1,-.3],.045,K.gold);for(let i=0;i<5;i++)K.box(g,-.55+i*.22,1.26,0,.16,.42,.4,['#c584a7','#a2b8d7','#dbbf9a'][i%3],.02);}if(p.type==='plant')K.bouquet(g,0,0,0,1.4);if(p.type==='petbed'){K.ell(g,0,.2,0,.6,.2,.5,'#ba91c4');K.torus(g,0,.32,0,.5,.10,C.cream,true);}K.optimize(g);if(preview)g.traverse(o=>{if(o.material){o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.42;}});return g;}
 function rebuild(){objects.forEach(remove);objects=list.map(mesh);layers();}rebuild();
 function point(e){const ray=new T.Raycaster();ray.layers.set(2);ray.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);return ray.ray.intersectPlane(new T.Plane(v(0,1,0),-.12),v());}
 function candidate(p){return {type:selected<0?type:list[selected].type,x:Math.round(p.x*2)/2,z:Math.round(p.z*2)/2,rot};}
 function panel(){return `<h2>自由布置会客室</h2><p>选家具后点地板摆放。选中已有家具，再拖动移动；门口和家具之间会保留空隙。</p><div class="life-grid">${Object.entries(names).map(([id,n])=>btn(n,'furniture',id)).join('')}</div>${btn('旋转 90°','homeRotate')}${btn('收纳选中家具','homeRemove')}<p>已摆放 ${list.length}/30 · ${selected>=0?'正在移动 '+names[list[selected].type]:'准备摆放 '+names[type]}</p><small>房间自动保存；门口的浅色区域保持通畅。家具可以随时收纳重摆。</small>`;}
 function action(a,val){if(a==='furniture'){type=val;selected=-1;}if(a==='homeRotate'){rot=(rot+1)%4;if(selected>=0){const p={...list[selected],rot};if(canFurnitureFit(list,p,selected)){list[selected]=p;rebuild();}else note('旋转后会挤到旁边家具，先移到空处。');}}if(a==='homeRemove'&&selected>=0){list.splice(selected,1);selected=-1;rebuild();}persist();render();}
 function down(e){const p=point(e);if(!p)return;let nearest=-1,best=.65;for(let i=0;i<list.length;i++){const d=Math.hypot(list[i].x-p.x,list[i].z-p.z);if(d<best){best=d;nearest=i;}}if(nearest>=0){selected=nearest;rot=list[selected].rot;dragging=true;render();return;}if(list.length>=30)return;const q=candidate(p);if(canFurnitureFit(list,q,selected)){if(selected>=0)list[selected]=q;else{list.push(q);selected=list.length-1;}dragging=true;rebuild();persist();render();}else note('这里与家具或门口通道重叠，换一块空地试试。');}
 function move(e){if(!dragging||selected<0)return;const p=point(e);if(!p)return;const q=candidate(p);if(ghost)remove(ghost);ghost=mesh(q,true);if(canFurnitureFit(list,q,selected)){list[selected]=q;objects[selected].position.set(q.x,.12,q.z);objects[selected].rotation.y=q.rot*Math.PI/2;}layers();}
 function up(){dragging=false;if(ghost){remove(ghost);ghost=null;}persist();render();}
 note('会客室可以自由布置。门口、桌椅和家具之间会检查间距。');
 return {panel,action,down,move,up,update(){},dispose(){},get debug(){return {list,objects};}};
}
