import {T,C,v} from './kit.js';
import {spend,give,addFood,availableFood,takeFood} from './adventure-state.js';
export function createKitchenService({K,A,root,save,camera,note,persist,render,layers,marker,remove}){
 const w=save.world,service=w.service;service.jobs??=Array.from({length:3},()=>null);service.orders??=[];service.orderId??=0;let slot=0,kind='cake',flavor='berry',held=false,last=null,pourType='base',tick=0,open=false,mistakes=0,completed=0,arrival=0,elapsed=0;
 const btn=(n,a,val='',extra='')=>`<button data-life="craft-${a}" data-value="${val}" ${extra}>${n}</button>`,names={berry:'莓果',flower:'花香',mint:'薄荷',milk:'奶香'},stations=[],guests=[];
 K.box(root,0,.58,0,12,1.16,5,'#ca83aa',.15);K.box(root,0,1.2,0,12.1,.12,5.1,C.cream,.07);for(let i=0;i<3;i++){const x=-3.9+i*3.9,g=K.group(root,'厨房工作台 '+(i+1),x,1.3,.1);K.disk(g,0,0,0,1.0,.08,K.gold);const cake=K.group(g,'正在制作的餐点');K.cyl(cake,0,.3,0,.64,.48,.6,'#c885a5',32);K.ell(cake,0,.62,0,.65,.15,.65,'#d4a679',24);const icing=K.group(cake,'精度裱花');const oven=K.group(g,'可观察烤箱',0,0,-1.8);for(let xx of [-.85,.85])K.box(oven,xx,.7,0,.12,1.4,1.3,'#93688f');K.box(oven,0,1.36,0,1.8,.12,1.3,'#93688f');K.box(oven,0,.7,.67,1.6,1.2,.05,K.glass);K.box(oven,0,.08,0,1.8,.12,1.3,'#93688f');const drink=K.cyl(g,0,.55,0,.43,.30,1.1,K.mat('#daedf8',{transparent:true,opacity:.35,depthWrite:false}),32);const liquid=K.cyl(g,0,.12,0,.37,.27,.95,K.mat('#db99ba',{roughness:.2}),28);marker(g,'工作台 '+(i+1),()=>{slot=i;render();},v(0,2.2,0));stations.push({g,cake,icing,drink,liquid,drawn:0});}
 for(let i=0;i<3;i++){const x=-4+i*4;K.table(root,x,0,-5,1.4,.85,C.cream);K.chair(root,x,0,-6.7,C.rose,0,.42);const g=A.doll(root,x,0,-7.6,{style:['picnicdress','sailor','cascade'][i],color:['#c782b1','#8baecd','#bc9fdb'][i],scale:.85,name:'等待餐点的朋友'});K.optimize(g);guests.push(g);}layers();
 function refresh(){for(let i=0;i<3;i++){const j=service.jobs[i],o=stations[i];o.cake.visible=!!j&&j.kind==='cake';o.drink.visible=o.liquid.visible=!!j&&j.kind==='drink';if(j?.kind==='cake'){o.cake.position.set(0,j.phase==='bake'?.10:0,j.phase==='bake'?-1.8:0);o.cake.scale.setScalar(j.phase==='bake'?.60:1);if(o.drawn>(j.dots?.length||0)){o.icing.children.slice().forEach(remove);o.drawn=0;}while(o.drawn<(j.dots?.length||0)){const p=j.dots[o.drawn++];K.cyl(o.icing,p[0],.77+p[2],p[1],.025,.085,.09,['#f2dce5','#db87af','#b5a3d3'][i],10);} }else if(j){const fill=Math.min(1,(j.base+j.fruit)/6);o.liquid.scale.y=Math.max(.01,fill);o.liquid.position.y=.08+fill*.45;}if(!j&&o.drawn){o.icing.children.slice().forEach(remove);o.drawn=0;}}layers();}
 function startJob(){if(service.jobs[slot]){note('这座工作台还有餐点，先完成或清理。');return;}const cost=kind==='cake'?{wheat:1,milk:1,sugar:1}:{};if(flavor==='berry')cost.berry=1;else if(flavor==='mint')cost.mint=1;else if(flavor==='flower')cost.flower=1;else if(kind==='drink')cost.milk=1;if(!spend(save,cost)){note('原料不够。农場提供小麦、草莓、薄荷，花材来自探索，奶与糖可补货。');return;}service.jobs[slot]={kind,flavor,phase:kind==='cake'?'mix':'pour',mix:0,time:0,heat:0,base:0,fruit:0,dots:[],pressure:0};refresh();persist();render();}
 function score(j){if(j.kind==='drink'){const ratio=j.fruit/Math.max(.1,j.base+j.fruit),precision=Math.max(0,1-Math.abs(ratio-1/3)*3);return Math.round(precision*65+Math.min(1,j.mix/3)*25+10);}const sectors=new Set(j.dots.map(p=>Math.floor((Math.atan2(p[1],p[0])+Math.PI)/Math.PI*4)%8)),spread=Math.min(1,j.dots.length/45),centered=j.dots.filter(p=>Math.hypot(p[0],p[1])<.62).length/Math.max(1,j.dots.length);return Math.round(j.heat*30+(sectors.size/8*.6+spread*.4)*35+centered*20+Math.max(0,15-Math.max(0,j.time-90)*.1));}
 function pack(){const j=service.jobs[slot];if(!j||(j.kind==='cake'&&j.phase!=='decorate')||(j.kind==='drink'&&(j.base+j.fruit<3||j.mix<2))){note('餐点还没有制作完成。');return;}if(j.kind==='cake'&&j.dots.length<12){note('奶油还太少，继续在蛋糕上挤出纹路。');return;}const quality=score(j);addFood(save,j.kind,names[j.flavor]+(j.kind==='cake'?'花纹纸杯蛋糕':'特调'),quality,[j.flavor,...(j.kind==='cake'?['milk']:[])]);service.jobs[slot]=null;refresh();note('成品 '+quality+' 分，已装入背包。可以送给客人，或带走交付居民委托。');persist();render();}
 function newOrder(){if(service.orders.filter(o=>!o.done).length>=3)return;const id=service.orderId++,k=id%4;service.orders.push({id,who:['米拉','乔伊','牧场主人','赶车的居民'][k],kind:k===1||k===3?'drink':'cake',tag:['flower','berry','milk','mint'][k],time:0,limit:k===3?85:150,done:false});service.orders=service.orders.filter(o=>!o.done).slice(-3);}
 function deliver(id){const o=service.orders.find(o=>o.id===+id&&!o.done);if(!o)return;const food=availableFood(save,o.kind,o.tag,0)[0];if(!food){note('背包里还没有符合这位客人口味的成品。');return;}takeFood(save,o.kind,o.tag,0);o.done=true;completed++;service.served++;const perfect=food.score>=80&&o.time<=o.limit;if(!perfect)mistakes++;else service.perfect++;save.coins+=Math.round(food.score/3)+(perfect?8:0);const g=guests[o.id%3];g.userData.leaving=0;const tray=K.group(g,'客人收到的餐点',0,1.2,.4);K.disk(tray,0,0,0,.4,.05,K.gold);if(o.kind==='cake')K.cyl(tray,0,.18,0,.22,.16,.3,'#d195b8',20);else K.cyl(tray,0,.25,0,.14,.12,.5,'#a6cae8',20);layers();if(completed>=4&&mistakes===0&&!w.flags.perfectKitchen){w.flags.perfectKitchen=true;give(save,'lace',2);give(save,'star',2);note('零失误营业完成！获得蕾丝 ×2、星光碎片 ×2。');}else note(o.who+'收到餐点，'+(perfect?'口味与出餐都很满意。':'可以继续改进精度和出餐顺序。'));persist();render();}
 function panel(){const j=service.jobs[slot],ideal=20-service.level*3;return `<h2>花会多订单厨房</h2><p>三个工作台可同时制作。烘烤时调饮，冷却时接单；做好的餐点装进共同背包。</p>${btn(open?'结束接单':'开店接单','serviceOpen')} ${btn('奶与糖各 ×3 · 9 币','restock')}<div class="adv-workstations">${stations.map((o,i)=>btn('台 '+(i+1)+(service.jobs[i]?' · '+({mix:'搅拌',bake:'烘烤',cool:'冷却',decorate:'裱花',pour:'调饮'}[service.jobs[i].phase]):' · 空闲'),'station',i)).join('')}</div><h3>工作台 ${slot+1}</h3>${j?`<p>${names[j.flavor]}${j.kind==='cake'?'蛋糕':'饮品'} · ${j.phase==='bake'?'最佳出炉 '+(ideal-2)+'–'+(ideal+3)+' 秒':j.phase==='cool'?'冷却 4 秒后可以裱花':j.phase==='mix'?'在选中台面拖动搅拌':j.phase==='decorate'?'在蛋糕上拖动挤奶油，尽量均匀覆盖':'按住选中杯子倒入，再拖动搅拌'}。</p><div id="kitchen-live"></div>${j.phase==='mix'?btn('送入烤箱','oven'):j.phase==='bake'?btn('取出烤箱','removeOven'):j.phase==='pour'?`${btn('选择基底','pourType','base')}${btn('选择风味','pourType','fruit')}${btn('改为搅拌','pourType','mix')}<small>基底 : 风味 = 2 : 1</small>`:''}${btn('装盒，放入背包','pack')}${btn('清理失败的餐点','discard')}`:`<div class="life-tabs">${btn('纸杯蛋糕','kind','cake')}${btn('手调饮品','kind','drink')}</div><div class="life-grid">${Object.entries(names).map(([id,n])=>btn(n+(flavor===id?' ✓':''),'flavor',id)).join('')}</div>${btn('准备原料并开始','job','','class="primary wide"')}`}<h3>等候订单</h3>${service.orders.filter(o=>!o.done).map(o=>`<article id="order-card-${o.id}" class="adv-card adv-order ${o.time>o.limit?'late':''}"><b>${o.who}</b><p>${names[o.tag]}${o.kind==='cake'?'蛋糕':'饮品'}</p><small id="order-time-${o.id}">${o.time>o.limit?'已超时，仍可交付但影响评价':'剩余 '+Math.ceil(o.limit-o.time)+' 秒'}</small>${btn('送出背包里的成品','order',o.id)}</article>`).join('')||'<p>开店后朋友会陆续到来。</p>'}<p>已送出 ${service.served} 份 · 本轮失误 ${mistakes}</p>${btn('升级温控设备 · 80 币 + 木材 ×2','upgrade')}<small>温控 ${service.level}/2。烤焦和丢弃会消耗已投入原料；关店后可继续制作外带餐点。</small>`;}
 function action(a,val){const j=service.jobs[slot];if(a==='station'){slot=+val;held=false;last=null;}if(a==='kind')kind=val;if(a==='flavor')flavor=val;if(a==='job')startJob();if(a==='pourType')pourType=val;if(a==='oven'){if(j?.phase!=='mix'||j.mix<2){note('面糊尚未混匀，在工作台上拖动搅拌。');return;}j.phase='bake';j.time=0;}if(a==='removeOven'&&j?.phase==='bake'){const ideal=20-service.level*3;j.heat=Math.max(0,1-Math.abs(j.time-ideal)/(ideal*.55));if(j.heat<.2){service.jobs[slot]=null;mistakes++;note('这次太生或烤焦了，原料已消耗。');}else{j.phase='cool';j.time=0;}}if(a==='pack')pack();if(a==='discard'&&j){service.jobs[slot]=null;mistakes++;note('这份餐点已清理，投入的原料不退回。');}if(a==='serviceOpen'){open=!open;if(open){arrival=0;completed=mistakes=0;if(!service.orders.some(o=>!o.done))newOrder();}}if(a==='order')deliver(val);if(a==='restock'){if(save.coins>=9){save.coins-=9;give(save,'milk',3);give(save,'sugar',3);note('奶和糖各补充了三份。');}else note('可以出售农场收成换取梦想币。');}if(a==='upgrade'){if(service.level>=2){note('设备已经升级完成。');return;}if(service.jobs.some(Boolean)){note('先取出正在制作的餐点，再升级设备。');return;}if(save.coins>=80&&spend(save,{wood:2})){save.coins-=80;service.level++;note('温控升级完成，烘烤工序缩短了。');}else note('需要 80 梦想币和木材 ×2。');}refresh();persist();render();}
 function point(e){const ray=new T.Raycaster();ray.layers.set(2);ray.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);return ray.ray.intersectPlane(new T.Plane(v(0,1,0),-2.08),v());}
 function validPoint(e){const p=point(e);return p&&Math.hypot(p.x-stations[slot].g.position.x,p.z-.1)<1.1?p:null;}
 function down(e){held=!!validPoint(e);last=null;if(held)move(e);}
 function move(e){if(!held)return;const j=service.jobs[slot],p=validPoint(e);if(!j||!p)return;const d=last?p.distanceTo(last):0;if(j.phase==='mix'||j.phase==='pour'&&pourType==='mix')j.mix=Math.min(4,j.mix+Math.min(.4,d));if(j.phase==='decorate'&&j.dots.length<350){if(last&&d<=.065)return;const x=p.x-stations[slot].g.position.x,z=p.z-.1;if(x*x+z*z<.65**2&&(!last||d>.065)){const n=j.dots.filter(a=>(a[0]-x)**2+(a[1]-z)**2<.08**2).length;j.dots.push([x,z,Math.min(.55,n*.04)]);refresh();}}last=p;}
 function up(){held=false;last=null;persist();render();}
 function update(dt){elapsed+=dt;tick+=dt;if(open){arrival+=dt;for(const o of service.orders)if(!o.done)o.time+=dt;if(arrival>22){arrival=0;newOrder();render();}}for(let i=0;i<3;i++){const j=service.jobs[i];if(!j)continue;if(j.phase==='bake'){j.time+=dt;if(j.time>37-service.level*3){service.jobs[i]=null;mistakes++;note('烤箱里的蛋糕烤焦了。下一次可以先处理快到时间的工作台。');refresh();render();}}else if(j.phase==='cool'){j.time+=dt;if(j.time>=4){j.phase='decorate';j.time=0;note('蛋糕冷却好了，可以裱花。');render();}}else if(j.phase==='decorate')j.time+=dt;if(i===slot&&held&&j.phase==='pour'&&pourType!=='mix'){if(j.base+j.fruit<7){j[pourType]+=dt*.9;j.mix=0;refresh();}}}for(const g of guests)if(g.userData.leaving!==undefined){g.userData.leaving+=dt;g.position.z=-7.6+Math.sin(Math.min(1,g.userData.leaving/3)*Math.PI)*1.4;g.rotation.y=Math.sin(Math.min(1,g.userData.leaving/3)*Math.PI)*.8;}if(tick>.3){tick=0;for(const o of service.orders){const label=document.querySelector('#order-time-'+o.id),card=document.querySelector('#order-card-'+o.id);if(label)label.textContent=o.time>o.limit?'已超时，仍可交付但影响评价':'剩余 '+Math.ceil(o.limit-o.time)+' 秒';if(card)card.classList.toggle('late',o.time>o.limit);}const el=document.querySelector('#kitchen-live'),j=service.jobs[slot];if(el&&j)el.textContent=j.phase==='bake'?'烘烤 '+j.time.toFixed(1)+' 秒':j.phase==='mix'?'搅拌 '+Math.round(j.mix/3*100)+'%':j.phase==='pour'?'基底 '+j.base.toFixed(1)+' / 风味 '+j.fruit.toFixed(1)+' · 混合 '+Math.min(100,Math.round(j.mix/3*100))+'%':j.phase==='cool'?'冷却 '+j.time.toFixed(1)+' 秒':'奶油 '+j.dots.length+' 笔';} }
 refresh();note('选择工作台准备原料，拖动台面搅拌。烤箱工作时，可以在另一座台制作饮品。');
 return {panel,action,down,move,up,update,dispose(){held=false;open=false;persist();},get debug(){return {service,stations,score,slot};}};
}
