import {T,C,v,createKit} from './kit.js';
import {TRAVEL_KEY,REGIONS,clamp,wrap,distance,roadDistance,isWater,islandCenter,isWalkable,route,nearbyStop,freshTravel,restoreTravel,completeBadge,walkRoute} from './travel-state.js';
import {buildTravelWorld,travelVehicle} from './travel-world.js';
const button=(label,action,val='',extra='')=>`<button data-travel="${action}" data-value="${val}" ${extra}>${label}</button>`;
export function createTravel({W,scene,camera,controls,bridge,beforeOpen,reward,openLife,world=null,reduced=false}){
 let state;try{state=restoreTravel(localStorage.getItem(TRAVEL_KEY));}catch{state=freshTravel();}
 let active=false,mode=state.last,K,root,map,rig,avatar,old,pose,yaw=0,speed=0,auto=null,dock=null,onFoot=false,walkGoal=null,doorOpen=false,board=null,carried=null,carryMesh=null,cargoGroup=null,riders=[],boarding=null,unloading=null,arm=false,armOffset={x:0,z:8},armLine=null,scanHeld=false,scanProgress=0,scanTarget=null,scanRing=null,grab=null,view='follow',orbit=0,clock=0,hudClock=0,saveClock=0,nearest=null,lensOpen=false,saveFailed=false;
 let rememberedFoot=null,walkPath=[];const keys=new Set(),ray=new T.Raycaster();ray.layers.set(3);const pointer=new T.Vector2(),canvas=document.querySelector('#scene');
 const ui=document.createElement('section');ui.id='travel-app';ui.hidden=true;ui.setAttribute('aria-label','远方旅行地图');ui.innerHTML=`<header class="travel-header"><strong>星光海屿群岛</strong>${button('手册 · 背包','world')}<nav>${Object.entries(REGIONS).map(([k,r])=>button(r.name,'region',k)).join('')}</nav>${button('粉晶主岛','close')}</header><aside class="travel-itinerary"><div class="travel-title"><div><small id="travel-biome"></small><h2 id="travel-title"></h2></div>${button('−','fold','','aria-label="折叠路线"')}</div><div id="travel-route-content"><div id="travel-map" aria-label="路线地图"></div><div id="travel-stops"></div><div id="travel-journal"></div></div></aside><output id="travel-readout"></output><div id="travel-notice" role="status"></div><div id="travel-nearby"></div><aside id="travel-special" hidden></aside><nav class="travel-controls"><div id="travel-actions"></div><div class="travel-pad"><button data-travel-key="up" aria-label="前进">↑</button><button data-travel-key="left" aria-label="左转">←</button><button data-travel-key="down" aria-label="后退或刹车">↓</button><button data-travel-key="right" aria-label="右转">→</button></div><div id="travel-depth"><button data-travel-key="rise">上浮 Q</button><button data-travel-key="sink">下潜 E</button></div><small id="travel-help"></small></nav>`;document.body.append(ui);const $=s=>ui.querySelector(s),markers=[];
 function note(t){$('#travel-notice').textContent=t;}
 function persist(){if(active&&pose&&!onFoot){state.locations[mode]={p:pose.toArray(),yaw,dock};}state.last=mode;try{localStorage.setItem(TRAVEL_KEY,JSON.stringify(state));saveFailed=false;}catch{saveFailed=true;}}
 function setLayers(){root.traverse(o=>o.layers.set(3));}
 function dispose(){if(!root)return;const geos=new Set(),mats=new Set();root.traverse(o=>{if(o.geometry)geos.add(o.geometry);if(o.material)for(const m of Array.isArray(o.material)?o.material:[o.material])mats.add(m);if(o.shadow?.map)o.shadow.map.dispose();});root.removeFromParent();geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());root=null;for(const m of markers)m.el.remove();markers.length=0;}
 function cargoType(){return mode==='bus'?'fruit':'flower';}
 function cargoCount(){return state.cargo.filter(c=>c===cargoType()).length;}
 function renderCargo(){if(cargoGroup)cargoGroup.removeFromParent();cargoGroup=K.group(rig.vehicle,'实际装载货物');const n=mode==='submarine'?state.cells.length:cargoCount();for(let i=0;i<n;i++){const g=map.crate(cargoGroup,mode==='bus'?0:(i-1)*.65,mode==='bus'?1.04:mode==='yacht'?1.2:.4,mode==='bus'?-2.8+i*1.2:mode==='yacht'?-3: -2,mode==='submarine'?'#a3bddd':'#dcaac4');g.scale.setScalar(mode==='bus'?.58:.45);}setLayers();}
 function makeRiders(){for(const g of riders)g.removeFromParent();riders=[];if(mode!=='bus')return;for(let i=0;i<state.passengers;i++){const g=map.A.doll(rig.vehicle,i%2?.65:-.65,.48,-1.9+Math.floor(i/2)*1.5,{style:'picnicdress',color:['#df8dab','#9fbddd','#c1acd9'][i],scale:.65,pose:'seated',name:'车内乘客'});g.userData.live=true;K.optimize(g);riders.push(g);}setLayers();}
 function reset(next){if(world&&!world.allowed(next)){note(world.lockReason(next));return;}if(root){returnCarry();persist();}world?.leaveMap();dispose();keys.clear();armLine=null;mode=next;K=createKit();root=K.group(scene,'扩展旅行地图 · '+REGIONS[mode].name);const saved=state.locations[mode];pose=v(...saved.p);yaw=saved.yaw;dock=saved.dock;speed=0;auto=null;onFoot=false;doorOpen=!!dock;walkGoal=null;walkPath=[];boarding=unloading=board=null;carried=carryMesh=null;arm=false;grab=null;scanHeld=false;scanProgress=0;scanTarget=null;orbit=0;lensOpen=false;riders=[];cargoGroup=null;
  map=buildTravelWorld(K,root,mode,state);world?.build(K,root,map,mode,state);rig=travelVehicle(K,root,mode,W);rig.vehicle.position.copy(pose);rig.vehicle.rotation.y=yaw;avatar=map.A.doll(root,0,0,0,{style:mode==='submarine'?'astronaut':'sailor',color:'#d78baa',scale:.9,hairStyle:'bun',...(world?.appearance()||{}),name:'我的旅行角色'});avatar.userData.live=true;K.optimize(avatar);avatar.visible=false;
  const hemi=new T.HemisphereLight(mode==='submarine'?'#dcecff':'#fff5eb','#78979b',mode==='submarine'?2.2:2.0),sun=new T.DirectionalLight(mode==='submarine'?'#b1d4ff':'#fff0d2',2.7),fill=new T.DirectionalLight('#f1e3ff',.9);sun.position.set(-60,100,80);fill.position.set(70,50,-90);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-60,right:60,top:60,bottom:-60,near:1,far:240});sun.shadow.bias=-.0003;sun.shadow.normalBias=.04;sun.shadow.camera.layers.set(3);root.add(hemi,sun,sun.target,fill);map.light=sun;
  scene.background=new T.Color(mode==='submarine'?'#7397bd':mode==='bus'?'#c0d7e4':'#c6dfff');scene.fog=new T.FogExp2(scene.background,mode==='submarine'?.0065:.0018);scene.environmentIntensity=mode==='submarine'?.75:.8;
  scanRing=K.torus(root,0,0,0,1,.025,K.mat('#d3ecff',{transparent:true,opacity:.48,emissive:'#81b6ee',emissiveIntensity:.6}),true);scanRing.visible=false;
  renderCargo();makeRiders();if(mode==='bus')map.dynamics.passengers.forEach((g,i)=>g.visible=!state.picked.includes('passengers')&&i>=state.passengers);
  for(const p of map.pois){const el=document.createElement('button');el.className='travel-marker';el.textContent=p.name;el.onclick=()=>approach(p);$('#travel-nearby').append(el);markers.push({p,el});}
  setLayers();world?.entered(context());frame();render();note(REGIONS[mode].stops.find(s=>s.id===dock)?.hint||'选择一个目的地自动导航，或用方向键亲自驾驶。');persist();updateCamera(1,true);
 }
 function frame(){if(!active)return;camera.clearViewOffset();camera.aspect=innerWidth/innerHeight;camera.near=.08;camera.far=900;camera.updateProjectionMatrix();}
 function render(){if(!active)return;const r=REGIONS[mode];$('#travel-title').textContent=r.name;$('#travel-biome').textContent=r.vehicle+' · '+r.stops.length+' 个停靠点';$('#travel-stops').innerHTML=r.stops.map(s=>button(`<b>${s.name}</b><small>${state.visits.includes(mode+':'+s.id)?'已到访':'探索目的地'}${dock===s.id?' · 已停靠':''}</small>`,'nav',s.id,`class="travel-stop" ${onFoot?'disabled':''}`)+(state.visits.includes(mode+':'+s.id)?button('返回此站','warp',s.id,'class="travel-warp"'):'')).join('');
  const goal=mode==='bus'?`温室鲜果送达 ${state.delivered}/3<br>山顶旅客送达 ${state.arrivals}/3`:mode==='yacht'?`庆典花架 ${state.flowers}/3<br>灯塔 ${state.lens.every((a,i)=>a===[2,5,7][i])?'已点亮':'等待校准'}`:`能源匣 ${state.cells.length}/3<br>观测基地 ${state.base?'已恢复':'等待供能'}`;$('#travel-journal').innerHTML=`<h3>这段旅程</h3><p>${goal}</p><small>完成地区委托获得服装与梦想币。<br>${saveFailed?'当前浏览器无法保存进度。':'位置、货物与探索记录自动保存在本机。'}</small>`;
  $('#travel-actions').innerHTML=button(auto?'停止导航':'选择路线','auto')+button(onFoot?'登回交通工具':mode==='submarine'?'进入基地':'下车 / 登岛','disembark')+button(mode==='bus'?(doorOpen?'关闭车门':'打开车门'):dock?'解除停靠':mode==='yacht'?'靠泊抛锚':'悬停靠近','dock')+button(view==='follow'?'俯瞰地图':'跟随视角','view')+(mode==='bus'?button(boarding?'朋友正在登车…':unloading?'朋友正在下车…':'接送候车朋友','passengers'):mode==='submarine'?'<button data-travel-hold="scan">按住声呐扫描</button>'+button(arm?'收起机械臂':'展开机械臂','arm'):button(carried?'放进游艇货舱':'取出一篮鲜花','cargo'));
  if(mode==='submarine'&&dock==='surface')$('#travel-actions').innerHTML+=button('返回海面','surface');if(mode==='bus')$('#travel-actions').innerHTML+=button(carried?'把果箱装车':'取出一箱鲜果','cargo');$('#travel-depth').hidden=mode!=='submarine'||onFoot;$('#travel-help').textContent=onFoot?'方向键 / WASD 行走 · 点地点可走过去 · Enter 互动':'方向键 / WASD 驾驶 · Enter 停靠或互动'+(mode==='submarine'?' · Q/E 升降':'');
  for(const b of ui.querySelectorAll('[data-travel="region"]'))b.setAttribute('aria-pressed',String(b.dataset.value===mode));renderSpecial();mapUI();bindPads();
 }
 function bindPads(){for(const b of ui.querySelectorAll('[data-travel-key],[data-travel-hold]')){b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture?.(e.pointerId);if(b.dataset.travelHold==='scan'){scanHeld=true;auto=null;}else keys.add(b.dataset.travelKey);};b.onpointerup=b.onpointercancel=e=>{if(b.hasPointerCapture?.(e.pointerId))b.releasePointerCapture(e.pointerId);keys.delete(b.dataset.travelKey);scanHeld=false;};}}
 function mapUI(){const r=REGIONS[mode],size=240,b=r.bounds*2+30,to=p=>[120+p[0]/b*size,120+p[2]/b*size],p=to(onFoot?avatar.position.toArray():pose.toArray()),path=mode==='bus'?r.stops.map(s=>to(s.p).join(',')).join(' '):'';$('#travel-map').innerHTML=`<svg viewBox="0 0 240 240" role="img" aria-label="${r.name}位置图"><rect x="1" y="1" width="238" height="238" rx="20" fill="${mode==='bus'?'#e4e9d8':'#d4e7f6'}"/>${path?`<polygon points="${path}" fill="none" stroke="#a98599" stroke-width="5"/>`:''}${r.stops.map(s=>{const [x,y]=to(s.p);return `<g><circle cx="${x}" cy="${y}" r="${s.id===dock?8:5}" fill="${r.color}"/><text x="${x}" y="${y-10}" text-anchor="middle" font-size="11" fill="#41364c">${s.name.slice(0,4)}</text></g>`;}).join('')}<path d="M0 -7 L5 6 L0 3 L-5 6 Z" transform="translate(${p[0]} ${p[1]}) rotate(${(Math.PI-yaw)*180/Math.PI})" fill="#b92878" stroke="white" stroke-width="1.5"/></svg>`;}
 function renderSpecial(){const panel=$('#travel-special');panel.hidden=!arm&&!lensOpen;if(arm){panel.innerHTML=`<h3>机械臂微调</h3><p>让爪子落到发光能源匣上，接近时再抓取。</p><div class="travel-arm-pad">${button('向左','armShift','left')}${button('伸远','armShift','forward')}${button('向右','armShift','right')}${button('收近','armShift','back')}</div>${button('合爪抓取','grab','','class="primary"')}<small>也可以拖动画面微调爪子。</small>`;}else if(lensOpen){panel.innerHTML=`<h3>星镜灯塔</h3><p>三枚星标分别转到刻度 <b>2 · 5 · 7</b>。环上的星星会随之移动，三层吻合后灯塔亮起。</p>${state.lens.map((n,i)=>`<div>${button('↶','lensTurn',i+':-1')}<b>${['金环','粉环','蓝环'][i]} ${n}</b>${button('↷','lensTurn',i+':1')}</div>`).join('')}${button('收起控制台','lensClose')}`;}}
 function nearestPOI(){const p=onFoot?avatar.position:pose;return map.pois.filter(o=>o.g.visible).map(o=>({p:o,d:o.g.getWorldPosition(v()).distanceTo(p)})).sort((a,b)=>a.d-b.d)[0];}
 function queueWalk(p,info={}){const valid=q=>(world?.floorY()!=null||isWalkable(q,mode,dock))&&(!world||world.walkable(v(...q),context()));const route=walkRoute(avatar.position.toArray(),p.toArray(),valid,info.boarding?9:1.7);walkPath=route.map((a,i)=>{const q=v(...a);q.userData=i===route.length-1?info:{waypoint:true};return q;});walkGoal=walkPath.shift()||null;if(!walkGoal)note('这里暂时没有可走通的路线，试试附近的入口。');}
 function approach(p){if(!onFoot){if(mode==='submarine'&&p.kind==='sample'){note('先靠近到 22 米以内并按住声呐，再展开机械臂。');return;}note('先停稳交通工具，再下车或登岛。');return;}if(p.kind==='sample')return;walkGoal=p.g.position.clone();if(world?.floorY()==null&&!isWalkable(walkGoal.toArray(),mode,dock)){note('这个位置需要在对应岛屿停靠后再探索。');walkGoal=null;return;}queueWalk(p.g.position.clone(),{poi:p});note('正在走向'+p.name+'。');}
 function attachCarry(type,id,fromCargo=false){carried={type,id,fromCargo};carryMesh=map.crate(avatar,0,1.1,.72,type==='flower'?'#d6b492':'#e3a9bd');carryMesh.scale.setScalar(.48);if(type==='flower')K.bouquet(carryMesh,0,1,0,.8);K.optimize(carryMesh);setLayers();}
 function clearCarry(){carryMesh?.removeFromParent();carryMesh=null;carried=null;}
 function returnCarry(){if(!carried)return;if(carried.fromCargo)state.cargo.push(carried.type);else state.picked=state.picked.filter(id=>id!==carried.id);clearCarry();}
 function interactPOI(p){if(!p)return;if(world?.interact(p,context()))return;if(!onFoot&&p.kind!=='sample'&&p.kind!=='base'){note('请先停稳并下车或登岛。');return;}const actor=onFoot?avatar.position:pose;if(actor.distanceTo(p.g.position)>(mode==='submarine'&&!onFoot?14:4.5)){note('再靠近一点，或点地点名称走过去。');return;}
  if(['fruit','flower'].includes(p.kind)){if(carried){note('先把手里的货物放进交通工具。');return;}if(state.picked.includes(p.id))return;state.picked.push(p.id);p.g.visible=false;attachCarry(p.kind,p.id);note('拿起了货箱。走回交通工具旁，点「装车」或「放进货舱」。');}
  if(p.kind==='deliverFruit'){if(carried?.type!=='fruit'){note('去温室取鲜果，运到市集后从大巴取出，带到这个柜台。');return;}state.delivered=Math.min(3,state.delivered+1);const g=map.crate(p.g,-1.5+state.delivered,1.42,.1);g.scale.setScalar(.5);clearCarry();note('鲜果已经摆上柜台，市集收到 '+state.delivered+'/3 箱。');checkRewards();}
  if(p.kind==='planter'){if(carried?.type!=='flower'){note('从花语外岛运来花篮，取出后带到空花架。');return;}if(p.slot!==state.flowers){note('先布置第 '+(state.flowers+1)+' 座花架。');return;}clearCarry();state.flowers++;map.dynamics.flowers[p.slot].visible=true;note('花架布置好了。'+(state.flowers===3?'舞会开始了！':'还需要 '+(3-state.flowers)+' 篮鲜花。'));checkRewards();}
  if(p.kind==='lens'){lensOpen=true;auto=null;speed=0;note('校准灯塔的三层星镜。可以随时离开，刻度会保留。');}
  if(p.kind==='farm')return openLife('farm');if(p.kind==='pet')return openLife('pet');if(p.kind==='mix')return openLife('mix');
  if(p.kind==='transferBus')return transit('bus');if(p.kind==='transferYacht')return transit('yacht');if(p.kind==='transferSubmarine')return transit('submarine');
  if(p.kind==='sample'){note(state.scanned.includes(p.id)?'已记录能源匣。将潜艇悬停在它附近，展开机械臂打捞。':'按住声呐扫描，发光环覆盖目标时会记录位置。');}
  if(p.kind==='base'){if(state.cells.length<3){note('基地还缺少 '+(3-state.cells.length)+' 枚能源匣。可以按路线探索不同深度。');return;}state.base=true;note('能源接通，基地舱门正在打开！停靠后可进入珍珠档案馆。');checkRewards();}
  if(p.kind==='archive')note('观测档案已修复：珊瑚拱、远洋沉船和晶光海沟的记录都保存在旅行手册里。');
  setLayers();persist();render();
 }
 function checkRewards(){for(const [id,title,item]of [['valley','山谷旅人','picnicdress'],['islands','群岛庆典主理人','mermaidcouture'],['ocean','深海探索员','icecape']])if(completeBadge(state,id)){reward(60,item);note('完成「'+title+'」！获得 60 梦想币和一套高级服装，已加入衣橱。');}persist();}
 function chooseRoute(id){if(world?.busy())return;if(onFoot||board){note('请先回到交通工具。');return;}returnCarry();doorOpen=false;dock=null;arm=false;scanHeld=false;lensOpen=false;auto={id,points:route(mode,pose.toArray(),id),at:0};note('导航前往'+REGIONS[mode].stops.find(s=>s.id===id).name+'。随时按方向键接管驾驶。');render();}
 function doDock(){if(onFoot)return;if(dock){dock=null;doorOpen=false;note('解除停靠，可以继续驾驶。');render();return;}const n=nearbyStop(mode,pose.toArray());if(n.d>(mode==='submarine'?18:12)){note('先靠近路线图上的停靠点。自动导航会把交通工具带到附近。');return;}if(Math.abs(speed)>2){auto=null;keys.clear();speed*=.4;note('正在减速，停稳后再操作。');return;}dock=n.s.id;speed=0;auto=null;doorOpen=true;const id=mode+':'+dock;if(!state.visits.includes(id))state.visits.push(id);note(n.s.name+' · '+n.s.hint);persist();render();}
 function disembark(){if(board)return;if(onFoot){if(avatar.position.distanceTo(pose)>11){queueWalk(pose.clone(),{boarding:true});note('正在走回交通工具。');return;}returnCarry();board={from:avatar.position.clone(),to:pose.clone().add(v(0,1.3,0)),t:0,out:false};walkGoal=null;render();return;}if(!dock||Math.abs(speed)>1){note('先在车站或码头停稳并靠泊。');return;}if(mode==='submarine'&&(dock!=='base'||!state.base)){note('潜艇只能在恢复供能后的观测基地出舱。');return;}doorOpen=true;let end;if(mode==='bus')end=pose.clone().add(v(5,0,1));else if(mode==='yacht'){const s=REGIONS.yacht.stops.find(s=>s.id===dock),c=v(...islandCenter(s));end=v(...s.p).lerp(c,.22);end.y=1.3;}else end=v(85,-37.7,50);avatar.position.copy(pose).add(v(0,mode==='bus'?1:1.4,0));avatar.visible=true;board={from:avatar.position.clone(),to:end,t:0,out:true};render();}
 function cargo(){if(!onFoot){note('下车或登岛后，在交通工具旁搬运货物。');return;}if(avatar.position.distanceTo(pose)>11){note('再走近交通工具，或点「登回交通工具」自动走回来。');return;}if(carried){if(carried.type!==cargoType()){note('这件货物属于另一条运输路线。');return;}if(cargoCount()>=3){note('货舱已装满三箱，先送往目的地。');return;}state.cargo.push(carried.type);clearCarry();note('货物已装入，车船上的货箱也会跟随你移动。');}else{const i=state.cargo.indexOf(cargoType());if(i<0){note('货舱是空的。先去农庄拿果箱，或去花语外岛领取花篮。');return;}state.cargo.splice(i,1);attachCarry(cargoType(),null,true);note('已取出一箱，带到市集柜台或庆典花架。');}renderCargo();persist();render();}
 function passengers(){if(mode!=='bus'||onFoot||boarding||unloading)return;if(!dock||!doorOpen){note('在站点停稳，打开车门再接送朋友。');return;}if(dock==='peak'&&!state.picked.includes('passengers')){boarding={i:state.passengers,t:0};note('朋友正在步行到车门，依次登车。');}else if(dock==='market'&&state.passengers){unloading={t:0,count:state.passengers};note('朋友正在下车，走向市集。');}else note(dock==='peak'?'这批朋友已接上车，下一站是花港市集。':'到云岭观景站接朋友，再送往花港市集。');render();}
 let transitTimer=null;function transit(next){if(next===mode)return;if(world&&!world.allowed(next)){note(world.lockReason(next));world.open('journal');return;}returnCarry();persist();auto=null;speed=0;ui.classList.add('travel-transition');note('正在搭乘交通工具前往'+REGIONS[next].name+'…');clearTimeout(transitTimer);transitTimer=setTimeout(()=>{if(active){reset(next);ui.classList.remove('travel-transition');}},650);}
 function context(){return {K,root,map,mode,rig,avatar,pose,yaw,dock,onFoot,state,clock,note,render,persist,setLayers,openLife,reset:transit,close,keys,walkTo:(p)=>{queueWalk(p.clone());},refreshAvatar:()=>{}};}
 function action(a,value=''){
  if(!active)return;if(a==='close'){close();return;}if(world?.flightActive()&&!['world','view','fold'].includes(a)){note('请先把飞机降落并返回码头，再操作海上交通工具。');return;}if(a==='region'){transit(value);return;}if(a==='world'){world?.open('journal');return;}if(a==='surface'){transit('yacht');return;}if(a==='fold'){ui.classList.toggle('route-folded');return;}if(a==='nav'){chooseRoute(value);return;}if(a==='auto'){if(auto){auto=null;speed=0;note('导航已停止，可以自己驾驶。');}else ui.classList.remove('route-folded');render();return;}if(a==='dock'){if(mode==='bus'&&dock){doorOpen=!doorOpen;note(doorOpen?'车门打开了。':'车门已关闭，按前进即可离站。');render();return;}doDock();return;}if(a==='disembark'){disembark();return;}if(a==='cargo'){cargo();return;}if(a==='passengers'){passengers();return;}if(a==='view'){view=view==='follow'?'map':'follow';render();return;}
  if(a==='warp'){if(!state.visits.includes(mode+':'+value)){note('先亲自抵达并发现这个站点。');return;}if(cargoCount()||state.passengers){note('货物和乘客需要实际运输，选择自动导航可以轻松前往。');return;}if(onFoot){note('先回到交通工具，再使用站点传送。');return;}const stop=REGIONS[mode].stops.find(s=>s.id===value);if(stop){auto=null;speed=0;pose.fromArray(stop.p);dock=stop.id;doorOpen=true;rig.vehicle.position.copy(pose);persist();render();note('已返回发现过的站点：'+stop.name);}return;}if(a==='near'){const n=nearestPOI();if(n)interactPOI(n.p);else doDock();return;}if(a==='lensClose'){lensOpen=false;renderSpecial();return;}if(a==='lensTurn'){if(!lensOpen||!onFoot)return;const [i,d]=value.split(':').map(Number);state.lens[i]=(state.lens[i]+d+8)%8;map.dynamics.lens[i].rotation.z=state.lens[i]*Math.PI/4;map.dynamics.beam.visible=state.lens.every((a,i)=>a===[2,5,7][i]);if(map.dynamics.beam.visible)note('星镜对齐，灯塔光束照向群岛！');checkRewards();render();return;}
  if(a==='arm'){if(mode!=='submarine'||onFoot)return;auto=null;speed=0;arm=!arm;armOffset={x:2,z:8};rig.claw.visible=arm;note(arm?'调整爪子的位置；先扫描能源匣，再靠近抓取。':'机械臂已收起。');render();return;}if(a==='armShift'){if(!arm)return;armOffset.x=clamp(armOffset.x+(value==='left'?-.6:value==='right'?.6:0),-6,6);armOffset.z=clamp(armOffset.z+(value==='forward'?.6:value==='back'?-.6:0),3,18);return;}if(a==='grab'){if(!arm||grab)return;const target=map.pois.filter(p=>p.kind==='sample'&&p.g.visible&&state.scanned.includes(p.id)).map(p=>({p,d:p.g.getWorldPosition(v()).add(v(0,.7,0)).distanceTo(rig.claw.position.clone().add(v(0,-.65,0)))})).sort((a,b)=>a.d-b.d)[0];if(!target||target.d>2.2){note('爪子还没对准已扫描的能源匣。靠近发光箱，微调左右和前后再试。');return;}grab={p:target.p,from:target.p.g.position.clone(),t:0};note('已夹住能源匣，正在收回。');return;}
 }
 function keyName(code){return {KeyW:'up',ArrowUp:'up',KeyS:'down',ArrowDown:'down',KeyA:'left',ArrowLeft:'left',KeyD:'right',ArrowRight:'right',KeyQ:'rise',KeyE:'sink'}[code];}
 ui.addEventListener('click',e=>{const b=e.target.closest('[data-travel]');if(b&&!b.disabled)action(b.dataset.travel,b.dataset.value);});
 addEventListener('keydown',e=>{if(!active||world?.busy()||/INPUT|TEXTAREA|SELECT/.test(e.target?.tagName||''))return;const k=keyName(e.code);if(k){e.preventDefault();keys.add(k);}if(e.code==='Space'&&mode==='submarine'){e.preventDefault();scanHeld=true;auto=null;}if(e.code==='Enter'){e.preventDefault();if(onFoot||mode==='submarine')action('near');else doDock();}if(e.code==='Escape'){e.preventDefault();close();}});addEventListener('keyup',e=>{keys.delete(keyName(e.code));if(e.code==='Space')scanHeld=false;});addEventListener('blur',()=>{keys.clear();scanHeld=false;});addEventListener('resize',frame);
 let drag=null;canvas.addEventListener('pointerdown',e=>{if(!active||world?.busy())return;e.stopImmediatePropagation();e.preventDefault();canvas.setPointerCapture?.(e.pointerId);drag={x:e.clientX,y:e.clientY,moved:false};},true);canvas.addEventListener('pointermove',e=>{if(!active||world?.busy()||!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)>2)drag.moved=true;if(arm){armOffset.x=clamp(armOffset.x+dx*.025,-6,6);armOffset.z=clamp(armOffset.z-dy*.03,3,18);}else orbit-=dx*.005;drag.x=e.clientX;drag.y=e.clientY;},true);canvas.addEventListener('pointerup',e=>{if(!active||world?.busy())return;e.stopImmediatePropagation();if(canvas.hasPointerCapture?.(e.pointerId))canvas.releasePointerCapture(e.pointerId);if(drag&&!drag.moved&&onFoot){pointer.set(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2);ray.setFromCamera(pointer,camera);root.updateMatrixWorld(true);const hit=ray.intersectObjects(map.pois.filter(p=>p.g.visible).map(p=>p.g),true)[0];if(hit){let g=hit.object;while(g&&!map.pois.some(p=>p.g===g))g=g.parent;const p=map.pois.find(p=>p.g===g);if(p)approach(p);}else{const plane=new T.Plane(v(0,1,0),-avatar.position.y),p=ray.ray.intersectPlane(plane,v());if(p&&(world?.floorY()!=null||isWalkable(p.toArray(),mode,dock)))queueWalk(p);}}drag=null;},true);canvas.addEventListener('pointercancel',()=>{drag=null;},true);
 function open(next=state.last,resume=false){if(world&&!world.allowed(next)){world.open('journal');world.inform?.(world.lockReason(next));return;}beforeOpen();bridge.prepare();old={position:camera.position.clone(),target:controls.target.clone(),enabled:controls.enabled,mask:camera.layers.mask,near:camera.near,far:camera.far,background:scene.background,fog:scene.fog,environmentIntensity:scene.environmentIntensity,view:camera.view?{...camera.view}:null};active=true;ui.hidden=false;document.body.classList.add('travel-active','challenge-active');controls.enabled=false;camera.layers.set(3);reset(REGIONS[next]?next:'bus');if(resume&&rememberedFoot?.mode===mode){onFoot=true;avatar.visible=true;avatar.position.fromArray(rememberedFoot.p);updateCamera(1,true);render();}}
 function close(){if(!active)return;if(onFoot)rememberedFoot={mode,p:avatar.position.toArray()};clearTimeout(transitTimer);ui.classList.remove('travel-transition');returnCarry();persist();world?.leaveMap();active=false;ui.hidden=true;keys.clear();scanHeld=false;dispose();camera.position.copy(old.position);camera.layers.mask=old.mask;camera.near=old.near;camera.far=old.far;camera.clearViewOffset();if(old.view?.enabled)camera.setViewOffset(old.view.fullWidth,old.view.fullHeight,old.view.offsetX,old.view.offsetY,old.view.width,old.view.height);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();controls.target.copy(old.target);controls.enabled=old.enabled;camera.lookAt(controls.target);scene.background=old.background;scene.fog=old.fog;scene.environmentIntensity=old.environmentIntensity;document.body.classList.remove('travel-active','challenge-active');}
 function updateCamera(dt,immediate=false){const center=(world?.cameraActor()?.getWorldPosition(v())||(onFoot||board?avatar.position:pose)).clone(),heading=world?.cameraHeading()??(onFoot?Math.PI:yaw),angle=(view==='map'?0:heading)+orbit;const mobile=innerWidth<760,dist=view==='map'?(mode==='submarine'?80:115):onFoot?16:mode==='bus'?24:30;const goal=center.clone().add(v(Math.sin(angle)*-dist,view==='map'?dist*1.15:onFoot?11:16,Math.cos(angle)*-dist));goal.y=Math.max(world?.floorY()!=null?world.floorY()+4:mode==='submarine'?-100:8,goal.y);camera.position.lerp(goal,immediate?1:Math.min(1,dt*5));const target=center.clone().add(v(0,onFoot?1.4:1.5,0));controls.target.copy(target);camera.lookAt(target);if(!mobile)camera.setViewOffset(innerWidth,innerHeight,-135,0,innerWidth,innerHeight);else if(world?.busy())camera.setViewOffset(innerWidth,innerHeight,0,innerHeight*.23,innerWidth,innerHeight);else camera.clearViewOffset();camera.updateProjectionMatrix();camera.updateMatrixWorld(true);}
 function steer(dt){const up=keys.has('up'),down=keys.has('down'),left=keys.has('left'),right=keys.has('right');if(world?.busy()||world?.driving()||board||boarding||unloading||arm||grab){speed=0;return;}if(onFoot){let dir=v();if(up||down||left||right){walkGoal=null;walkPath=[];const a=orbit;dir.set((right?1:0)-(left?1:0),0,(down?1:0)-(up?1:0)).applyAxisAngle(v(0,1,0),a);}else if(walkGoal){dir.copy(walkGoal).sub(avatar.position);dir.y=0;if(dir.length()<(walkGoal.userData?.waypoint?.28:walkGoal.userData?.boarding?10:1.8)){const info=walkGoal.userData;walkGoal=walkPath.shift()||null;if(info?.waypoint)return;if(info?.boarding)disembark();else if(info?.poi)interactPOI(info.poi);return;}}if(dir.length()){dir.normalize();const p=avatar.position.clone().addScaledVector(dir,dt*7);p.y=world?.floorY()??(mode==='bus'?.3:mode==='yacht'?1.3:-37.7);if((world?.floorY()!=null||isWalkable(p.toArray(),mode,dock))&&(!world||world.walkable(p,context()))){avatar.position.copy(p);avatar.rotation.y=Math.atan2(dir.x,dir.z);avatar.position.y+=Math.abs(Math.sin(clock*13))*.05;}}return;}
  if(up||down||left||right||keys.has('rise')||keys.has('sink')){auto=null;if(dock){dock=null;doorOpen=false;}lensOpen=false;}
  const max=mode==='bus'?24:mode==='yacht'?22:16;let desired=(up?max:0)-(down?max*.42:0);if(auto){const target=v(...auto.points[auto.at]),delta=target.clone().sub(pose);if(delta.length()<.5){auto.at++;if(auto.at>=auto.points.length){const stopId=auto.id;auto=null;speed=0;dock=stopId;doorOpen=true;if(!state.visits.includes(mode+':'+dock))state.visits.push(mode+':'+dock);if(mode==='submarine')yaw=Math.PI;note('已抵达'+REGIONS[mode].stops.find(s=>s.id===dock).name+'。'+(mode==='submarine'?'按住声呐扫描附近的能源匣。':'可以下车或登岛探索。'));persist();render();return;}}if(auto){const d=v(...auto.points[auto.at]).sub(pose),a=Math.atan2(d.x,d.z);yaw+=wrap(a-yaw)*Math.min(1,dt*3.8);desired=Math.min(max,Math.max(1,d.length()*1.8))*Math.max(.28,1-Math.abs(wrap(a-yaw))*.6);if(mode==='submarine')pose.y+=clamp(d.y,-6*dt,6*dt);}}
  if(!auto)yaw+=((left?1:0)-(right?1:0))*dt*1.45*(speed<-.5?-1:1);speed+=(desired-speed)*Math.min(1,dt*3);if(dock)speed=0;const before=pose.clone(),next=pose.clone();if(auto){const direction=v(...auto.points[auto.at]).sub(pose);direction.y=0;const len=direction.length();if(len>.01)next.addScaledVector(direction.normalize(),Math.min(len,Math.abs(speed)*dt));}else next.add(v(Math.sin(yaw)*speed*dt,0,Math.cos(yaw)*speed*dt));if(mode==='submarine'&&!auto)next.y=clamp(next.y+((keys.has('rise')?1:0)-(keys.has('sink')?1:0))*dt*8,-95,-12);const boundary=REGIONS[mode].bounds;const valid=Math.abs(next.x)<boundary&&Math.abs(next.z)<boundary&&(mode!=='bus'||roadDistance(next.toArray())<7.5)&&(mode!=='yacht'||isWater(next.toArray()));if(valid)pose.copy(next);else{speed*=.2;if(hudClock>.3)note(mode==='bus'?'靠近路边了，轻转方向盘回到路面，或重新选择自动导航。':'前面是岛岸，请绕行到码头靠泊。');}state.distance+=pose.distanceTo(before);rig.vehicle.position.copy(pose);rig.vehicle.rotation.y=yaw;
 }
 function updateBoard(dt){if(!board)return;board.t+=dt;const q=Math.min(1,board.t/1.3);avatar.position.lerpVectors(board.from,board.to,q);avatar.position.y+=Math.sin(q*Math.PI)*.35;avatar.rotation.y=Math.atan2(board.to.x-board.from.x,board.to.z-board.from.z);if(q===1){onFoot=board.out;avatar.visible=onFoot;if(!onFoot){doorOpen=false;walkGoal=null;}board=null;persist();render();}}
 function updatePassengers(dt){if(boarding){const p=map.dynamics.passengers[boarding.i];boarding.t+=dt;rig.vehicle.updateMatrixWorld(true);const to=rig.vehicle.localToWorld(v(1.8,0,2.7));p.position.lerp(to,Math.min(1,dt*2));p.position.y=.3+Math.abs(Math.sin(clock*10))*.045;p.rotation.y=Math.atan2(to.x-p.position.x,to.z-p.position.z);if(boarding.t>2.3){p.visible=false;state.passengers++;boarding.i++;boarding.t=0;makeRiders();if(boarding.i===3){state.picked.push('passengers');boarding=null;note('三位朋友都坐好了，可以前往花港市集。');persist();render();}}}if(unloading){unloading.t+=dt;for(let i=0;i<riders.length;i++){riders[i].visible=false;const p=map.dynamics.passengers[i];p.visible=true;const from=pose.clone().add(v(4,0,2)),to=v(-104+i*1.4,.3,40);p.position.lerpVectors(from,to,Math.min(1,unloading.t/3));p.position.y=.3+Math.abs(Math.sin(clock*10+i))*.045;}if(unloading.t>=3){state.arrivals=Math.min(3,state.arrivals+unloading.count);state.passengers=0;unloading=null;makeRiders();note('朋友们抵达花港市集，准备一起逛街。');checkRewards();render();}}}
 function updateScan(dt){scanRing.visible=mode==='submarine'&&scanHeld&&!onFoot;if(!scanRing.visible){scanProgress=0;scanTarget=null;return;}scanRing.position.copy(pose);scanRing.scale.setScalar(2+(clock%2)*18);const n=map.pois.filter(p=>p.kind==='sample'&&p.g.visible).map(p=>({p,d:p.g.position.distanceTo(pose)})).sort((a,b)=>a.d-b.d)[0];if(n&&n.d<23){if(scanTarget!==n.p.id){scanTarget=n.p.id;scanProgress=0;}scanProgress+=dt;if(scanProgress>=2&&!state.scanned.includes(n.p.id)){state.scanned.push(n.p.id);note('声呐记录成功：'+n.p.name+'。展开机械臂，在发光箱上合爪。');persist();render();}}}
 function updateArm(dt){if(!rig.claw)return;rig.claw.visible=arm;if(arm){const local=v(armOffset.x,0,armOffset.z).applyAxisAngle(v(0,1,0),yaw),p=pose.clone().add(local);p.y=pose.y-1.2;rig.claw.position.copy(p);rig.claw.rotation.y=yaw;if(armLine){armLine.geometry.dispose();armLine.removeFromParent();}armLine=K.tube(root,[pose.clone().add(v(0,-.6,0)),pose.clone().add(local.clone().multiplyScalar(.5)).add(v(0,-.2,0)),p],.075,K.gold,false,12);armLine.layers.set(3);}else if(armLine){armLine.removeFromParent();armLine.geometry.dispose();armLine=null;}
  if(grab){grab.t+=dt;const q=Math.min(1,grab.t/1.7),to=pose.clone().add(v(0,1,0));grab.p.g.position.lerpVectors(grab.from,to,q);if(q===1){state.cells.push(grab.p.id);grab.p.g.visible=false;grab=null;arm=false;renderCargo();note('能源匣已放入潜艇货架。收集进度 '+state.cells.length+'/3。');persist();render();}}}
 function update(dt){if(!active||document.hidden)return;dt=Math.min(dt,.08);clock+=dt;hudClock+=dt;saveClock+=dt;steer(dt);world?.update(dt,context());updateBoard(dt);updatePassengers(dt);updateScan(dt);updateArm(dt);for(const d of rig.doors)d.rotation.y+=(doorOpen?-1.5-d.rotation.y:-d.rotation.y)*Math.min(1,dt*4);for(const w of rig.wheels)w.rotation.x+=speed*dt/.6;if(rig.propeller)rig.propeller.rotation.z+=dt*(4+Math.abs(speed)*1.5);if(mode==='yacht')rig.vehicle.rotation.z=reduced?0:Math.sin(clock*1.1)*.018;
  for(const [i,a]of map.dynamics.wildlife.entries()){if(a.dance){a.g.rotation.y=state.flowers===3?Math.sin(clock+i)*.7:0;}else{a.g.position.x=a.base.x+Math.sin(clock*.3+i)*12;a.g.position.z=a.base.z+Math.cos(clock*.3+i)*8;a.g.rotation.y=-clock*.3-i;a.g.position.y=a.base.y+(a.dolphin?Math.max(0,Math.sin(clock+i))*1.4:Math.sin(clock+i)*.4);}}if(map.dynamics.gate)map.dynamics.gate.position.x+=(state.base?92-map.dynamics.gate.position.x:85-map.dynamics.gate.position.x)*Math.min(1,dt*2);if(map.dynamics.beam?.visible)map.dynamics.beam.rotation.y=clock*.15;
  map.light.position.copy(onFoot?avatar.position:pose).add(v(-40,80,40));map.light.target.position.copy(onFoot?avatar.position:pose);map.light.target.updateMatrixWorld();updateCamera(dt);root.updateMatrixWorld(true);
  for(const m of markers){const p=m.p.g.getWorldPosition(v()),d=p.distanceTo(onFoot?avatar.position:pose),q=p.add(v(0,3,0)).project(camera);m.el.hidden=!m.p.g.visible||d>27||q.z< -1||q.z>1||Math.abs(q.x)>.94||Math.abs(q.y)>.8||!onFoot;m.el.style.transform=`translate(-50%,-50%) translate(${(q.x*.5+.5)*innerWidth}px,${(.5-q.y*.5)*innerHeight}px)`;}
  if(hudClock>.16){hudClock=0;nearest=nearestPOI();$('#travel-readout').textContent=REGIONS[mode].vehicle+' · '+(onFoot?'步行探索':Math.round(Math.abs(speed)*3.6)+' km/h')+(mode==='submarine'?' · 深度 '+Math.round(-pose.y)+' m':' · 货舱 '+cargoCount()+'/3')+(mode==='bus'?' · 乘客 '+state.passengers+'/3':'')+(scanHeld?' · 扫描 '+Math.min(100,Math.round(scanProgress/2*100))+'%':'');if(nearest&&nearest.d<(onFoot?5:mode==='submarine'?15:0)){let b=$('#travel-interact');if(!b){b=document.createElement('button');b.id='travel-interact';b.dataset.travel='near';$('#travel-actions').append(b);}b.textContent='互动 · '+nearest.p.name;b.hidden=false;}else{const b=$('#travel-interact');if(b)b.hidden=true;}mapUI();}if(saveClock>2){persist();saveClock=0;}
 }
 return {open,close,update,action,busy:()=>active,get state(){return state;},get debug(){return {...context(),mode,pose,yaw,speed,dock,onFoot,avatar,map,rig,keys,auto,board,walking:!!walkGoal,carried,armOffset,arm,root,scan:()=>{scanHeld=true;},stopScan:()=>{scanHeld=false;},interact:interactPOI,approach};}};
}
