import {createHomeEditor} from './home-editor.js';
import {createKitchenService} from './kitchen-service.js';
import {addFood,spend} from './adventure-state.js';
import {T,C,v} from './kit.js';
import {CROPS,FLAVORS,DRINKS,PARTS,PAINTS,plant,water,harvest,sellCrop,fulfill,drinkScore,footprint,canPlace,erasePiece} from './craft-state.js';
export const WORKSHOPS={farm:'庄园农场',mix:'海岸调饮',cupcake:'纸杯蛋糕裱花',sand:'沙滩沙堡',blocks:'积木工坊',home:'家居布置',service:'多订单厨房'};
export function createWorkshop({mode,K,A,B,root,save,camera,note,persist,render,layers,marker,remove,navigate,publish}){
 if(mode==='home')return createHomeEditor({K,root,save,camera,note,persist,render,layers,remove});if(mode==='service')return createKitchenService({K,A,root,save,camera,note,persist,render,layers,marker,remove});
 const btn=(label,a,val='',extra='')=>`<button data-life="craft-${a}" data-value="${val}" ${extra}>${label}</button>`,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const grid=(list,a,selected)=>`<div class="life-grid">${list.map(([id,n])=>btn(n,a,id,`aria-pressed="${selected===id}"`)).join('')}</div>`;
 const s=save.craft;let time=0,held=false,lastPoint=null,tool='plant',crop='berry',activePlot=-1,waterTimer=0,waterCan,drops=[],plots=[],rabbits=[],cycle=0;
 let mixTool='pour',flavor='soda',parts={},pouring=false,pour=0,motion=0,method='stir',recipe=0,glass,liquid,stream,bottle,spoon,garnish='lemon',drinkDone=false,result=null,drinkMove=0,drinkFrom=null;
 let batterStream;let usedFlavors=new Set(),cupFlavor='milk';
 let phase='decorate',cream=PAINTS[1],nozzle='star',decor='pipe',dots=[],strokes=[],strokeAt=0,icingRoot,cup,bowl,whisk,bag,oven,phaseTime=0,mixProgress=0,mixMesh,usedProduce=false,cupRewarded=false;
 let part=mode==='sand'?'tower':'brick',color=PAINTS[0],level=0,rot=0,erase=false,buildRoot,ghost,hover=null,history=[],viewAngle=0;
 const ray=new T.Raycaster();ray.layers.set(2);const plane=new T.Plane(v(0,1,0),0);
 function point(e,y=0){camera.updateMatrixWorld(true);ray.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);plane.constant=-y;return ray.ray.intersectPlane(plane,v());}
 function changed(){layers();persist();render();}
 function baseCounter(){K.box(root,0,.55,0,8.5,1.1,5.6,'#c3769f',.20);K.box(root,0,1.14,0,8.7,.16,5.8,'#fff5e4',.10);K.box(root,0,2.0,-2.8,8,.2,.42,'#f2d6df',.03);for(let x of [-3.6,3.6]){K.plant(root,x,1.23,-1.9,.7);K.rod(root,[x,1.23,-2.8],[x,3.4,-2.8],.035,K.gold);}K.tube(root,[[-3.6,3.4,-2.8],[0,3.65,-2.8],[3.6,3.4,-2.8]],.018,K.gold);for(let x=-3;x<=3;x++)K.ell(root,x,3.4,-2.8,.07,.07,.07,K.glow,12);}
 function inventory(){return `<p class="life-inventory">${CROPS.map(c=>c.name+' '+s.inventory[c.id]).join(' · ')}</p>`;}
 function buildFarm(){K.box(root,0,.0,0,11,.10,8,'#89ae77',.2);for(let i=0;i<6;i++){let x=(i%3-1)*2.45,z=i<3?-1.65:1.45,g=K.group(root,'菜地 '+(i+1),x,.11,z);K.box(g,0,0,0,2.1,.20,2.35,'#78513d',.08);for(let d of [-1,1]){K.box(g,d*1.05,.08,0,.12,.30,2.4,'#d6b18b',.03);K.box(g,0,.08,d*1.2,2.2,.30,.12,'#d6b18b',.03);}const plants=K.group(g,'生长植株');const m=marker(g,'',()=>plotClick(i),v(0,1.2,0));plots.push({g,plants,m,key:'',height:0});}
  for(let x=-5;x<=5;x++){K.box(root,x,.66,-3.9,.09,1.3,.09,'#fff4e3',.01);}for(let y of [.5,1])K.box(root,0,y,-3.9,10,.08,.08,'#fff4e3',.01);K.box(root,4.65,.53,-1.5,1.15,1.05,1.2,'#cf90ac');const roof=K.cyl(root,4.65,1.24,-1.5,.04,.94,.65,'#a45f88',4);roof.rotation.y=Math.PI/4;K.box(root,4.65,.46,-.88,.45,.65,.035,'#533c50');for(let i=0;i<2;i++){let p=B.rabbit(root,4.5,.12,i*.9+.2,.82);K.optimize(p);rabbits.push(p);}marker(rabbits[0],'照料动物',()=>action('animals'),v(0,1.0,0));waterCan=K.group(root,'移动浇水壶');K.cyl(waterCan,0,.25,0,.22,.24,.45,'#82b8cc');K.tube(waterCan,[[.18,.28,0],[.4,.37,0],[.6,.30,0]],.04,K.gold);K.torus(waterCan,-.22,.35,0,.18,.025,K.gold);waterCan.visible=false;for(let i=0;i<12;i++){const d=K.ell(root,0,0,0,.025,.065,.025,'#8cc8ff',8);d.visible=false;drops.push(d);}refreshPlots();note('先收获第一块成熟草莓。选种子后点空地；浇水时按住菜地，也可点击地块浇满一壶。');}
 function refreshPlots(){for(let i=0;i<6;i++){const p=s.plots[i],o=plots[i],c=CROPS.find(c=>c.id===p.crop),q=c?p.growth/c.time:0,key=p.crop+':'+Math.floor(q*4);if(key!==o.key){for(const child of o.plants.children.slice())remove(child);if(c)for(let n=0;n<5;n++){const x=(n%2-.5)*.65,z=(Math.floor(n/2)-1)*.55,stem=K.group(o.plants,'枝叶',x,0,z);K.rod(stem,[0,0,0],[0,.55,0],.014,'#518250');for(let j=0;j<4;j++){let leaf=K.ell(stem,(j%2?1:-1)*.12,.16+j*.095,0,.16,.035,.075,c.id==='wheat'?'#b1a354':'#5d9a61',12);leaf.rotation.z=(j%2?1:-1)*.45;}if(q>=.5){if(c.id==='wheat'){for(let j=0;j<5;j++)K.ell(stem,(j%2-.5)*.08,.55+j*.045,0,.045,.075,.035,c.color,10);}else if(c.id==='berry'){K.ell(stem,.10,.3,.11,.095,.12,.08,q>=1?c.color:'#e4b699',16);for(let j=0;j<6;j++)K.ell(stem,.06+j%3*.035,.25+Math.floor(j/3)*.07,.18,.005,.007,.005,'#f9d582',6);}}}o.key=key;K.optimize(o.plants);layers();}o.plants.scale.setScalar(.30+q*.7);o.m.el.textContent=!c?'空地 '+(i+1):p.water<1?c.name+' · 需浇水':q>=1?c.name+' · 收获':c.name+' '+Math.round(q*100)+'%';}}
 function plotClick(i){const p=s.plots[i];if(tool==='water'&&p.crop&&p.water<1){activePlot=i;waterTimer=1.35;return;}if(harvest(save,i)){note('收获 +3！食材进入仓库，可出售或带去调饮与烘焙。');refreshPlots();changed();return;}if(!p.crop){if(plant(save,i,crop)){note('种下'+CROPS.find(c=>c.id===crop).name+'，选浇水壶照料它。');}else note('梦想币不足，免费小麦种子随时可种。');}else if(p.water<1){activePlot=i;waterTimer=1.35;}else note('正在生长。可以同时经营其他菜地，或切换到调饮与动物伙伴。');refreshPlots();changed();}
 function buildDrink(){baseCounter();glass=K.group(root,'透明调饮杯',0,1.24,.3);K.cyl(glass,0,.75,0,.72,.48,1.5,K.mat('#e3effa',{transparent:true,opacity:.23,roughness:.07,depthWrite:false,side:T.DoubleSide}),48);K.torus(glass,0,1.5,0,.72,.022,K.gold,true);liquid=K.cyl(glass,0,.08,0,.66,.46,1.35,K.mat('#b3ddff',{roughness:.14,metalness:.08,transparent:true,opacity:.84}),40);liquid.scale.y=.015;for(let i=0;i<4;i++){let ice=K.box(glass,Math.sin(i*2)*.33,.95,Math.cos(i*2)*.33,.23,.23,.23,K.glass,.025);ice.name='冰块';ice.visible=false;}bottle=K.group(root,'手持调饮瓶',-1.9,2.4,.1);K.cyl(bottle,0,.3,0,.21,.23,.6,'#aed4ea');K.cyl(bottle,0,.70,0,.09,.1,.25,K.gold);stream=K.cyl(root,0,0,0,.025,.035,1,'#a5d4ed',10);stream.visible=false;spoon=K.group(glass,'搅拌匙');K.rod(spoon,[.5,.1,0],[.5,2,0],.028,K.gold);K.ell(spoon,.5,.2,0,.10,.16,.025,K.gold);for(let i=0;i<FLAVORS.length;i++){const f=FLAVORS[i],g=K.group(root,'配料瓶 '+f.id,-2.7+i*1.35,1.25,-1.8);K.cyl(g,0,.3,0,.21,.23,.6,f.color,24);K.cyl(g,0,.70,0,.085,.11,.25,K.gold);marker(g,f.name,()=>action('flavor',f.id),v(0,1.25,0));}drawGarnish();note('选择配料，按住杯子倒入；松手停止。按配方控制份量，再拖动杯子搅拌或摇匀。');}
 function drawGarnish(){const old=glass.getObjectByName('杯口装饰');if(old)remove(old);const g=K.group(glass,'杯口装饰');if(garnish==='lemon'){let q=K.cyl(g,.65,1.46,0,.29,.29,.05,'#f9d56f',32);q.rotation.x=Math.PI/2;for(let i=0;i<8;i++){const a=i/8*Math.PI*2;K.rod(g,[.65,1.46,.035],[.65+Math.cos(a)*.25,1.46+Math.sin(a)*.25,.035],.008,C.cream);}}else if(garnish==='berry'){K.ell(g,.62,1.45,0,.18,.22,.17,'#d93f76');}else for(let i=0;i<3;i++){const q=K.ell(g,.58+i*.04,1.48+i*.1,0,.16,.035,.08,'#7fb477');q.rotation.z=i*.5;}layers();}
 function startPour(){if(drinkDone)return;pouring=!pouring;note(pouring?'正在倒入，点「停止倒入」或松开杯子停止。':'已停止，配方的份量可随时查看。');render();}
 function pourStep(dt){if(['berry','mint','milk'].includes(flavor)&&!usedFlavors.has(flavor)){if(!spend(save,{[flavor]:1})){pouring=false;note('缺少这种原料，农场可以收获草莓与薄荷，厨房可补充奶。');return;}usedFlavors.add(flavor);}const total=Object.values(parts).reduce((a,b)=>a+b,0);if(total>=8){pouring=false;return;}const add=Math.min(dt*.8,8-total);parts[flavor]=(parts[flavor]||0)+add;pour+=add;motion=0;const h=(total+add)/8*1.32;liquid.scale.y=h/1.35;liquid.position.y=.10+h/2;const c=new T.Color(0,0,0);for(const f of FLAVORS)c.add(new T.Color(f.color).multiplyScalar((parts[f.id]||0)/(total+add)));liquid.material.color.copy(c);bottle.position.set(-.72,3.35,.3);bottle.rotation.z=-1.08;stream.visible=true;bottle.updateMatrixWorld(true);const start=bottle.localToWorld(v(0,.825,0)),end=v(0,glass.position.y+.10+h,.3),delta=end.clone().sub(start);stream.position.copy(start).add(end).multiplyScalar(.5);stream.scale.y=delta.length();stream.quaternion.setFromUnitVectors(v(0,1,0),delta.normalize());stream.material=K.mat(FLAVORS.find(f=>f.id===flavor).color);for(const o of glass.children)if(o.name==='冰块'){o.visible=h>.5;o.position.y=h+.03;}}
 function serveDrink(){if(drinkDone)return;if(Object.values(parts).reduce((a,b)=>a+b,0)<1){note('杯子还没装好，先倒入至少一份饮品。');return;}if(motion<2){note('还没有混合均匀，在杯子附近拖动搅拌或摇一摇。');return;}pouring=false;const score=drinkScore(parts,DRINKS[recipe],method,motion);let bonus=0;if(usedFlavors.has('berry'))bonus+=4;if(usedFlavors.has('mint'))bonus+=4;const pay=Math.floor(score/8)+bonus;save.coins+=pay;if(score>=85&&!s.drinkBook.includes(recipe))s.drinkBook.push(recipe);result={score,pay};addFood(save,'drink',DRINKS[recipe].name,score,Object.keys(parts).filter(k=>parts[k]>.2));drinkDone=true;publish?.('mix',glass);drinkMove=0;drinkFrom=glass.position.clone();note(`${score} 分，获得 ${pay} 币${bonus?'，其中 '+bonus+' 币来自农场鲜果加成':''}。配方比例、混合方式与均匀度都影响评价。`);changed();}
 function buildCup(){baseCounter();K.disk(root,0,1.27,.3,1.75,.10,K.gold);cup=K.group(root,'纸杯蛋糕',0,1.34,.3);K.cyl(cup,0,.38,0,1.03,.75,.74,'#bd74a0',48);for(let i=0;i<40;i++){const a=i/40*Math.PI*2;K.rod(cup,[Math.sin(a)*.76,.03,Math.cos(a)*.76],[Math.sin(a)*1.03,.73,Math.cos(a)*1.03],.017,i%2?'#ebc4d9':'#d68cb5');}K.ell(cup,0,.77,0,1.02,.22,1.02,'#deb17c',48);icingRoot=K.group(cup,'亲手挤出的奶油');bag=K.group(root,'裱花袋');K.cyl(bag,0,.4,0,.25,.04,.7,C.cream);K.cyl(bag,0,.015,0,.05,.012,.13,K.gold);bag.visible=false;batterStream=K.cyl(root,0,0,0,.07,.09,1,'#ebcd97',16);batterStream.visible=false;bowl=K.group(root,'搅拌碗',-2.45,1.24,.2);K.ell(bowl,0,.3,0,.7,.45,.7,'#8bb8d8');mixMesh=K.disk(bowl,0,.61,0,.62,.04,'#edd2a2');whisk=K.group(bowl,'打蛋器');for(let i=0;i<4;i++){let a=i*Math.PI/2;K.tube(whisk,[[0,1.2,0],[Math.cos(a)*.24,.68,Math.sin(a)*.24],[0,.48,0],[0,1.2,0]],.016,K.gold);}K.rod(whisk,[0,1.15,0],[.15,1.65,0],.06,'#d67aa2');oven=K.group(root,'桌面烤箱',2.75,1.24,-.5);for(const x of [-.70,.70])K.box(oven,x,.62,0,.10,1.24,1.45,'#8a658b',.03);K.box(oven,0,.62,-.69,1.4,1.24,.08,'#8a658b',.02);for(const y of [.05,1.19])K.box(oven,0,y,0,1.4,.10,1.45,'#8a658b',.03);K.ell(oven,.58,.97,.4,.06,.05,.09,K.glow,12);K.box(oven,0,.57,.75,1.22,.9,.05,K.glass);K.rod(oven,[-.43,1,.82],[.43,1,.82],.035,K.gold);K.ell(oven,.5,1.10,.77,.07,.07,.025,K.gold);note('先试着在蛋糕顶上拖动挤奶油。可换花嘴、颜色与装饰，撤销不满意的一笔；也能从搅拌面糊开始烤一只。');}
 function dotMesh(p){const [x,y,z,c,type]=p,g=K.group(icingRoot,'奶油 '+type,x,y,z);if(type==='berry'){K.ell(g,0,.1,0,.11,.16,.10,'#d93972',16);for(let i=0;i<4;i++)K.ell(g,Math.sin(i*2)*.06,.15,Math.cos(i*2)*.08,.008,.013,.008,'#f5cd76',8);}else if(type==='pearl')K.ell(g,0,.04,0,.055,.055,.055,K.mat('#fff1d9',{metalness:.18,roughness:.15}),12);else if(type==='sprinkle'){const q=K.box(g,0,.025,0,.15,.035,.04,c,.01);q.rotation.y=x*17+z*9;}else if(type==='rose'){for(let i=0;i<7;i++){let a=i*.9;const q=K.ell(g,Math.sin(a)*.05,.05+ i*.008,Math.cos(a)*.05,.085,.04,.035,c,12);q.rotation.y=-a;}}else if(type==='star'){const q=K.cyl(g,0,.045,0,.025,.12,.12,c,10);q.rotation.y=(x+z)*3;}else K.ell(g,0,.045,0,.09,.065,.09,c,12);return g;}
 function redrawIcing(){for(const child of icingRoot.children.slice())remove(child);for(const p of dots)dotMesh(p);K.optimize(icingRoot);layers();}
 function pipeAt(p){if(phase!=='decorate'||!p)return;let x=p.x-cup.position.x,z=p.z-cup.position.z;if(x*x+z*z>1.02**2)return;const type=decor==='pipe'?nozzle:decor;if(dots.length>=700){note('这一只已经装饰得很丰富了，可以保存作品，再做下一只。');return;}if(lastPoint&&lastPoint.distanceTo(p)<(type==='rose'?.16:.085))return;const near=dots.filter(a=>(a[0]-x)**2+(a[2]-z)**2<.095**2).length,y=.776+.22*Math.sqrt(Math.max(0,1-(x*x+z*z)/(1.02**2)))+Math.min(.8,near*.045);const d=[x,y,z,cream,type];dots.push(d);dotMesh(d);bag.visible=decor==='pipe';bag.position.set(p.x,cup.position.y+y+.12,p.z);lastPoint=p.clone();layers();}
 function saveCup(){if(dots.length<4){note('再加一点奶油或装饰，让它成为你的作品。');return;}s.cupcakes.unshift({name:`${nozzle==='rose'?'玫瑰':nozzle==='star'?'星纹':'云朵'}奶油 ${s.cupcakes.length+1}`,dots:dots.map(p=>[...p])});s.cupcakes=s.cupcakes.slice(0,6);note('蛋糕保存在作品柜，奶油每一笔的位置都会保留。');changed();}
 function partMesh(parent,p,preview=false){const spec=PARTS[mode].find(a=>a.id===p.id),unit=.82,h=.55,base=mode==='sand'?.16:1.24,g=K.group(parent,p.id,p.x*unit,base+p.y*h,p.z*unit);g.userData.piece=p;const fw=(p.rot?spec.d:spec.w)*unit,fd=(p.rot?spec.w:spec.d)*unit,w=spec.w*unit,d=spec.d*unit;g.position.x+=(fw-unit)/2;g.position.z+=(fd-unit)/2;g.rotation.y=p.rot?-Math.PI/2:0;const mat=preview?K.mat('#ffffff',{transparent:true,opacity:.35,depthWrite:false}):mode==='sand'?K.mat('#e7c592',{roughness:.91}):K.mat(p.color,{roughness:.24,clearcoat:.6});
  if(mode==='sand'){
   if(p.id==='tower'){K.cyl(g,0,.23,0,.33,.38,.46,mat,32);for(let i=0;i<8;i++){let a=i*Math.PI/4;K.box(g,Math.sin(a)*.28,.49,Math.cos(a)*.28,.13,.13,.13,mat,.01);}K.box(g,0,.26,.343,.10,.17,.01,'#9d7757',.01);}else if(p.id==='roof')K.cyl(g,0,.27,0,.01,.39,.53,mat,40);else if(p.id==='flag'){K.rod(g,[0,0,0],[0,.55,0],.025,K.gold);K.box(g,.14,.43,0,.29,.17,.02,p.color,.01);}else if(p.id==='stairs'){for(let i=0;i<4;i++)K.box(g,0,(i+1)*.065,-.29+i*.19,.75,(i+1)*.13,.19,mat,.01);}else if(p.id==='gate'){K.arch(g,0,0,0,w*.67,.53,mat,.14);K.box(g,0,.50,0,w,.11,d*.75,mat,.01);}else{K.box(g,0,.24,0,w-.03,.48,d*.65,mat,.02);for(let i=0;i<5;i++)K.box(g,-w/2+.16+i*(w-.32)/4,.51,0,.17,.12,d*.65,mat,.01);}
  }else{
   if(p.id==='window'||p.id==='arch'){K.box(g,-w/2+.1,.25,0,.19,.5,d-.03,mat,.025);K.box(g,w/2-.1,.25,0,.19,.5,d-.03,mat,.025);K.box(g,0,.45,0,w-.03,.15,d-.03,mat,.025);if(p.id==='window')K.box(g,0,.05,0,w-.03,.10,d-.03,mat,.015);}else if(p.id==='roof'){const geo=new T.CylinderGeometry(.001,1,.50,4);geo.rotateY(Math.PI/4);let o=K.mesh(g,geo,mat,0,.25,0);o.scale.set(w*.68,1,d*.68);}else K.box(g,0,.25,0,w-.035,.5,d-.035,mat,.045);
   if(p.id!=='roof')for(let x=0;x<spec.w;x++)for(let z=0;z<spec.d;z++)K.cyl(g,-w/2+.41+x*.82,.54,-d/2+.41+z*.82,.15,.15,.075,mat,20);
  }return g;
 }
 function buildBuilder(){if(mode==='sand'){K.box(root,0,.04,0,10,.15,9.2,'#f0d5aa',.2);K.box(root,0,-.025,-5.3,16,.08,2.8,K.mat('#a8d3f5',{roughness:.12,transparent:true,opacity:.8}),.02);for(let i=0;i<15;i++){const a=i*2.4;K.ell(root,Math.sin(a)*4.6,.18,Math.cos(a)*3.9,.09,.045,.15,i%2?'#fff3de':'#ddb4b0',12);}K.cyl(root,-5,.45,1,.40,.31,.7,'#d784ad',28);K.torus(root,-5,.78,1,.38,.035,K.gold,true);}else{baseCounter();K.box(root,0,1.21,0,7.7,.09,7.7,'#d5d2e2',.03);}
  const y=mode==='sand'?.145:1.265;for(let i=-4;i<=5;i++){K.rod(root,[i*.82-.41,y,-3.69],[i*.82-.41,y,3.69],.008,mode==='sand'?'#d4b989':'#ad9dba');K.rod(root,[-3.69,y,i*.82-.41],[3.69,y,i*.82-.41],.008,mode==='sand'?'#d4b989':'#ad9dba');}buildRoot=K.group(root,'我的'+WORKSHOPS[mode]);rebuild();note('选部件，点网格放置；先搭底层，再增加楼层。可旋转、撤销、拆除并保存整座作品。');}
 function rebuild(){for(const o of buildRoot.children.slice())remove(o);s.builds[mode].forEach((p,i)=>{const g=partMesh(buildRoot,p);g.userData.index=i;});layers();}
 function candidate(p){return {id:part,x:Math.round(p.x/.82)||0,z:Math.round(p.z/.82)||0,y:level,rot,color};}
 function showGhost(p){if(ghost)remove(ghost);ghost=null;hover=p?candidate(p):null;if(hover&&canPlace(s.builds[mode],hover,mode)&&!erase){ghost=partMesh(root,hover,true);layers();}}
 function place(p){if(!p)return;const list=s.builds[mode],q=candidate(p);if(erase){const index=list.findLastIndex(a=>a.y===level&&footprint(a,mode).some(c=>c[0]===q.x&&c[1]===q.z));if(index<0)return;const next=erasePiece(list,index,mode);if(!next){note('这块上面还支撑着其他部件，请先拆上层。');return;}history.push(list.map(p=>({...p})));s.builds[mode]=next;}else{if(!canPlace(list,q,mode)){note('这里需要空位和下层支撑。可换位置，或先回到第 1 层。');return;}history.push(list.map(p=>({...p})));list.push(q);}history=history.slice(-30);rebuild();changed();}
 function farmPanel(){return `<h2>庄园农场</h2><p>6 块菜地 · 已收获 ${s.harvested} 份<br>生长只计算游玩时间，离线不会枯萎。</p>${grid(CROPS.map(c=>[c.id,c.name+'种子 · '+(c.cost?c.cost+' 币':'免费')]),'crop',crop)}<div class="life-tabs">${btn('播种 / 收获','tool','plant',`aria-pressed="${tool==='plant'}"`)}${btn('浇水壶','tool','water',`aria-pressed="${tool==='water'}"`)}</div><p>点菜地操作；浇水可按住土地，或点地块标签。成熟后直接收获。</p><h3>仓库与经营</h3>${inventory()}${grid(CROPS.map(c=>[c.id,'卖出 '+c.name+' · +'+c.sell]),'sell','')}<div class="life-card"><b>茶会长期订单 · 40 币</b><p>草莓、薄荷、小麦各 2 份。</p>${btn('装篮交付','contract','','class="wide"')}</div>${btn('去调饮使用鲜果','jump','mix','class="wide"')}${btn('去烘焙使用小麦','jump','cupcake','class="wide"')}${btn('照料猫咪、兔子与小鹿','animals','','class="primary wide"')}`;}
 function mixPanel(){const r=DRINKS[recipe],total=Object.values(parts).reduce((a,b)=>a+b,0);return `<h2>海岸调饮</h2><p>原料会混色，液面随倒入量上升。允许自由调配，也可以回应朋友的口味。</p>${grid(DRINKS.map((r,i)=>[String(i),r.name+(s.drinkBook.includes(i)?' ✓':'')]),'drinkRecipe',String(recipe))}<div class="life-card"><b>${r.name}</b><p>${Object.entries(r.parts).map(([k,n])=>FLAVORS.find(f=>f.id===k).name+' '+n+' 份').join(' + ')}<br>${r.method==='shake'?'摇匀':'搅拌'}</p></div>${grid(FLAVORS.map(f=>[f.id,f.name]),'flavor',flavor)}${btn(pouring?'停止倒入':'持续倒入选中配料','pour','','class="wide" '+(drinkDone?'disabled':''))}<div id="craft-live" class="life-card"></div>${grid([['stir','搅拌'],['shake','摇匀']],'method',method)}<p>松开停止倒入，再在杯子附近拖动混合。不要求画准圆圈。</p>${grid([['lemon','柠檬片'],['berry','鲜莓'],['mint','薄荷叶']],'garnish',garnish)}${btn('端出这杯特调','serve','','class="primary wide" '+(drinkDone?'disabled':''))}${result?`<p>${result.score} 分 · +${result.pay} 币</p>`:''}${btn('重新调一杯','drinkReset','','class="wide"')}${inventory()}<small>倒入草莓、薄荷或奶时消耗对应原料；装杯后进入共同背包，可送给居民。</small>`;}
 function cupPanel(){return `<h2>纸杯蛋糕工作室</h2><p>${phase==='decorate'?'在蛋糕顶上拖动，奶油会逐层堆高。没有固定答案，可以自由设计。':phase==='mix'?'在左侧碗上拖动搅拌，不要求固定方向。':phase==='bake'?'蛋糕正在烤箱内膨起。':phase==='fill'?'面糊正在倒入纸杯。':'端出的作品正在送到展示台。'}</p><div id="craft-live" class="life-card"></div><h3>蛋糕口味</h3>${grid([["milk","香草奶香"],["flower","风铃花香 · 花材 ×1"]],"cupFlavor",cupFlavor)}<h3>花嘴与奶油颜色</h3>${grid([['round','圆口奶油'],['star','星纹裱花'],['rose','玫瑰花嘴']],'nozzle',nozzle)}<div class="life-colors">${PAINTS.map(c=>btn('','cream',c,`style="--swatch:${c}" aria-label="奶油 ${c}" aria-pressed="${cream===c}"`)).join('')}</div>${grid([['pipe','挤奶油'],['berry','放草莓'],['pearl','糖珠'],['sprinkle','彩糖条']],'decor',decor)}${btn('撤销上一笔','icingUndo','','class="wide"')}${phase==='mix'?btn('倒入纸杯并烘烤','bake','','class="primary wide"'):btn('从搅拌面糊开始新作','cupNew','','class="wide"')}<h3>保存与招待</h3>${btn('保存到蛋糕柜','saveCup','','class="wide"')}${btn('摆盘招待朋友','serveCup','','class="primary wide" '+(cupRewarded?'disabled':''))}<p>使用农场小麦烘焙 +5 币，鲜草莓装饰 +4 币；每只可招待一次。</p>${inventory()}${grid(s.cupcakes.map((c,i)=>[String(i),esc(c.name)]),'loadCup','')}`;}
 function builderPanel(){return `<h2>${WORKSHOPS[mode]}</h2><p>${mode==='sand'?'用圆塔、拱门、城墙与旗帜搭出海边城堡。':'搭一座多层玩偶屋、咖啡馆或小城堡。积木会对齐颗粒网格。'}<br>已放 ${s.builds[mode].length}/140 块</p>${grid(PARTS[mode].map(p=>[p.id,p.name]),'part',part)}<h3>${mode==='sand'?'旗帜颜色':'积木颜色'}</h3><div class="life-colors">${PAINTS.map(c=>btn('','blockColor',c,`style="--swatch:${c}" aria-label="颜色 ${c}" aria-pressed="${color===c}"`)).join('')}</div><div class="life-tabs">${btn('旋转部件 90°','rotatePart')}${btn(erase?'✓ 拆除模式':'拆除部件','erase')}</div><h3>正在搭第 ${level+1} 层</h3><div class="life-tabs">${Array.from({length:6},(_,i)=>btn(String(i+1),'level',String(i),`aria-pressed="${i===level}"`)).join('')}</div><p>先在空网格搭底层，上层部件需要完整支撑。拆除时先拆上层。</p><div class="life-grid">${btn('撤销','undo')}${btn('从空地重新搭','clearBuild')}</div>${btn('转动作品视角','orbit','','class="wide"')}${btn('保存这座作品','saveBuild','','class="primary wide"')}<h3>作品架</h3>${grid(s.shelves[mode].map((a,i)=>[String(i),esc(a.name)+' · '+a.parts.length+' 块']),'loadBuild','')}<small>当前搭建自动保存；作品架保留另外 4 个方案，载入后可继续修改。</small>`;}
 function panel(){return mode==='farm'?farmPanel():mode==='mix'?mixPanel():mode==='cupcake'?cupPanel():builderPanel();}
 function action(a,val){
  if(a==='jump'){navigate(val);return;}if(a==='animals'){navigate('pet');return;}
  if(mode==='farm'){if(a==='crop'){crop=val;tool='plant';}if(a==='tool')tool=val;if(a==='plot')plotClick(+val);if(a==='sell'){note(sellCrop(save,val)?'已出售 1 份农产品。':'仓库还没有这个收成，先去种植。');}if(a==='contract')note(fulfill(save)?'茶会收到新鲜食材，获得 40 币！':'订单需要草莓、薄荷、小麦各 2 份。');}
  if(mode==='mix'){if(a==='flavor'){flavor=val;mixTool='pour';pouring=false;}if(a==='pour')startPour();if(a==='method'){method=val;mixTool='mix';pouring=false;}if(a==='drinkRecipe')recipe=+val;if(a==='garnish'){garnish=val;drawGarnish();}if(a==='serve')serveDrink();if(a==='drinkReset'){parts={};usedFlavors=new Set();motion=0;pouring=false;drinkDone=false;result=null;liquid.scale.y=.015;liquid.position.y=.08;glass.position.set(0,1.24,.3);glass.rotation.set(0,0,0);for(const o of glass.children)if(o.name==='冰块')o.visible=false;}}
  if(mode==='cupcake'){if(a==='cupFlavor')cupFlavor=val;if(a==='cream')cream=val;if(a==='nozzle'){nozzle=val;decor='pipe';}if(a==='decor')decor=val;if(a==='icingUndo'){dots=dots.slice(0,strokes.pop()??Math.max(0,dots.length-1));redrawIcing();}if(a==='cupNew'){if(['bake','fill'].includes(phase))return;usedProduce=false;cupRewarded=false;phase='mix';mixProgress=0;dots=[];strokes=[];redrawIcing();cup.position.set(0,1.34,.3);cup.scale.setScalar(1);cup.visible=false;note('先在左侧面糊碗上拖动搅拌，再倒入纸杯。');}if(a==='bake'){if(phase!=='mix'||mixProgress<2){note('面糊还没搅匀，拖动碗中的打蛋器。');return;}if(!spend(save,{wheat:1,milk:1,sugar:1})){note('烘焙需要小麦、奶和糖各一份。去农场收获，或到多订单厨房补货。');return;}phase='fill';phaseTime=0;usedProduce=true;note('倒面糊、进烤箱，蛋糕会慢慢膨起。');}if(a==='saveCup'&&phase==='decorate'){saveCup();publish?.('cupcake',cup);}if(a==='loadCup'){const c=s.cupcakes[+val];if(c){phase='decorate';cupRewarded=true;usedProduce=false;dots=c.dots.map(p=>[...p]);strokes=[];cup.position.set(0,1.34,.3);cup.scale.setScalar(1);cup.visible=true;redrawIcing();}}if(a==='serveCup'){if(cupRewarded){note('这只是已保存作品的展示。烤一只新的蛋糕，再招待朋友。');return;}if(phase!=='decorate'||dots.length<4){note('先装饰一只蛋糕，再摆盘招待。');return;}if(!usedProduce){if(!spend(save,{wheat:1,milk:1,sugar:1})){note('成品需要小麦、奶和糖各一份。');return;}usedProduce=true;}if(cupFlavor==='flower'&&!spend(save,{flower:1})){note('花香蛋糕需要一份采集到的风铃花。');return;}let bonus=0;if(dots.some(p=>p[4]==='berry')&&s.inventory.berry){s.inventory.berry--;bonus=4;}const pay=8+(usedProduce?5:0)+bonus;save.coins+=pay;const coverage=new Set(dots.map(p=>Math.floor((Math.atan2(p[2],p[0])+Math.PI)/Math.PI*4)%8)).size;const quality=Math.min(100,35+coverage*5+Math.min(25,dots.length*.45));addFood(save,'cake',cupFlavor==='flower'?'风铃花香纸杯蛋糕':'奶油纸杯蛋糕',quality,['milk',cupFlavor,...(bonus?['berry']:[])]);cupRewarded=true;publish?.('cupcake',cup);phase='served';phaseTime=0;note('朋友收到了你的蛋糕！+'+pay+' 币，作品也存入蛋糕柜。');saveCup();}}
  if(['sand','blocks'].includes(mode)){if(a==='part'){part=val;erase=false;}if(a==='blockColor')color=val;if(a==='level')level=+val;if(a==='rotatePart')rot=1-rot;if(a==='erase')erase=!erase;if(a==='undo'&&history.length){s.builds[mode]=history.pop();rebuild();}if(a==='clearBuild'){history.push(s.builds[mode].map(p=>({...p})));s.builds[mode]=[];rebuild();}if(a==='saveBuild'){if(!s.builds[mode].length){note('先搭几块，再保存作品。');return;}s.shelves[mode].unshift({name:WORKSHOPS[mode]+' '+(s.shelves[mode].length+1),parts:s.builds[mode].map(p=>({...p}))});s.shelves[mode]=s.shelves[mode].slice(0,4);publish?.(mode,buildRoot);note(mode==='sand'?'作品已保存，也摆到了豪宅的沙滩上。':'作品已保存，也摆到了海滩积木台上。');}if(a==='loadBuild'&&s.shelves[mode][+val]){history.push(s.builds[mode].map(p=>({...p})));s.builds[mode]=s.shelves[mode][+val].parts.map(p=>({...p}));rebuild();publish?.(mode,buildRoot);}if(a==='orbit'){viewAngle+=Math.PI/4;return {orbit:Math.PI/4};}if(ghost){remove(ghost);ghost=null;}}
  changed();return null;
 }
 function down(e){held=true;lastPoint=null;if(mode==='farm'){const p=point(e,.12);if(p){const i=plots.findIndex(o=>Math.abs(p.x-o.g.position.x)<1.12&&Math.abs(p.z-o.g.position.z)<1.25);if(i>=0){activePlot=i;plotClick(i);}}}else if(mode==='mix'){const p=point(e,2.1);if(p&&Math.hypot(p.x,p.z-.3)<1.7&&!drinkDone&&mixTool==='pour'){pouring=true;render();}}else if(mode==='cupcake'){if(phase==='decorate'){strokeAt=dots.length;strokes.push(strokeAt);pipeAt(point(e,cup.position.y+1));}}else{place(point(e,(mode==='sand'?.16:1.24)+level*.55));}}
 function move(e){if(mode==='farm'&&held){const p=point(e,.12);if(p){const i=plots.findIndex(o=>Math.abs(p.x-o.g.position.x)<1.12&&Math.abs(p.z-o.g.position.z)<1.25);if(i>=0)activePlot=i;}}else if(mode==='mix'&&held&&!drinkDone&&mixTool==='mix'){const p=point(e,2.1);if(p){if(lastPoint){const d=p.distanceTo(lastPoint);if(d>.03){pouring=false;motion=Math.min(6,motion+Math.min(.4,d));spoon.rotation.y+=d*2.4;if(method==='shake')glass.rotation.z=Math.sin(motion*8)*.18;}}lastPoint=p;}}else if(mode==='cupcake'&&held){if(phase==='decorate'){if(decor==='pipe')pipeAt(point(e,cup.position.y+1));}else if(phase==='mix'){const p=point(e,1.9);if(p&&Math.hypot(p.x+2.45,p.z-.2)<1.5){if(lastPoint){const d=Math.min(.4,p.distanceTo(lastPoint));mixProgress=Math.min(3,mixProgress+d);whisk.rotation.y+=d*3;mixMesh.rotation.y+=d*3;}lastPoint=p;}}}else if(['sand','blocks'].includes(mode))showGhost(point(e,(mode==='sand'?.16:1.24)+level*.55));}
 function up(){held=false;pouring=false;lastPoint=null;if(mode==='cupcake'){bag.visible=false;if(phase==='decorate')K.optimize(icingRoot);layers();}if(mode==='mix')glass.rotation.z=0;persist();render();}
 function update(dt){time+=dt;cycle+=dt;if(mode==='farm'){if(activePlot>=0&&(waterTimer>0||held&&tool==='water')){waterTimer=Math.max(0,waterTimer-dt);const o=plots[activePlot],p=s.plots[activePlot];water(save,activePlot,dt/1.15);waterCan.visible=true;waterCan.position.copy(o.g.position).add(v(-.25,1.3,0));waterCan.rotation.z=-.25;drops.forEach((d,i)=>{d.visible=true;d.position.copy(o.g.position).add(v(Math.sin(i*2)*.35,1.1-((time*1.6+i/12)%1)*.95,Math.cos(i*2)*.45));});if(p.water>=1&&!held)waterTimer=0;}else{waterCan.visible=false;drops.forEach(d=>d.visible=false);}for(let i=0;i<rabbits.length;i++){let p=rabbits[i];p.position.z=.5+Math.sin(time*.35+i)*.8;p.position.y=.12+Math.abs(Math.sin(time*5+i))*.045;}if(cycle>.35){refreshPlots();cycle=0;}}
  if(mode==='mix'){if(pouring&&!drinkDone)pourStep(dt);else{stream.visible=false;bottle.position.lerp(v(-1.9,2.4,.1),dt*5);bottle.rotation.z*=Math.max(0,1-dt*6);}if(drinkDone){drinkMove=Math.min(1,drinkMove+dt*.8);glass.position.lerpVectors(drinkFrom,v(2.35,1.24,.1),drinkMove);}if(cycle>.15){cycle=0;const el=document.querySelector('#craft-live');if(el)el.textContent=FLAVORS.filter(f=>parts[f.id]).map(f=>f.name+' '+parts[f.id].toFixed(1)).join(' · ')+'　混合 '+Math.min(100,Math.round(motion/5*100))+'%';}}
  if(mode==='cupcake'){if(phase==='fill'){phaseTime+=dt;const f=Math.min(1,phaseTime/1.5);bowl.position.lerpVectors(v(-2.45,1.24,.2),v(-.55,2.6,.3),Math.sin(f*Math.PI));bowl.rotation.z=-Math.sin(f*Math.PI)*.8;cup.visible=true;cup.scale.y=Math.max(.25,f);batterStream.visible=f>.25&&f<.8;if(batterStream.visible){const start=bowl.position.clone().add(v(.48,.5,0)),end=v(0,1.75,.3),delta=end.clone().sub(start);batterStream.position.copy(start).add(end).multiplyScalar(.5);batterStream.scale.y=delta.length();batterStream.quaternion.setFromUnitVectors(v(0,1,0),delta.normalize());}if(phaseTime>1.5){phase='bake';phaseTime=0;batterStream.visible=false;bowl.position.set(-2.45,1.24,.2);bowl.rotation.z=0;render();}}if(phase==='bake'){phaseTime+=dt;cup.position.set(2.75,1.35,-.5);cup.scale.set(.48,.30+Math.min(1,phaseTime/6)*.18,.48);if(phaseTime>=6){phase='decorate';cup.position.set(0,1.34,.3);cup.scale.setScalar(1);note('蛋糕烤好了！现在可以亲手挤奶油、摆草莓和糖珠。');changed();}}if(phase==='served'){phaseTime+=dt;cup.position.x=Math.min(1.8,phaseTime*.8);}if(cycle>.15){cycle=0;const el=document.querySelector('#craft-live');if(el)el.textContent=phase==='mix'?'面糊均匀度 '+Math.round(mixProgress/3*100)+'%':phase==='bake'?'烘焙 '+Math.round(phaseTime/6*100)+'%':'已装饰 '+dots.length+' 笔 · '+(usedProduce?'农场小麦蛋糕':'香草蛋糕');}}
 }
 if(mode==='farm')buildFarm();else if(mode==='mix')buildDrink();else if(mode==='cupcake')buildCup();else buildBuilder();
 return {panel,action,down,move,up,update,get debug(){return {phase,dots,parts,motion,level,plots,build:s.builds[mode]};},dispose(){pouring=false;held=false;}};
}
